-- =====================================================================
-- Jayvi Foods — Pincode seed, file 18 of 21: pincodes rows 15441-16405
-- Run supabase_seed_pincodes_01_states.sql FIRST. Files 02-21 can then
-- run in any order (each is independent, uses ON CONFLICT DO NOTHING —
-- safe to re-run this specific file if it fails partway).
-- This file: 965 rows.
-- =====================================================================

insert into public.pincodes (pincode, state, serviceable, active, source) values
  ('642101', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642102', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642103', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642104', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642105', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642106', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642107', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642108', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642109', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642110', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642111', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642112', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642113', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642114', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642117', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642120', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642122', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642123', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642125', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642126', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642127', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642128', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642129', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642130', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642132', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642133', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642134', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642154', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642201', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642202', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642203', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642204', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642205', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642206', 'Tamil Nadu', true, true, 'india_post_import'),
  ('642207', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643001', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643002', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643003', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643004', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643005', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643006', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643007', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643101', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643102', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643103', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643105', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643201', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643202', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643203', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643204', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643205', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643206', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643207', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643209', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643211', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643212', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643213', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643214', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643215', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643216', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643217', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643218', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643219', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643220', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643221', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643223', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643224', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643225', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643226', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643231', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643233', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643236', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643237', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643238', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643239', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643240', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643241', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643242', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643243', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643253', 'Tamil Nadu', true, true, 'india_post_import'),
  ('643270', 'Tamil Nadu', true, true, 'india_post_import'),
  ('500001', 'Telangana', true, true, 'india_post_import'),
  ('500002', 'Telangana', true, true, 'india_post_import'),
  ('500003', 'Telangana', true, true, 'india_post_import'),
  ('500004', 'Telangana', true, true, 'india_post_import'),
  ('500005', 'Telangana', true, true, 'india_post_import'),
  ('500006', 'Telangana', true, true, 'india_post_import'),
  ('500007', 'Telangana', true, true, 'india_post_import'),
  ('500008', 'Telangana', true, true, 'india_post_import'),
  ('500009', 'Telangana', true, true, 'india_post_import'),
  ('500010', 'Telangana', true, true, 'india_post_import'),
  ('500011', 'Telangana', true, true, 'india_post_import'),
  ('500012', 'Telangana', true, true, 'india_post_import'),
  ('500013', 'Telangana', true, true, 'india_post_import'),
  ('500014', 'Telangana', true, true, 'india_post_import'),
  ('500015', 'Telangana', true, true, 'india_post_import'),
  ('500016', 'Telangana', true, true, 'india_post_import'),
  ('500017', 'Telangana', true, true, 'india_post_import'),
  ('500018', 'Telangana', true, true, 'india_post_import'),
  ('500019', 'Telangana', true, true, 'india_post_import'),
  ('500020', 'Telangana', true, true, 'india_post_import'),
  ('500022', 'Telangana', true, true, 'india_post_import'),
  ('500023', 'Telangana', true, true, 'india_post_import'),
  ('500024', 'Telangana', true, true, 'india_post_import'),
  ('500025', 'Telangana', true, true, 'india_post_import'),
  ('500026', 'Telangana', true, true, 'india_post_import'),
  ('500027', 'Telangana', true, true, 'india_post_import'),
  ('500028', 'Telangana', true, true, 'india_post_import'),
  ('500029', 'Telangana', true, true, 'india_post_import'),
  ('500030', 'Telangana', true, true, 'india_post_import'),
  ('500031', 'Telangana', true, true, 'india_post_import'),
  ('500032', 'Telangana', true, true, 'india_post_import'),
  ('500033', 'Telangana', true, true, 'india_post_import'),
  ('500034', 'Telangana', true, true, 'india_post_import'),
  ('500035', 'Telangana', true, true, 'india_post_import'),
  ('500036', 'Telangana', true, true, 'india_post_import'),
  ('500037', 'Telangana', true, true, 'india_post_import'),
  ('500038', 'Telangana', true, true, 'india_post_import'),
  ('500039', 'Telangana', true, true, 'india_post_import'),
  ('500040', 'Telangana', true, true, 'india_post_import'),
  ('500041', 'Telangana', true, true, 'india_post_import'),
  ('500042', 'Telangana', true, true, 'india_post_import'),
  ('500043', 'Telangana', true, true, 'india_post_import'),
  ('500044', 'Telangana', true, true, 'india_post_import'),
  ('500045', 'Telangana', true, true, 'india_post_import'),
  ('500046', 'Telangana', true, true, 'india_post_import'),
  ('500047', 'Telangana', true, true, 'india_post_import'),
  ('500048', 'Telangana', true, true, 'india_post_import'),
  ('500049', 'Telangana', true, true, 'india_post_import'),
  ('500050', 'Telangana', true, true, 'india_post_import'),
  ('500051', 'Telangana', true, true, 'india_post_import'),
  ('500052', 'Telangana', true, true, 'india_post_import'),
  ('500053', 'Telangana', true, true, 'india_post_import'),
  ('500054', 'Telangana', true, true, 'india_post_import'),
  ('500055', 'Telangana', true, true, 'india_post_import'),
  ('500056', 'Telangana', true, true, 'india_post_import'),
  ('500057', 'Telangana', true, true, 'india_post_import'),
  ('500058', 'Telangana', true, true, 'india_post_import'),
  ('500059', 'Telangana', true, true, 'india_post_import'),
  ('500060', 'Telangana', true, true, 'india_post_import'),
  ('500061', 'Telangana', true, true, 'india_post_import'),
  ('500062', 'Telangana', true, true, 'india_post_import'),
  ('500063', 'Telangana', true, true, 'india_post_import'),
  ('500064', 'Telangana', true, true, 'india_post_import'),
  ('500065', 'Telangana', true, true, 'india_post_import'),
  ('500066', 'Telangana', true, true, 'india_post_import'),
  ('500067', 'Telangana', true, true, 'india_post_import'),
  ('500068', 'Telangana', true, true, 'india_post_import'),
  ('500069', 'Telangana', true, true, 'india_post_import'),
  ('500070', 'Telangana', true, true, 'india_post_import'),
  ('500072', 'Telangana', true, true, 'india_post_import'),
  ('500073', 'Telangana', true, true, 'india_post_import'),
  ('500074', 'Telangana', true, true, 'india_post_import'),
  ('500075', 'Telangana', true, true, 'india_post_import'),
  ('500076', 'Telangana', true, true, 'india_post_import'),
  ('500077', 'Telangana', true, true, 'india_post_import'),
  ('500078', 'Telangana', true, true, 'india_post_import'),
  ('500079', 'Telangana', true, true, 'india_post_import'),
  ('500080', 'Telangana', true, true, 'india_post_import'),
  ('500081', 'Telangana', true, true, 'india_post_import'),
  ('500082', 'Telangana', true, true, 'india_post_import'),
  ('500083', 'Telangana', true, true, 'india_post_import'),
  ('500084', 'Telangana', true, true, 'india_post_import'),
  ('500085', 'Telangana', true, true, 'india_post_import'),
  ('500086', 'Telangana', true, true, 'india_post_import'),
  ('500087', 'Telangana', true, true, 'india_post_import'),
  ('500088', 'Telangana', true, true, 'india_post_import'),
  ('500089', 'Telangana', true, true, 'india_post_import'),
  ('500090', 'Telangana', true, true, 'india_post_import'),
  ('500091', 'Telangana', true, true, 'india_post_import'),
  ('500092', 'Telangana', true, true, 'india_post_import'),
  ('500093', 'Telangana', true, true, 'india_post_import'),
  ('500094', 'Telangana', true, true, 'india_post_import'),
  ('500095', 'Telangana', true, true, 'india_post_import'),
  ('500096', 'Telangana', true, true, 'india_post_import'),
  ('500097', 'Telangana', true, true, 'india_post_import'),
  ('500098', 'Telangana', true, true, 'india_post_import'),
  ('500100', 'Telangana', true, true, 'india_post_import'),
  ('500101', 'Telangana', true, true, 'india_post_import'),
  ('500102', 'Telangana', true, true, 'india_post_import'),
  ('500103', 'Telangana', true, true, 'india_post_import'),
  ('500104', 'Telangana', true, true, 'india_post_import'),
  ('500107', 'Telangana', true, true, 'india_post_import'),
  ('500108', 'Telangana', true, true, 'india_post_import'),
  ('500109', 'Telangana', true, true, 'india_post_import'),
  ('500110', 'Telangana', true, true, 'india_post_import'),
  ('500111', 'Telangana', true, true, 'india_post_import'),
  ('500112', 'Telangana', true, true, 'india_post_import'),
  ('500113', 'Telangana', true, true, 'india_post_import'),
  ('500114', 'Telangana', true, true, 'india_post_import'),
  ('500115', 'Telangana', true, true, 'india_post_import'),
  ('501101', 'Telangana', true, true, 'india_post_import'),
  ('501102', 'Telangana', true, true, 'india_post_import'),
  ('501106', 'Telangana', true, true, 'india_post_import'),
  ('501111', 'Telangana', true, true, 'india_post_import'),
  ('501121', 'Telangana', true, true, 'india_post_import'),
  ('501141', 'Telangana', true, true, 'india_post_import'),
  ('501142', 'Telangana', true, true, 'india_post_import'),
  ('501143', 'Telangana', true, true, 'india_post_import'),
  ('501144', 'Telangana', true, true, 'india_post_import'),
  ('501158', 'Telangana', true, true, 'india_post_import'),
  ('501202', 'Telangana', true, true, 'india_post_import'),
  ('501203', 'Telangana', true, true, 'india_post_import'),
  ('501218', 'Telangana', true, true, 'india_post_import'),
  ('501301', 'Telangana', true, true, 'india_post_import'),
  ('501359', 'Telangana', true, true, 'india_post_import'),
  ('501401', 'Telangana', true, true, 'india_post_import'),
  ('501501', 'Telangana', true, true, 'india_post_import'),
  ('501502', 'Telangana', true, true, 'india_post_import'),
  ('501503', 'Telangana', true, true, 'india_post_import'),
  ('501504', 'Telangana', true, true, 'india_post_import'),
  ('501505', 'Telangana', true, true, 'india_post_import'),
  ('501506', 'Telangana', true, true, 'india_post_import'),
  ('501508', 'Telangana', true, true, 'india_post_import'),
  ('501509', 'Telangana', true, true, 'india_post_import'),
  ('501510', 'Telangana', true, true, 'india_post_import'),
  ('501511', 'Telangana', true, true, 'india_post_import'),
  ('501512', 'Telangana', true, true, 'india_post_import'),
  ('502001', 'Telangana', true, true, 'india_post_import'),
  ('502032', 'Telangana', true, true, 'india_post_import'),
  ('502101', 'Telangana', true, true, 'india_post_import'),
  ('502102', 'Telangana', true, true, 'india_post_import'),
  ('502103', 'Telangana', true, true, 'india_post_import'),
  ('502107', 'Telangana', true, true, 'india_post_import'),
  ('502108', 'Telangana', true, true, 'india_post_import'),
  ('502109', 'Telangana', true, true, 'india_post_import'),
  ('502110', 'Telangana', true, true, 'india_post_import'),
  ('502113', 'Telangana', true, true, 'india_post_import'),
  ('502114', 'Telangana', true, true, 'india_post_import'),
  ('502115', 'Telangana', true, true, 'india_post_import'),
  ('502117', 'Telangana', true, true, 'india_post_import'),
  ('502125', 'Telangana', true, true, 'india_post_import'),
  ('502130', 'Telangana', true, true, 'india_post_import'),
  ('502205', 'Telangana', true, true, 'india_post_import'),
  ('502210', 'Telangana', true, true, 'india_post_import'),
  ('502220', 'Telangana', true, true, 'india_post_import'),
  ('502221', 'Telangana', true, true, 'india_post_import'),
  ('502228', 'Telangana', true, true, 'india_post_import'),
  ('502246', 'Telangana', true, true, 'india_post_import'),
  ('502247', 'Telangana', true, true, 'india_post_import'),
  ('502248', 'Telangana', true, true, 'india_post_import'),
  ('502249', 'Telangana', true, true, 'india_post_import'),
  ('502251', 'Telangana', true, true, 'india_post_import'),
  ('502255', 'Telangana', true, true, 'india_post_import'),
  ('502256', 'Telangana', true, true, 'india_post_import'),
  ('502257', 'Telangana', true, true, 'india_post_import'),
  ('502267', 'Telangana', true, true, 'india_post_import'),
  ('502269', 'Telangana', true, true, 'india_post_import'),
  ('502270', 'Telangana', true, true, 'india_post_import'),
  ('502271', 'Telangana', true, true, 'india_post_import'),
  ('502273', 'Telangana', true, true, 'india_post_import'),
  ('502276', 'Telangana', true, true, 'india_post_import'),
  ('502277', 'Telangana', true, true, 'india_post_import'),
  ('502278', 'Telangana', true, true, 'india_post_import'),
  ('502279', 'Telangana', true, true, 'india_post_import'),
  ('502280', 'Telangana', true, true, 'india_post_import'),
  ('502281', 'Telangana', true, true, 'india_post_import'),
  ('502285', 'Telangana', true, true, 'india_post_import'),
  ('502286', 'Telangana', true, true, 'india_post_import'),
  ('502287', 'Telangana', true, true, 'india_post_import'),
  ('502290', 'Telangana', true, true, 'india_post_import'),
  ('502291', 'Telangana', true, true, 'india_post_import'),
  ('502293', 'Telangana', true, true, 'india_post_import'),
  ('502294', 'Telangana', true, true, 'india_post_import'),
  ('502295', 'Telangana', true, true, 'india_post_import'),
  ('502296', 'Telangana', true, true, 'india_post_import'),
  ('502300', 'Telangana', true, true, 'india_post_import'),
  ('502301', 'Telangana', true, true, 'india_post_import'),
  ('502302', 'Telangana', true, true, 'india_post_import'),
  ('502303', 'Telangana', true, true, 'india_post_import'),
  ('502305', 'Telangana', true, true, 'india_post_import'),
  ('502306', 'Telangana', true, true, 'india_post_import'),
  ('502307', 'Telangana', true, true, 'india_post_import'),
  ('502310', 'Telangana', true, true, 'india_post_import'),
  ('502311', 'Telangana', true, true, 'india_post_import'),
  ('502312', 'Telangana', true, true, 'india_post_import'),
  ('502313', 'Telangana', true, true, 'india_post_import'),
  ('502314', 'Telangana', true, true, 'india_post_import'),
  ('502316', 'Telangana', true, true, 'india_post_import'),
  ('502318', 'Telangana', true, true, 'india_post_import'),
  ('502319', 'Telangana', true, true, 'india_post_import'),
  ('502321', 'Telangana', true, true, 'india_post_import'),
  ('502324', 'Telangana', true, true, 'india_post_import'),
  ('502325', 'Telangana', true, true, 'india_post_import'),
  ('502329', 'Telangana', true, true, 'india_post_import'),
  ('502331', 'Telangana', true, true, 'india_post_import'),
  ('502334', 'Telangana', true, true, 'india_post_import'),
  ('502335', 'Telangana', true, true, 'india_post_import'),
  ('502336', 'Telangana', true, true, 'india_post_import'),
  ('502345', 'Telangana', true, true, 'india_post_import'),
  ('502371', 'Telangana', true, true, 'india_post_import'),
  ('502372', 'Telangana', true, true, 'india_post_import'),
  ('502375', 'Telangana', true, true, 'india_post_import'),
  ('502381', 'Telangana', true, true, 'india_post_import'),
  ('503001', 'Telangana', true, true, 'india_post_import'),
  ('503002', 'Telangana', true, true, 'india_post_import'),
  ('503003', 'Telangana', true, true, 'india_post_import'),
  ('503101', 'Telangana', true, true, 'india_post_import'),
  ('503102', 'Telangana', true, true, 'india_post_import'),
  ('503108', 'Telangana', true, true, 'india_post_import'),
  ('503110', 'Telangana', true, true, 'india_post_import'),
  ('503111', 'Telangana', true, true, 'india_post_import'),
  ('503112', 'Telangana', true, true, 'india_post_import'),
  ('503114', 'Telangana', true, true, 'india_post_import'),
  ('503120', 'Telangana', true, true, 'india_post_import'),
  ('503122', 'Telangana', true, true, 'india_post_import'),
  ('503123', 'Telangana', true, true, 'india_post_import'),
  ('503124', 'Telangana', true, true, 'india_post_import'),
  ('503125', 'Telangana', true, true, 'india_post_import'),
  ('503144', 'Telangana', true, true, 'india_post_import'),
  ('503164', 'Telangana', true, true, 'india_post_import'),
  ('503165', 'Telangana', true, true, 'india_post_import'),
  ('503174', 'Telangana', true, true, 'india_post_import'),
  ('503175', 'Telangana', true, true, 'india_post_import'),
  ('503180', 'Telangana', true, true, 'india_post_import'),
  ('503185', 'Telangana', true, true, 'india_post_import'),
  ('503186', 'Telangana', true, true, 'india_post_import'),
  ('503187', 'Telangana', true, true, 'india_post_import'),
  ('503201', 'Telangana', true, true, 'india_post_import'),
  ('503202', 'Telangana', true, true, 'india_post_import'),
  ('503206', 'Telangana', true, true, 'india_post_import'),
  ('503207', 'Telangana', true, true, 'india_post_import'),
  ('503212', 'Telangana', true, true, 'india_post_import'),
  ('503213', 'Telangana', true, true, 'india_post_import'),
  ('503217', 'Telangana', true, true, 'india_post_import'),
  ('503218', 'Telangana', true, true, 'india_post_import'),
  ('503219', 'Telangana', true, true, 'india_post_import'),
  ('503223', 'Telangana', true, true, 'india_post_import'),
  ('503224', 'Telangana', true, true, 'india_post_import'),
  ('503245', 'Telangana', true, true, 'india_post_import'),
  ('503246', 'Telangana', true, true, 'india_post_import'),
  ('503301', 'Telangana', true, true, 'india_post_import'),
  ('503302', 'Telangana', true, true, 'india_post_import'),
  ('503305', 'Telangana', true, true, 'india_post_import'),
  ('503306', 'Telangana', true, true, 'india_post_import'),
  ('503307', 'Telangana', true, true, 'india_post_import'),
  ('503308', 'Telangana', true, true, 'india_post_import'),
  ('503309', 'Telangana', true, true, 'india_post_import'),
  ('503310', 'Telangana', true, true, 'india_post_import'),
  ('503311', 'Telangana', true, true, 'india_post_import'),
  ('503322', 'Telangana', true, true, 'india_post_import'),
  ('504001', 'Telangana', true, true, 'india_post_import'),
  ('504002', 'Telangana', true, true, 'india_post_import'),
  ('504101', 'Telangana', true, true, 'india_post_import'),
  ('504102', 'Telangana', true, true, 'india_post_import'),
  ('504103', 'Telangana', true, true, 'india_post_import'),
  ('504104', 'Telangana', true, true, 'india_post_import'),
  ('504105', 'Telangana', true, true, 'india_post_import'),
  ('504106', 'Telangana', true, true, 'india_post_import'),
  ('504107', 'Telangana', true, true, 'india_post_import'),
  ('504109', 'Telangana', true, true, 'india_post_import'),
  ('504110', 'Telangana', true, true, 'india_post_import'),
  ('504201', 'Telangana', true, true, 'india_post_import'),
  ('504202', 'Telangana', true, true, 'india_post_import'),
  ('504203', 'Telangana', true, true, 'india_post_import'),
  ('504204', 'Telangana', true, true, 'india_post_import'),
  ('504205', 'Telangana', true, true, 'india_post_import'),
  ('504206', 'Telangana', true, true, 'india_post_import'),
  ('504207', 'Telangana', true, true, 'india_post_import'),
  ('504208', 'Telangana', true, true, 'india_post_import'),
  ('504209', 'Telangana', true, true, 'india_post_import'),
  ('504216', 'Telangana', true, true, 'india_post_import'),
  ('504218', 'Telangana', true, true, 'india_post_import'),
  ('504219', 'Telangana', true, true, 'india_post_import'),
  ('504220', 'Telangana', true, true, 'india_post_import'),
  ('504231', 'Telangana', true, true, 'india_post_import'),
  ('504251', 'Telangana', true, true, 'india_post_import'),
  ('504272', 'Telangana', true, true, 'india_post_import'),
  ('504273', 'Telangana', true, true, 'india_post_import'),
  ('504292', 'Telangana', true, true, 'india_post_import'),
  ('504293', 'Telangana', true, true, 'india_post_import'),
  ('504294', 'Telangana', true, true, 'india_post_import'),
  ('504295', 'Telangana', true, true, 'india_post_import'),
  ('504296', 'Telangana', true, true, 'india_post_import'),
  ('504297', 'Telangana', true, true, 'india_post_import'),
  ('504299', 'Telangana', true, true, 'india_post_import'),
  ('504301', 'Telangana', true, true, 'india_post_import'),
  ('504302', 'Telangana', true, true, 'india_post_import'),
  ('504303', 'Telangana', true, true, 'india_post_import'),
  ('504304', 'Telangana', true, true, 'india_post_import'),
  ('504306', 'Telangana', true, true, 'india_post_import'),
  ('504307', 'Telangana', true, true, 'india_post_import'),
  ('504308', 'Telangana', true, true, 'india_post_import'),
  ('504309', 'Telangana', true, true, 'india_post_import'),
  ('504310', 'Telangana', true, true, 'india_post_import'),
  ('504311', 'Telangana', true, true, 'india_post_import'),
  ('504312', 'Telangana', true, true, 'india_post_import'),
  ('504313', 'Telangana', true, true, 'india_post_import'),
  ('504323', 'Telangana', true, true, 'india_post_import'),
  ('505001', 'Telangana', true, true, 'india_post_import'),
  ('505002', 'Telangana', true, true, 'india_post_import'),
  ('505101', 'Telangana', true, true, 'india_post_import'),
  ('505102', 'Telangana', true, true, 'india_post_import'),
  ('505122', 'Telangana', true, true, 'india_post_import'),
  ('505129', 'Telangana', true, true, 'india_post_import'),
  ('505152', 'Telangana', true, true, 'india_post_import'),
  ('505153', 'Telangana', true, true, 'india_post_import'),
  ('505162', 'Telangana', true, true, 'india_post_import'),
  ('505172', 'Telangana', true, true, 'india_post_import'),
  ('505174', 'Telangana', true, true, 'india_post_import'),
  ('505184', 'Telangana', true, true, 'india_post_import'),
  ('505185', 'Telangana', true, true, 'india_post_import'),
  ('505186', 'Telangana', true, true, 'india_post_import'),
  ('505188', 'Telangana', true, true, 'india_post_import'),
  ('505208', 'Telangana', true, true, 'india_post_import'),
  ('505209', 'Telangana', true, true, 'india_post_import'),
  ('505210', 'Telangana', true, true, 'india_post_import'),
  ('505211', 'Telangana', true, true, 'india_post_import'),
  ('505212', 'Telangana', true, true, 'india_post_import'),
  ('505214', 'Telangana', true, true, 'india_post_import'),
  ('505215', 'Telangana', true, true, 'india_post_import'),
  ('505301', 'Telangana', true, true, 'india_post_import'),
  ('505302', 'Telangana', true, true, 'india_post_import'),
  ('505303', 'Telangana', true, true, 'india_post_import'),
  ('505304', 'Telangana', true, true, 'india_post_import'),
  ('505305', 'Telangana', true, true, 'india_post_import'),
  ('505306', 'Telangana', true, true, 'india_post_import'),
  ('505307', 'Telangana', true, true, 'india_post_import'),
  ('505326', 'Telangana', true, true, 'india_post_import'),
  ('505327', 'Telangana', true, true, 'india_post_import'),
  ('505330', 'Telangana', true, true, 'india_post_import'),
  ('505331', 'Telangana', true, true, 'india_post_import'),
  ('505401', 'Telangana', true, true, 'india_post_import'),
  ('505402', 'Telangana', true, true, 'india_post_import'),
  ('505403', 'Telangana', true, true, 'india_post_import'),
  ('505404', 'Telangana', true, true, 'india_post_import'),
  ('505405', 'Telangana', true, true, 'india_post_import'),
  ('505415', 'Telangana', true, true, 'india_post_import'),
  ('505416', 'Telangana', true, true, 'india_post_import'),
  ('505425', 'Telangana', true, true, 'india_post_import'),
  ('505445', 'Telangana', true, true, 'india_post_import'),
  ('505450', 'Telangana', true, true, 'india_post_import'),
  ('505451', 'Telangana', true, true, 'india_post_import'),
  ('505452', 'Telangana', true, true, 'india_post_import'),
  ('505453', 'Telangana', true, true, 'india_post_import'),
  ('505454', 'Telangana', true, true, 'india_post_import'),
  ('505455', 'Telangana', true, true, 'india_post_import'),
  ('505460', 'Telangana', true, true, 'india_post_import'),
  ('505462', 'Telangana', true, true, 'india_post_import'),
  ('505466', 'Telangana', true, true, 'india_post_import'),
  ('505467', 'Telangana', true, true, 'india_post_import'),
  ('505468', 'Telangana', true, true, 'india_post_import'),
  ('505469', 'Telangana', true, true, 'india_post_import'),
  ('505470', 'Telangana', true, true, 'india_post_import'),
  ('505471', 'Telangana', true, true, 'india_post_import'),
  ('505472', 'Telangana', true, true, 'india_post_import'),
  ('505473', 'Telangana', true, true, 'india_post_import'),
  ('505474', 'Telangana', true, true, 'india_post_import'),
  ('505475', 'Telangana', true, true, 'india_post_import'),
  ('505476', 'Telangana', true, true, 'india_post_import'),
  ('505480', 'Telangana', true, true, 'india_post_import'),
  ('505481', 'Telangana', true, true, 'india_post_import'),
  ('505490', 'Telangana', true, true, 'india_post_import'),
  ('505497', 'Telangana', true, true, 'india_post_import'),
  ('505498', 'Telangana', true, true, 'india_post_import'),
  ('505501', 'Telangana', true, true, 'india_post_import'),
  ('505502', 'Telangana', true, true, 'india_post_import'),
  ('505504', 'Telangana', true, true, 'india_post_import'),
  ('505505', 'Telangana', true, true, 'india_post_import'),
  ('505514', 'Telangana', true, true, 'india_post_import'),
  ('505524', 'Telangana', true, true, 'india_post_import'),
  ('505526', 'Telangana', true, true, 'india_post_import'),
  ('505527', 'Telangana', true, true, 'india_post_import'),
  ('505528', 'Telangana', true, true, 'india_post_import'),
  ('505529', 'Telangana', true, true, 'india_post_import'),
  ('505530', 'Telangana', true, true, 'india_post_import'),
  ('505531', 'Telangana', true, true, 'india_post_import'),
  ('505532', 'Telangana', true, true, 'india_post_import'),
  ('506001', 'Telangana', true, true, 'india_post_import'),
  ('506002', 'Telangana', true, true, 'india_post_import'),
  ('506004', 'Telangana', true, true, 'india_post_import'),
  ('506005', 'Telangana', true, true, 'india_post_import'),
  ('506006', 'Telangana', true, true, 'india_post_import'),
  ('506007', 'Telangana', true, true, 'india_post_import'),
  ('506008', 'Telangana', true, true, 'india_post_import'),
  ('506009', 'Telangana', true, true, 'india_post_import'),
  ('506011', 'Telangana', true, true, 'india_post_import'),
  ('506013', 'Telangana', true, true, 'india_post_import'),
  ('506015', 'Telangana', true, true, 'india_post_import'),
  ('506101', 'Telangana', true, true, 'india_post_import'),
  ('506102', 'Telangana', true, true, 'india_post_import'),
  ('506103', 'Telangana', true, true, 'india_post_import'),
  ('506104', 'Telangana', true, true, 'india_post_import'),
  ('506105', 'Telangana', true, true, 'india_post_import'),
  ('506112', 'Telangana', true, true, 'india_post_import'),
  ('506122', 'Telangana', true, true, 'india_post_import'),
  ('506132', 'Telangana', true, true, 'india_post_import'),
  ('506134', 'Telangana', true, true, 'india_post_import'),
  ('506135', 'Telangana', true, true, 'india_post_import'),
  ('506142', 'Telangana', true, true, 'india_post_import'),
  ('506143', 'Telangana', true, true, 'india_post_import'),
  ('506144', 'Telangana', true, true, 'india_post_import'),
  ('506145', 'Telangana', true, true, 'india_post_import'),
  ('506146', 'Telangana', true, true, 'india_post_import'),
  ('506151', 'Telangana', true, true, 'india_post_import'),
  ('506163', 'Telangana', true, true, 'india_post_import'),
  ('506164', 'Telangana', true, true, 'india_post_import'),
  ('506165', 'Telangana', true, true, 'india_post_import'),
  ('506166', 'Telangana', true, true, 'india_post_import'),
  ('506167', 'Telangana', true, true, 'india_post_import'),
  ('506168', 'Telangana', true, true, 'india_post_import'),
  ('506169', 'Telangana', true, true, 'india_post_import'),
  ('506170', 'Telangana', true, true, 'india_post_import'),
  ('506172', 'Telangana', true, true, 'india_post_import'),
  ('506175', 'Telangana', true, true, 'india_post_import'),
  ('506201', 'Telangana', true, true, 'india_post_import'),
  ('506221', 'Telangana', true, true, 'india_post_import'),
  ('506222', 'Telangana', true, true, 'india_post_import'),
  ('506223', 'Telangana', true, true, 'india_post_import'),
  ('506224', 'Telangana', true, true, 'india_post_import'),
  ('506244', 'Telangana', true, true, 'india_post_import'),
  ('506252', 'Telangana', true, true, 'india_post_import'),
  ('506301', 'Telangana', true, true, 'india_post_import'),
  ('506302', 'Telangana', true, true, 'india_post_import'),
  ('506303', 'Telangana', true, true, 'india_post_import'),
  ('506310', 'Telangana', true, true, 'india_post_import'),
  ('506313', 'Telangana', true, true, 'india_post_import'),
  ('506314', 'Telangana', true, true, 'india_post_import'),
  ('506315', 'Telangana', true, true, 'india_post_import'),
  ('506316', 'Telangana', true, true, 'india_post_import'),
  ('506317', 'Telangana', true, true, 'india_post_import'),
  ('506318', 'Telangana', true, true, 'india_post_import'),
  ('506319', 'Telangana', true, true, 'india_post_import'),
  ('506324', 'Telangana', true, true, 'india_post_import'),
  ('506329', 'Telangana', true, true, 'india_post_import'),
  ('506330', 'Telangana', true, true, 'india_post_import'),
  ('506331', 'Telangana', true, true, 'india_post_import'),
  ('506332', 'Telangana', true, true, 'india_post_import'),
  ('506333', 'Telangana', true, true, 'india_post_import'),
  ('506342', 'Telangana', true, true, 'india_post_import'),
  ('506343', 'Telangana', true, true, 'india_post_import'),
  ('506344', 'Telangana', true, true, 'india_post_import'),
  ('506345', 'Telangana', true, true, 'india_post_import'),
  ('506347', 'Telangana', true, true, 'india_post_import'),
  ('506348', 'Telangana', true, true, 'india_post_import'),
  ('506349', 'Telangana', true, true, 'india_post_import'),
  ('506350', 'Telangana', true, true, 'india_post_import'),
  ('506352', 'Telangana', true, true, 'india_post_import'),
  ('506355', 'Telangana', true, true, 'india_post_import'),
  ('506356', 'Telangana', true, true, 'india_post_import'),
  ('506365', 'Telangana', true, true, 'india_post_import'),
  ('506366', 'Telangana', true, true, 'india_post_import'),
  ('506367', 'Telangana', true, true, 'india_post_import'),
  ('506368', 'Telangana', true, true, 'india_post_import'),
  ('506369', 'Telangana', true, true, 'india_post_import'),
  ('506370', 'Telangana', true, true, 'india_post_import'),
  ('506371', 'Telangana', true, true, 'india_post_import'),
  ('506381', 'Telangana', true, true, 'india_post_import'),
  ('506391', 'Telangana', true, true, 'india_post_import'),
  ('507001', 'Telangana', true, true, 'india_post_import'),
  ('507002', 'Telangana', true, true, 'india_post_import'),
  ('507003', 'Telangana', true, true, 'india_post_import'),
  ('507101', 'Telangana', true, true, 'india_post_import'),
  ('507103', 'Telangana', true, true, 'india_post_import'),
  ('507111', 'Telangana', true, true, 'india_post_import'),
  ('507114', 'Telangana', true, true, 'india_post_import'),
  ('507115', 'Telangana', true, true, 'india_post_import'),
  ('507116', 'Telangana', true, true, 'india_post_import'),
  ('507117', 'Telangana', true, true, 'india_post_import'),
  ('507118', 'Telangana', true, true, 'india_post_import'),
  ('507119', 'Telangana', true, true, 'india_post_import'),
  ('507120', 'Telangana', true, true, 'india_post_import'),
  ('507122', 'Telangana', true, true, 'india_post_import'),
  ('507123', 'Telangana', true, true, 'india_post_import'),
  ('507124', 'Telangana', true, true, 'india_post_import'),
  ('507125', 'Telangana', true, true, 'india_post_import'),
  ('507128', 'Telangana', true, true, 'india_post_import'),
  ('507133', 'Telangana', true, true, 'india_post_import'),
  ('507136', 'Telangana', true, true, 'india_post_import'),
  ('507137', 'Telangana', true, true, 'india_post_import'),
  ('507138', 'Telangana', true, true, 'india_post_import'),
  ('507140', 'Telangana', true, true, 'india_post_import'),
  ('507154', 'Telangana', true, true, 'india_post_import'),
  ('507157', 'Telangana', true, true, 'india_post_import'),
  ('507158', 'Telangana', true, true, 'india_post_import'),
  ('507159', 'Telangana', true, true, 'india_post_import'),
  ('507160', 'Telangana', true, true, 'india_post_import'),
  ('507161', 'Telangana', true, true, 'india_post_import'),
  ('507163', 'Telangana', true, true, 'india_post_import'),
  ('507164', 'Telangana', true, true, 'india_post_import'),
  ('507165', 'Telangana', true, true, 'india_post_import'),
  ('507166', 'Telangana', true, true, 'india_post_import'),
  ('507167', 'Telangana', true, true, 'india_post_import'),
  ('507168', 'Telangana', true, true, 'india_post_import'),
  ('507169', 'Telangana', true, true, 'india_post_import'),
  ('507170', 'Telangana', true, true, 'india_post_import'),
  ('507182', 'Telangana', true, true, 'india_post_import'),
  ('507183', 'Telangana', true, true, 'india_post_import'),
  ('507201', 'Telangana', true, true, 'india_post_import'),
  ('507202', 'Telangana', true, true, 'india_post_import'),
  ('507203', 'Telangana', true, true, 'india_post_import'),
  ('507204', 'Telangana', true, true, 'india_post_import'),
  ('507208', 'Telangana', true, true, 'india_post_import'),
  ('507209', 'Telangana', true, true, 'india_post_import'),
  ('507210', 'Telangana', true, true, 'india_post_import'),
  ('507211', 'Telangana', true, true, 'india_post_import'),
  ('507301', 'Telangana', true, true, 'india_post_import'),
  ('507302', 'Telangana', true, true, 'india_post_import'),
  ('507303', 'Telangana', true, true, 'india_post_import'),
  ('507304', 'Telangana', true, true, 'india_post_import'),
  ('507305', 'Telangana', true, true, 'india_post_import'),
  ('507306', 'Telangana', true, true, 'india_post_import'),
  ('507316', 'Telangana', true, true, 'india_post_import'),
  ('507318', 'Telangana', true, true, 'india_post_import'),
  ('508001', 'Telangana', true, true, 'india_post_import'),
  ('508002', 'Telangana', true, true, 'india_post_import'),
  ('508004', 'Telangana', true, true, 'india_post_import'),
  ('508101', 'Telangana', true, true, 'india_post_import'),
  ('508105', 'Telangana', true, true, 'india_post_import'),
  ('508111', 'Telangana', true, true, 'india_post_import'),
  ('508112', 'Telangana', true, true, 'india_post_import'),
  ('508113', 'Telangana', true, true, 'india_post_import'),
  ('508114', 'Telangana', true, true, 'india_post_import'),
  ('508115', 'Telangana', true, true, 'india_post_import'),
  ('508116', 'Telangana', true, true, 'india_post_import'),
  ('508117', 'Telangana', true, true, 'india_post_import'),
  ('508126', 'Telangana', true, true, 'india_post_import'),
  ('508201', 'Telangana', true, true, 'india_post_import'),
  ('508202', 'Telangana', true, true, 'india_post_import'),
  ('508204', 'Telangana', true, true, 'india_post_import'),
  ('508205', 'Telangana', true, true, 'india_post_import'),
  ('508206', 'Telangana', true, true, 'india_post_import'),
  ('508207', 'Telangana', true, true, 'india_post_import'),
  ('508208', 'Telangana', true, true, 'india_post_import'),
  ('508210', 'Telangana', true, true, 'india_post_import'),
  ('508211', 'Telangana', true, true, 'india_post_import'),
  ('508212', 'Telangana', true, true, 'india_post_import'),
  ('508213', 'Telangana', true, true, 'india_post_import'),
  ('508214', 'Telangana', true, true, 'india_post_import'),
  ('508217', 'Telangana', true, true, 'india_post_import'),
  ('508218', 'Telangana', true, true, 'india_post_import'),
  ('508221', 'Telangana', true, true, 'india_post_import'),
  ('508223', 'Telangana', true, true, 'india_post_import'),
  ('508224', 'Telangana', true, true, 'india_post_import'),
  ('508233', 'Telangana', true, true, 'india_post_import'),
  ('508234', 'Telangana', true, true, 'india_post_import'),
  ('508238', 'Telangana', true, true, 'india_post_import'),
  ('508243', 'Telangana', true, true, 'india_post_import'),
  ('508244', 'Telangana', true, true, 'india_post_import'),
  ('508245', 'Telangana', true, true, 'india_post_import'),
  ('508246', 'Telangana', true, true, 'india_post_import'),
  ('508247', 'Telangana', true, true, 'india_post_import'),
  ('508248', 'Telangana', true, true, 'india_post_import'),
  ('508250', 'Telangana', true, true, 'india_post_import'),
  ('508252', 'Telangana', true, true, 'india_post_import'),
  ('508253', 'Telangana', true, true, 'india_post_import'),
  ('508254', 'Telangana', true, true, 'india_post_import'),
  ('508255', 'Telangana', true, true, 'india_post_import'),
  ('508256', 'Telangana', true, true, 'india_post_import'),
  ('508257', 'Telangana', true, true, 'india_post_import'),
  ('508258', 'Telangana', true, true, 'india_post_import'),
  ('508266', 'Telangana', true, true, 'india_post_import'),
  ('508277', 'Telangana', true, true, 'india_post_import'),
  ('508278', 'Telangana', true, true, 'india_post_import'),
  ('508279', 'Telangana', true, true, 'india_post_import'),
  ('508280', 'Telangana', true, true, 'india_post_import'),
  ('508284', 'Telangana', true, true, 'india_post_import'),
  ('508285', 'Telangana', true, true, 'india_post_import'),
  ('508286', 'Telangana', true, true, 'india_post_import'),
  ('508355', 'Telangana', true, true, 'india_post_import'),
  ('508373', 'Telangana', true, true, 'india_post_import'),
  ('508374', 'Telangana', true, true, 'india_post_import'),
  ('508376', 'Telangana', true, true, 'india_post_import'),
  ('508377', 'Telangana', true, true, 'india_post_import'),
  ('509001', 'Telangana', true, true, 'india_post_import'),
  ('509002', 'Telangana', true, true, 'india_post_import'),
  ('509102', 'Telangana', true, true, 'india_post_import'),
  ('509103', 'Telangana', true, true, 'india_post_import'),
  ('509104', 'Telangana', true, true, 'india_post_import'),
  ('509105', 'Telangana', true, true, 'india_post_import'),
  ('509106', 'Telangana', true, true, 'india_post_import'),
  ('509110', 'Telangana', true, true, 'india_post_import'),
  ('509120', 'Telangana', true, true, 'india_post_import'),
  ('509125', 'Telangana', true, true, 'india_post_import'),
  ('509126', 'Telangana', true, true, 'india_post_import'),
  ('509127', 'Telangana', true, true, 'india_post_import'),
  ('509128', 'Telangana', true, true, 'india_post_import'),
  ('509129', 'Telangana', true, true, 'india_post_import'),
  ('509130', 'Telangana', true, true, 'india_post_import'),
  ('509131', 'Telangana', true, true, 'india_post_import'),
  ('509133', 'Telangana', true, true, 'india_post_import'),
  ('509135', 'Telangana', true, true, 'india_post_import'),
  ('509152', 'Telangana', true, true, 'india_post_import'),
  ('509153', 'Telangana', true, true, 'india_post_import'),
  ('509201', 'Telangana', true, true, 'india_post_import'),
  ('509202', 'Telangana', true, true, 'india_post_import'),
  ('509203', 'Telangana', true, true, 'india_post_import'),
  ('509204', 'Telangana', true, true, 'india_post_import'),
  ('509205', 'Telangana', true, true, 'india_post_import'),
  ('509206', 'Telangana', true, true, 'india_post_import'),
  ('509207', 'Telangana', true, true, 'india_post_import'),
  ('509208', 'Telangana', true, true, 'india_post_import'),
  ('509209', 'Telangana', true, true, 'india_post_import'),
  ('509210', 'Telangana', true, true, 'india_post_import'),
  ('509215', 'Telangana', true, true, 'india_post_import'),
  ('509216', 'Telangana', true, true, 'india_post_import'),
  ('509217', 'Telangana', true, true, 'india_post_import'),
  ('509219', 'Telangana', true, true, 'india_post_import'),
  ('509228', 'Telangana', true, true, 'india_post_import'),
  ('509235', 'Telangana', true, true, 'india_post_import'),
  ('509301', 'Telangana', true, true, 'india_post_import'),
  ('509302', 'Telangana', true, true, 'india_post_import'),
  ('509311', 'Telangana', true, true, 'india_post_import'),
  ('509320', 'Telangana', true, true, 'india_post_import'),
  ('509321', 'Telangana', true, true, 'india_post_import'),
  ('509325', 'Telangana', true, true, 'india_post_import'),
  ('509326', 'Telangana', true, true, 'india_post_import'),
  ('509327', 'Telangana', true, true, 'india_post_import'),
  ('509334', 'Telangana', true, true, 'india_post_import'),
  ('509335', 'Telangana', true, true, 'india_post_import'),
  ('509336', 'Telangana', true, true, 'india_post_import'),
  ('509337', 'Telangana', true, true, 'india_post_import'),
  ('509338', 'Telangana', true, true, 'india_post_import'),
  ('509339', 'Telangana', true, true, 'india_post_import'),
  ('509340', 'Telangana', true, true, 'india_post_import'),
  ('509349', 'Telangana', true, true, 'india_post_import'),
  ('509350', 'Telangana', true, true, 'india_post_import'),
  ('509351', 'Telangana', true, true, 'india_post_import'),
  ('509352', 'Telangana', true, true, 'india_post_import'),
  ('509353', 'Telangana', true, true, 'india_post_import'),
  ('509357', 'Telangana', true, true, 'india_post_import'),
  ('509358', 'Telangana', true, true, 'india_post_import'),
  ('509360', 'Telangana', true, true, 'india_post_import'),
  ('509371', 'Telangana', true, true, 'india_post_import'),
  ('509375', 'Telangana', true, true, 'india_post_import'),
  ('509376', 'Telangana', true, true, 'india_post_import'),
  ('509380', 'Telangana', true, true, 'india_post_import'),
  ('509381', 'Telangana', true, true, 'india_post_import'),
  ('509382', 'Telangana', true, true, 'india_post_import'),
  ('509385', 'Telangana', true, true, 'india_post_import'),
  ('509401', 'Telangana', true, true, 'india_post_import'),
  ('509406', 'Telangana', true, true, 'india_post_import'),
  ('509407', 'Telangana', true, true, 'india_post_import'),
  ('509408', 'Telangana', true, true, 'india_post_import'),
  ('509409', 'Telangana', true, true, 'india_post_import'),
  ('509410', 'Telangana', true, true, 'india_post_import'),
  ('509411', 'Telangana', true, true, 'india_post_import'),
  ('509412', 'Telangana', true, true, 'india_post_import'),
  ('201001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201004', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201005', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201006', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201007', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201008', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201009', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201010', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201011', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201012', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201013', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201014', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201015', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201016', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201017', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201018', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201019', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201020', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201021', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201102', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201103', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201307', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201309', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201310', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201311', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201312', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201313', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201314', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201315', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201316', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201317', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('201318', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202127', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202128', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202129', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202130', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202131', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202132', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202133', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202134', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202135', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202136', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202137', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202138', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202139', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202140', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202141', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202142', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202143', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202145', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202146', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202150', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202155', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202165', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202170', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202280', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202281', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('202282', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203129', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203131', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203132', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203135', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203141', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203150', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203155', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203209', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203389', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203390', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203391', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203392', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203393', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203394', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203395', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203396', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203397', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203398', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203399', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203405', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203407', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203408', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203409', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203411', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('203412', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204101', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204102', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204211', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204212', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204213', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204214', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204215', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('204216', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205119', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205247', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205261', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205262', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205263', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205264', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205265', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205267', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205268', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('205304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206120', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206127', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206128', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206129', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206130', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206131', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206241', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206242', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206243', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206244', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206245', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206246', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206247', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206248', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206249', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206250', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206251', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206252', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206253', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('206255', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207120', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207241', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207242', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207243', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207244', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207245', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207246', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207247', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207248', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207249', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207250', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('207403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208004', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208005', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208006', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208007', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208008', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208009', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208010', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208011', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208012', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208013', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208014', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208015', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208016', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208017', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208019', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208020', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208021', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208022', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208023', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208024', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208025', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208026', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('208027', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209101', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209111', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209112', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209115', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209208', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('209209', 'Uttar Pradesh', true, true, 'india_post_import')
on conflict (pincode) do nothing;