-- =====================================================================
-- Jayvi Foods — Pincode seed, file 7 of 21: pincodes rows 4826-5790
-- Run supabase_seed_pincodes_01_states.sql FIRST. Files 02-21 can then
-- run in any order (each is independent, uses ON CONFLICT DO NOTHING —
-- safe to re-run this specific file if it fails partway).
-- This file: 965 rows.
-- =====================================================================

insert into public.pincodes (pincode, state, serviceable, active, source) values
  ('180017', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180018', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180019', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180020', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181102', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181111', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181121', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181122', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181123', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181124', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181131', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181132', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181133', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181141', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181143', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181145', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181152', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181202', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181203', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181204', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181205', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181206', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181207', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181221', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('181224', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182104', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182121', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182122', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182124', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182125', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182126', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182127', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182128', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182141', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182142', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182143', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182144', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182145', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182146', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182147', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182148', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182161', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182202', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182203', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182204', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182205', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182206', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182207', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182221', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182222', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182301', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182311', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182312', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182313', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182315', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('182320', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184102', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184104', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184120', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184121', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184141', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184142', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184143', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184144', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184145', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184148', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184151', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184152', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184202', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184203', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184204', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184205', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184206', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('184210', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185102', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185121', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185131', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185132', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185133', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185135', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185151', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185152', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185153', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185154', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185155', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185156', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185202', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185203', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185211', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185212', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185233', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('185234', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190001', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190002', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190003', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190004', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190005', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190006', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190007', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190008', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190009', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190010', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190011', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190012', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190014', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190015', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190017', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190018', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190019', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190020', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190021', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190023', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190024', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('190025', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191102', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191103', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191111', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191112', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191113', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191121', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191131', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191132', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('191202', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192121', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192122', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192123', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192124', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192125', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192126', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192129', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192202', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192210', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192211', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192212', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192221', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192231', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192232', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192233', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192301', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192302', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192303', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192304', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192305', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192306', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('192401', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193103', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193108', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193109', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193121', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193122', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193123', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193221', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193222', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193223', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193224', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193225', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193301', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193302', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193303', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193306', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193401', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193402', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193403', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193404', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193411', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193501', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193502', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193503', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193504', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('193505', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194101', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194102', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194103', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194104', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194105', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194106', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194107', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194109', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194201', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194202', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194301', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194302', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194303', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194401', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194402', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('194404', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('813208', 'Jharkhand', true, true, 'india_post_import'),
  ('814101', 'Jharkhand', true, true, 'india_post_import'),
  ('814102', 'Jharkhand', true, true, 'india_post_import'),
  ('814103', 'Jharkhand', true, true, 'india_post_import'),
  ('814110', 'Jharkhand', true, true, 'india_post_import'),
  ('814111', 'Jharkhand', true, true, 'india_post_import'),
  ('814112', 'Jharkhand', true, true, 'india_post_import'),
  ('814113', 'Jharkhand', true, true, 'india_post_import'),
  ('814114', 'Jharkhand', true, true, 'india_post_import'),
  ('814115', 'Jharkhand', true, true, 'india_post_import'),
  ('814116', 'Jharkhand', true, true, 'india_post_import'),
  ('814118', 'Jharkhand', true, true, 'india_post_import'),
  ('814119', 'Jharkhand', true, true, 'india_post_import'),
  ('814120', 'Jharkhand', true, true, 'india_post_import'),
  ('814133', 'Jharkhand', true, true, 'india_post_import'),
  ('814141', 'Jharkhand', true, true, 'india_post_import'),
  ('814142', 'Jharkhand', true, true, 'india_post_import'),
  ('814143', 'Jharkhand', true, true, 'india_post_import'),
  ('814144', 'Jharkhand', true, true, 'india_post_import'),
  ('814145', 'Jharkhand', true, true, 'india_post_import'),
  ('814146', 'Jharkhand', true, true, 'india_post_import'),
  ('814147', 'Jharkhand', true, true, 'india_post_import'),
  ('814148', 'Jharkhand', true, true, 'india_post_import'),
  ('814149', 'Jharkhand', true, true, 'india_post_import'),
  ('814150', 'Jharkhand', true, true, 'india_post_import'),
  ('814151', 'Jharkhand', true, true, 'india_post_import'),
  ('814152', 'Jharkhand', true, true, 'india_post_import'),
  ('814153', 'Jharkhand', true, true, 'india_post_import'),
  ('814154', 'Jharkhand', true, true, 'india_post_import'),
  ('814155', 'Jharkhand', true, true, 'india_post_import'),
  ('814156', 'Jharkhand', true, true, 'india_post_import'),
  ('814157', 'Jharkhand', true, true, 'india_post_import'),
  ('814158', 'Jharkhand', true, true, 'india_post_import'),
  ('814160', 'Jharkhand', true, true, 'india_post_import'),
  ('814165', 'Jharkhand', true, true, 'india_post_import'),
  ('814166', 'Jharkhand', true, true, 'india_post_import'),
  ('814167', 'Jharkhand', true, true, 'india_post_import'),
  ('815301', 'Jharkhand', true, true, 'india_post_import'),
  ('815302', 'Jharkhand', true, true, 'india_post_import'),
  ('815311', 'Jharkhand', true, true, 'india_post_import'),
  ('815312', 'Jharkhand', true, true, 'india_post_import'),
  ('815313', 'Jharkhand', true, true, 'india_post_import'),
  ('815314', 'Jharkhand', true, true, 'india_post_import'),
  ('815315', 'Jharkhand', true, true, 'india_post_import'),
  ('815316', 'Jharkhand', true, true, 'india_post_import'),
  ('815317', 'Jharkhand', true, true, 'india_post_import'),
  ('815318', 'Jharkhand', true, true, 'india_post_import'),
  ('815351', 'Jharkhand', true, true, 'india_post_import'),
  ('815352', 'Jharkhand', true, true, 'india_post_import'),
  ('815353', 'Jharkhand', true, true, 'india_post_import'),
  ('815354', 'Jharkhand', true, true, 'india_post_import'),
  ('815355', 'Jharkhand', true, true, 'india_post_import'),
  ('815357', 'Jharkhand', true, true, 'india_post_import'),
  ('815359', 'Jharkhand', true, true, 'india_post_import'),
  ('816101', 'Jharkhand', true, true, 'india_post_import'),
  ('816102', 'Jharkhand', true, true, 'india_post_import'),
  ('816103', 'Jharkhand', true, true, 'india_post_import'),
  ('816104', 'Jharkhand', true, true, 'india_post_import'),
  ('816105', 'Jharkhand', true, true, 'india_post_import'),
  ('816106', 'Jharkhand', true, true, 'india_post_import'),
  ('816107', 'Jharkhand', true, true, 'india_post_import'),
  ('816108', 'Jharkhand', true, true, 'india_post_import'),
  ('816109', 'Jharkhand', true, true, 'india_post_import'),
  ('816110', 'Jharkhand', true, true, 'india_post_import'),
  ('816115', 'Jharkhand', true, true, 'india_post_import'),
  ('816116', 'Jharkhand', true, true, 'india_post_import'),
  ('816117', 'Jharkhand', true, true, 'india_post_import'),
  ('816118', 'Jharkhand', true, true, 'india_post_import'),
  ('816120', 'Jharkhand', true, true, 'india_post_import'),
  ('816129', 'Jharkhand', true, true, 'india_post_import'),
  ('818142', 'Jharkhand', true, true, 'india_post_import'),
  ('822101', 'Jharkhand', true, true, 'india_post_import'),
  ('822102', 'Jharkhand', true, true, 'india_post_import'),
  ('822110', 'Jharkhand', true, true, 'india_post_import'),
  ('822111', 'Jharkhand', true, true, 'india_post_import'),
  ('822112', 'Jharkhand', true, true, 'india_post_import'),
  ('822113', 'Jharkhand', true, true, 'india_post_import'),
  ('822114', 'Jharkhand', true, true, 'india_post_import'),
  ('822115', 'Jharkhand', true, true, 'india_post_import'),
  ('822116', 'Jharkhand', true, true, 'india_post_import'),
  ('822117', 'Jharkhand', true, true, 'india_post_import'),
  ('822118', 'Jharkhand', true, true, 'india_post_import'),
  ('822119', 'Jharkhand', true, true, 'india_post_import'),
  ('822120', 'Jharkhand', true, true, 'india_post_import'),
  ('822121', 'Jharkhand', true, true, 'india_post_import'),
  ('822122', 'Jharkhand', true, true, 'india_post_import'),
  ('822123', 'Jharkhand', true, true, 'india_post_import'),
  ('822124', 'Jharkhand', true, true, 'india_post_import'),
  ('822125', 'Jharkhand', true, true, 'india_post_import'),
  ('822126', 'Jharkhand', true, true, 'india_post_import'),
  ('822128', 'Jharkhand', true, true, 'india_post_import'),
  ('822129', 'Jharkhand', true, true, 'india_post_import'),
  ('822131', 'Jharkhand', true, true, 'india_post_import'),
  ('822132', 'Jharkhand', true, true, 'india_post_import'),
  ('822133', 'Jharkhand', true, true, 'india_post_import'),
  ('822134', 'Jharkhand', true, true, 'india_post_import'),
  ('825101', 'Jharkhand', true, true, 'india_post_import'),
  ('825102', 'Jharkhand', true, true, 'india_post_import'),
  ('825103', 'Jharkhand', true, true, 'india_post_import'),
  ('825106', 'Jharkhand', true, true, 'india_post_import'),
  ('825108', 'Jharkhand', true, true, 'india_post_import'),
  ('825109', 'Jharkhand', true, true, 'india_post_import'),
  ('825132', 'Jharkhand', true, true, 'india_post_import'),
  ('825167', 'Jharkhand', true, true, 'india_post_import'),
  ('825301', 'Jharkhand', true, true, 'india_post_import'),
  ('825302', 'Jharkhand', true, true, 'india_post_import'),
  ('825303', 'Jharkhand', true, true, 'india_post_import'),
  ('825311', 'Jharkhand', true, true, 'india_post_import'),
  ('825312', 'Jharkhand', true, true, 'india_post_import'),
  ('825313', 'Jharkhand', true, true, 'india_post_import'),
  ('825314', 'Jharkhand', true, true, 'india_post_import'),
  ('825315', 'Jharkhand', true, true, 'india_post_import'),
  ('825316', 'Jharkhand', true, true, 'india_post_import'),
  ('825317', 'Jharkhand', true, true, 'india_post_import'),
  ('825318', 'Jharkhand', true, true, 'india_post_import'),
  ('825319', 'Jharkhand', true, true, 'india_post_import'),
  ('825320', 'Jharkhand', true, true, 'india_post_import'),
  ('825321', 'Jharkhand', true, true, 'india_post_import'),
  ('825322', 'Jharkhand', true, true, 'india_post_import'),
  ('825323', 'Jharkhand', true, true, 'india_post_import'),
  ('825324', 'Jharkhand', true, true, 'india_post_import'),
  ('825325', 'Jharkhand', true, true, 'india_post_import'),
  ('825326', 'Jharkhand', true, true, 'india_post_import'),
  ('825329', 'Jharkhand', true, true, 'india_post_import'),
  ('825330', 'Jharkhand', true, true, 'india_post_import'),
  ('825336', 'Jharkhand', true, true, 'india_post_import'),
  ('825401', 'Jharkhand', true, true, 'india_post_import'),
  ('825402', 'Jharkhand', true, true, 'india_post_import'),
  ('825403', 'Jharkhand', true, true, 'india_post_import'),
  ('825404', 'Jharkhand', true, true, 'india_post_import'),
  ('825405', 'Jharkhand', true, true, 'india_post_import'),
  ('825406', 'Jharkhand', true, true, 'india_post_import'),
  ('825407', 'Jharkhand', true, true, 'india_post_import'),
  ('825408', 'Jharkhand', true, true, 'india_post_import'),
  ('825409', 'Jharkhand', true, true, 'india_post_import'),
  ('825410', 'Jharkhand', true, true, 'india_post_import'),
  ('825411', 'Jharkhand', true, true, 'india_post_import'),
  ('825412', 'Jharkhand', true, true, 'india_post_import'),
  ('825413', 'Jharkhand', true, true, 'india_post_import'),
  ('825414', 'Jharkhand', true, true, 'india_post_import'),
  ('825415', 'Jharkhand', true, true, 'india_post_import'),
  ('825418', 'Jharkhand', true, true, 'india_post_import'),
  ('825421', 'Jharkhand', true, true, 'india_post_import'),
  ('826001', 'Jharkhand', true, true, 'india_post_import'),
  ('826003', 'Jharkhand', true, true, 'india_post_import'),
  ('826004', 'Jharkhand', true, true, 'india_post_import'),
  ('826005', 'Jharkhand', true, true, 'india_post_import'),
  ('826006', 'Jharkhand', true, true, 'india_post_import'),
  ('826007', 'Jharkhand', true, true, 'india_post_import'),
  ('826008', 'Jharkhand', true, true, 'india_post_import'),
  ('826009', 'Jharkhand', true, true, 'india_post_import'),
  ('826010', 'Jharkhand', true, true, 'india_post_import'),
  ('826011', 'Jharkhand', true, true, 'india_post_import'),
  ('827001', 'Jharkhand', true, true, 'india_post_import'),
  ('827003', 'Jharkhand', true, true, 'india_post_import'),
  ('827004', 'Jharkhand', true, true, 'india_post_import'),
  ('827006', 'Jharkhand', true, true, 'india_post_import'),
  ('827009', 'Jharkhand', true, true, 'india_post_import'),
  ('827010', 'Jharkhand', true, true, 'india_post_import'),
  ('827012', 'Jharkhand', true, true, 'india_post_import'),
  ('827013', 'Jharkhand', true, true, 'india_post_import'),
  ('827014', 'Jharkhand', true, true, 'india_post_import'),
  ('827015', 'Jharkhand', true, true, 'india_post_import'),
  ('827302', 'Jharkhand', true, true, 'india_post_import'),
  ('828101', 'Jharkhand', true, true, 'india_post_import'),
  ('828103', 'Jharkhand', true, true, 'india_post_import'),
  ('828104', 'Jharkhand', true, true, 'india_post_import'),
  ('828105', 'Jharkhand', true, true, 'india_post_import'),
  ('828106', 'Jharkhand', true, true, 'india_post_import'),
  ('828107', 'Jharkhand', true, true, 'india_post_import'),
  ('828108', 'Jharkhand', true, true, 'india_post_import'),
  ('828109', 'Jharkhand', true, true, 'india_post_import'),
  ('828110', 'Jharkhand', true, true, 'india_post_import'),
  ('828111', 'Jharkhand', true, true, 'india_post_import'),
  ('828112', 'Jharkhand', true, true, 'india_post_import'),
  ('828113', 'Jharkhand', true, true, 'india_post_import'),
  ('828114', 'Jharkhand', true, true, 'india_post_import'),
  ('828115', 'Jharkhand', true, true, 'india_post_import'),
  ('828116', 'Jharkhand', true, true, 'india_post_import'),
  ('828117', 'Jharkhand', true, true, 'india_post_import'),
  ('828119', 'Jharkhand', true, true, 'india_post_import'),
  ('828120', 'Jharkhand', true, true, 'india_post_import'),
  ('828121', 'Jharkhand', true, true, 'india_post_import'),
  ('828122', 'Jharkhand', true, true, 'india_post_import'),
  ('828123', 'Jharkhand', true, true, 'india_post_import'),
  ('828124', 'Jharkhand', true, true, 'india_post_import'),
  ('828125', 'Jharkhand', true, true, 'india_post_import'),
  ('828126', 'Jharkhand', true, true, 'india_post_import'),
  ('828127', 'Jharkhand', true, true, 'india_post_import'),
  ('828128', 'Jharkhand', true, true, 'india_post_import'),
  ('828129', 'Jharkhand', true, true, 'india_post_import'),
  ('828130', 'Jharkhand', true, true, 'india_post_import'),
  ('828131', 'Jharkhand', true, true, 'india_post_import'),
  ('828132', 'Jharkhand', true, true, 'india_post_import'),
  ('828133', 'Jharkhand', true, true, 'india_post_import'),
  ('828134', 'Jharkhand', true, true, 'india_post_import'),
  ('828135', 'Jharkhand', true, true, 'india_post_import'),
  ('828142', 'Jharkhand', true, true, 'india_post_import'),
  ('828201', 'Jharkhand', true, true, 'india_post_import'),
  ('828202', 'Jharkhand', true, true, 'india_post_import'),
  ('828203', 'Jharkhand', true, true, 'india_post_import'),
  ('828204', 'Jharkhand', true, true, 'india_post_import'),
  ('828205', 'Jharkhand', true, true, 'india_post_import'),
  ('828206', 'Jharkhand', true, true, 'india_post_import'),
  ('828207', 'Jharkhand', true, true, 'india_post_import'),
  ('828301', 'Jharkhand', true, true, 'india_post_import'),
  ('828302', 'Jharkhand', true, true, 'india_post_import'),
  ('828303', 'Jharkhand', true, true, 'india_post_import'),
  ('828304', 'Jharkhand', true, true, 'india_post_import'),
  ('828305', 'Jharkhand', true, true, 'india_post_import'),
  ('828306', 'Jharkhand', true, true, 'india_post_import'),
  ('828307', 'Jharkhand', true, true, 'india_post_import'),
  ('828309', 'Jharkhand', true, true, 'india_post_import'),
  ('828401', 'Jharkhand', true, true, 'india_post_import'),
  ('828402', 'Jharkhand', true, true, 'india_post_import'),
  ('828403', 'Jharkhand', true, true, 'india_post_import'),
  ('828404', 'Jharkhand', true, true, 'india_post_import'),
  ('829101', 'Jharkhand', true, true, 'india_post_import'),
  ('829102', 'Jharkhand', true, true, 'india_post_import'),
  ('829103', 'Jharkhand', true, true, 'india_post_import'),
  ('829104', 'Jharkhand', true, true, 'india_post_import'),
  ('829105', 'Jharkhand', true, true, 'india_post_import'),
  ('829106', 'Jharkhand', true, true, 'india_post_import'),
  ('829107', 'Jharkhand', true, true, 'india_post_import'),
  ('829108', 'Jharkhand', true, true, 'india_post_import'),
  ('829109', 'Jharkhand', true, true, 'india_post_import'),
  ('829110', 'Jharkhand', true, true, 'india_post_import'),
  ('829111', 'Jharkhand', true, true, 'india_post_import'),
  ('829112', 'Jharkhand', true, true, 'india_post_import'),
  ('829113', 'Jharkhand', true, true, 'india_post_import'),
  ('829114', 'Jharkhand', true, true, 'india_post_import'),
  ('829115', 'Jharkhand', true, true, 'india_post_import'),
  ('829116', 'Jharkhand', true, true, 'india_post_import'),
  ('829117', 'Jharkhand', true, true, 'india_post_import'),
  ('829118', 'Jharkhand', true, true, 'india_post_import'),
  ('829119', 'Jharkhand', true, true, 'india_post_import'),
  ('829121', 'Jharkhand', true, true, 'india_post_import'),
  ('829122', 'Jharkhand', true, true, 'india_post_import'),
  ('829123', 'Jharkhand', true, true, 'india_post_import'),
  ('829125', 'Jharkhand', true, true, 'india_post_import'),
  ('829126', 'Jharkhand', true, true, 'india_post_import'),
  ('829127', 'Jharkhand', true, true, 'india_post_import'),
  ('829128', 'Jharkhand', true, true, 'india_post_import'),
  ('829129', 'Jharkhand', true, true, 'india_post_import'),
  ('829130', 'Jharkhand', true, true, 'india_post_import'),
  ('829131', 'Jharkhand', true, true, 'india_post_import'),
  ('829132', 'Jharkhand', true, true, 'india_post_import'),
  ('829133', 'Jharkhand', true, true, 'india_post_import'),
  ('829134', 'Jharkhand', true, true, 'india_post_import'),
  ('829135', 'Jharkhand', true, true, 'india_post_import'),
  ('829143', 'Jharkhand', true, true, 'india_post_import'),
  ('829144', 'Jharkhand', true, true, 'india_post_import'),
  ('829149', 'Jharkhand', true, true, 'india_post_import'),
  ('829150', 'Jharkhand', true, true, 'india_post_import'),
  ('829201', 'Jharkhand', true, true, 'india_post_import'),
  ('829202', 'Jharkhand', true, true, 'india_post_import'),
  ('829203', 'Jharkhand', true, true, 'india_post_import'),
  ('829204', 'Jharkhand', true, true, 'india_post_import'),
  ('829205', 'Jharkhand', true, true, 'india_post_import'),
  ('829206', 'Jharkhand', true, true, 'india_post_import'),
  ('829207', 'Jharkhand', true, true, 'india_post_import'),
  ('829208', 'Jharkhand', true, true, 'india_post_import'),
  ('829209', 'Jharkhand', true, true, 'india_post_import'),
  ('829210', 'Jharkhand', true, true, 'india_post_import'),
  ('829301', 'Jharkhand', true, true, 'india_post_import'),
  ('831001', 'Jharkhand', true, true, 'india_post_import'),
  ('831002', 'Jharkhand', true, true, 'india_post_import'),
  ('831003', 'Jharkhand', true, true, 'india_post_import'),
  ('831004', 'Jharkhand', true, true, 'india_post_import'),
  ('831005', 'Jharkhand', true, true, 'india_post_import'),
  ('831006', 'Jharkhand', true, true, 'india_post_import'),
  ('831007', 'Jharkhand', true, true, 'india_post_import'),
  ('831009', 'Jharkhand', true, true, 'india_post_import'),
  ('831011', 'Jharkhand', true, true, 'india_post_import'),
  ('831012', 'Jharkhand', true, true, 'india_post_import'),
  ('831013', 'Jharkhand', true, true, 'india_post_import'),
  ('831014', 'Jharkhand', true, true, 'india_post_import'),
  ('831015', 'Jharkhand', true, true, 'india_post_import'),
  ('831016', 'Jharkhand', true, true, 'india_post_import'),
  ('831017', 'Jharkhand', true, true, 'india_post_import'),
  ('831019', 'Jharkhand', true, true, 'india_post_import'),
  ('831020', 'Jharkhand', true, true, 'india_post_import'),
  ('831021', 'Jharkhand', true, true, 'india_post_import'),
  ('832101', 'Jharkhand', true, true, 'india_post_import'),
  ('832102', 'Jharkhand', true, true, 'india_post_import'),
  ('832103', 'Jharkhand', true, true, 'india_post_import'),
  ('832104', 'Jharkhand', true, true, 'india_post_import'),
  ('832105', 'Jharkhand', true, true, 'india_post_import'),
  ('832106', 'Jharkhand', true, true, 'india_post_import'),
  ('832107', 'Jharkhand', true, true, 'india_post_import'),
  ('832108', 'Jharkhand', true, true, 'india_post_import'),
  ('832109', 'Jharkhand', true, true, 'india_post_import'),
  ('832111', 'Jharkhand', true, true, 'india_post_import'),
  ('832112', 'Jharkhand', true, true, 'india_post_import'),
  ('832113', 'Jharkhand', true, true, 'india_post_import'),
  ('832301', 'Jharkhand', true, true, 'india_post_import'),
  ('832302', 'Jharkhand', true, true, 'india_post_import'),
  ('832303', 'Jharkhand', true, true, 'india_post_import'),
  ('832304', 'Jharkhand', true, true, 'india_post_import'),
  ('832401', 'Jharkhand', true, true, 'india_post_import'),
  ('832402', 'Jharkhand', true, true, 'india_post_import'),
  ('832403', 'Jharkhand', true, true, 'india_post_import'),
  ('832404', 'Jharkhand', true, true, 'india_post_import'),
  ('833101', 'Jharkhand', true, true, 'india_post_import'),
  ('833102', 'Jharkhand', true, true, 'india_post_import'),
  ('833103', 'Jharkhand', true, true, 'india_post_import'),
  ('833104', 'Jharkhand', true, true, 'india_post_import'),
  ('833105', 'Jharkhand', true, true, 'india_post_import'),
  ('833106', 'Jharkhand', true, true, 'india_post_import'),
  ('833201', 'Jharkhand', true, true, 'india_post_import'),
  ('833202', 'Jharkhand', true, true, 'india_post_import'),
  ('833203', 'Jharkhand', true, true, 'india_post_import'),
  ('833204', 'Jharkhand', true, true, 'india_post_import'),
  ('833212', 'Jharkhand', true, true, 'india_post_import'),
  ('833213', 'Jharkhand', true, true, 'india_post_import'),
  ('833214', 'Jharkhand', true, true, 'india_post_import'),
  ('833215', 'Jharkhand', true, true, 'india_post_import'),
  ('833216', 'Jharkhand', true, true, 'india_post_import'),
  ('833217', 'Jharkhand', true, true, 'india_post_import'),
  ('833218', 'Jharkhand', true, true, 'india_post_import'),
  ('833219', 'Jharkhand', true, true, 'india_post_import'),
  ('833220', 'Jharkhand', true, true, 'india_post_import'),
  ('833221', 'Jharkhand', true, true, 'india_post_import'),
  ('833222', 'Jharkhand', true, true, 'india_post_import'),
  ('833223', 'Jharkhand', true, true, 'india_post_import'),
  ('834001', 'Jharkhand', true, true, 'india_post_import'),
  ('834002', 'Jharkhand', true, true, 'india_post_import'),
  ('834003', 'Jharkhand', true, true, 'india_post_import'),
  ('834004', 'Jharkhand', true, true, 'india_post_import'),
  ('834005', 'Jharkhand', true, true, 'india_post_import'),
  ('834006', 'Jharkhand', true, true, 'india_post_import'),
  ('834007', 'Jharkhand', true, true, 'india_post_import'),
  ('834008', 'Jharkhand', true, true, 'india_post_import'),
  ('834009', 'Jharkhand', true, true, 'india_post_import'),
  ('834010', 'Jharkhand', true, true, 'india_post_import'),
  ('834011', 'Jharkhand', true, true, 'india_post_import'),
  ('834012', 'Jharkhand', true, true, 'india_post_import'),
  ('834013', 'Jharkhand', true, true, 'india_post_import'),
  ('834014', 'Jharkhand', true, true, 'india_post_import'),
  ('835101', 'Jharkhand', true, true, 'india_post_import'),
  ('835102', 'Jharkhand', true, true, 'india_post_import'),
  ('835103', 'Jharkhand', true, true, 'india_post_import'),
  ('835201', 'Jharkhand', true, true, 'india_post_import'),
  ('835202', 'Jharkhand', true, true, 'india_post_import'),
  ('835203', 'Jharkhand', true, true, 'india_post_import'),
  ('835204', 'Jharkhand', true, true, 'india_post_import'),
  ('835205', 'Jharkhand', true, true, 'india_post_import'),
  ('835206', 'Jharkhand', true, true, 'india_post_import'),
  ('835207', 'Jharkhand', true, true, 'india_post_import'),
  ('835208', 'Jharkhand', true, true, 'india_post_import'),
  ('835209', 'Jharkhand', true, true, 'india_post_import'),
  ('835210', 'Jharkhand', true, true, 'india_post_import'),
  ('835211', 'Jharkhand', true, true, 'india_post_import'),
  ('835212', 'Jharkhand', true, true, 'india_post_import'),
  ('835213', 'Jharkhand', true, true, 'india_post_import'),
  ('835214', 'Jharkhand', true, true, 'india_post_import'),
  ('835215', 'Jharkhand', true, true, 'india_post_import'),
  ('835216', 'Jharkhand', true, true, 'india_post_import'),
  ('835217', 'Jharkhand', true, true, 'india_post_import'),
  ('835218', 'Jharkhand', true, true, 'india_post_import'),
  ('835219', 'Jharkhand', true, true, 'india_post_import'),
  ('835220', 'Jharkhand', true, true, 'india_post_import'),
  ('835221', 'Jharkhand', true, true, 'india_post_import'),
  ('835222', 'Jharkhand', true, true, 'india_post_import'),
  ('835223', 'Jharkhand', true, true, 'india_post_import'),
  ('835224', 'Jharkhand', true, true, 'india_post_import'),
  ('835225', 'Jharkhand', true, true, 'india_post_import'),
  ('835226', 'Jharkhand', true, true, 'india_post_import'),
  ('835227', 'Jharkhand', true, true, 'india_post_import'),
  ('835228', 'Jharkhand', true, true, 'india_post_import'),
  ('835229', 'Jharkhand', true, true, 'india_post_import'),
  ('835230', 'Jharkhand', true, true, 'india_post_import'),
  ('835231', 'Jharkhand', true, true, 'india_post_import'),
  ('835232', 'Jharkhand', true, true, 'india_post_import'),
  ('835233', 'Jharkhand', true, true, 'india_post_import'),
  ('835234', 'Jharkhand', true, true, 'india_post_import'),
  ('835235', 'Jharkhand', true, true, 'india_post_import'),
  ('835301', 'Jharkhand', true, true, 'india_post_import'),
  ('835302', 'Jharkhand', true, true, 'india_post_import'),
  ('835303', 'Jharkhand', true, true, 'india_post_import'),
  ('835325', 'Jharkhand', true, true, 'india_post_import'),
  ('560001', 'Karnataka', true, true, 'india_post_import'),
  ('560002', 'Karnataka', true, true, 'india_post_import'),
  ('560003', 'Karnataka', true, true, 'india_post_import'),
  ('560004', 'Karnataka', true, true, 'india_post_import'),
  ('560005', 'Karnataka', true, true, 'india_post_import'),
  ('560006', 'Karnataka', true, true, 'india_post_import'),
  ('560007', 'Karnataka', true, true, 'india_post_import'),
  ('560008', 'Karnataka', true, true, 'india_post_import'),
  ('560009', 'Karnataka', true, true, 'india_post_import'),
  ('560010', 'Karnataka', true, true, 'india_post_import'),
  ('560011', 'Karnataka', true, true, 'india_post_import'),
  ('560012', 'Karnataka', true, true, 'india_post_import'),
  ('560013', 'Karnataka', true, true, 'india_post_import'),
  ('560015', 'Karnataka', true, true, 'india_post_import'),
  ('560016', 'Karnataka', true, true, 'india_post_import'),
  ('560017', 'Karnataka', true, true, 'india_post_import'),
  ('560018', 'Karnataka', true, true, 'india_post_import'),
  ('560020', 'Karnataka', true, true, 'india_post_import'),
  ('560021', 'Karnataka', true, true, 'india_post_import'),
  ('560022', 'Karnataka', true, true, 'india_post_import'),
  ('560023', 'Karnataka', true, true, 'india_post_import'),
  ('560024', 'Karnataka', true, true, 'india_post_import'),
  ('560025', 'Karnataka', true, true, 'india_post_import'),
  ('560026', 'Karnataka', true, true, 'india_post_import'),
  ('560027', 'Karnataka', true, true, 'india_post_import'),
  ('560029', 'Karnataka', true, true, 'india_post_import'),
  ('560030', 'Karnataka', true, true, 'india_post_import'),
  ('560032', 'Karnataka', true, true, 'india_post_import'),
  ('560033', 'Karnataka', true, true, 'india_post_import'),
  ('560034', 'Karnataka', true, true, 'india_post_import'),
  ('560035', 'Karnataka', true, true, 'india_post_import'),
  ('560036', 'Karnataka', true, true, 'india_post_import'),
  ('560037', 'Karnataka', true, true, 'india_post_import'),
  ('560038', 'Karnataka', true, true, 'india_post_import'),
  ('560040', 'Karnataka', true, true, 'india_post_import'),
  ('560041', 'Karnataka', true, true, 'india_post_import'),
  ('560042', 'Karnataka', true, true, 'india_post_import'),
  ('560043', 'Karnataka', true, true, 'india_post_import'),
  ('560045', 'Karnataka', true, true, 'india_post_import'),
  ('560046', 'Karnataka', true, true, 'india_post_import'),
  ('560047', 'Karnataka', true, true, 'india_post_import'),
  ('560048', 'Karnataka', true, true, 'india_post_import'),
  ('560049', 'Karnataka', true, true, 'india_post_import'),
  ('560050', 'Karnataka', true, true, 'india_post_import'),
  ('560051', 'Karnataka', true, true, 'india_post_import'),
  ('560053', 'Karnataka', true, true, 'india_post_import'),
  ('560054', 'Karnataka', true, true, 'india_post_import'),
  ('560055', 'Karnataka', true, true, 'india_post_import'),
  ('560056', 'Karnataka', true, true, 'india_post_import'),
  ('560057', 'Karnataka', true, true, 'india_post_import'),
  ('560058', 'Karnataka', true, true, 'india_post_import'),
  ('560059', 'Karnataka', true, true, 'india_post_import'),
  ('560060', 'Karnataka', true, true, 'india_post_import'),
  ('560061', 'Karnataka', true, true, 'india_post_import'),
  ('560062', 'Karnataka', true, true, 'india_post_import'),
  ('560063', 'Karnataka', true, true, 'india_post_import'),
  ('560064', 'Karnataka', true, true, 'india_post_import'),
  ('560065', 'Karnataka', true, true, 'india_post_import'),
  ('560066', 'Karnataka', true, true, 'india_post_import'),
  ('560067', 'Karnataka', true, true, 'india_post_import'),
  ('560068', 'Karnataka', true, true, 'india_post_import'),
  ('560070', 'Karnataka', true, true, 'india_post_import'),
  ('560071', 'Karnataka', true, true, 'india_post_import'),
  ('560072', 'Karnataka', true, true, 'india_post_import'),
  ('560073', 'Karnataka', true, true, 'india_post_import'),
  ('560074', 'Karnataka', true, true, 'india_post_import'),
  ('560075', 'Karnataka', true, true, 'india_post_import'),
  ('560076', 'Karnataka', true, true, 'india_post_import'),
  ('560077', 'Karnataka', true, true, 'india_post_import'),
  ('560078', 'Karnataka', true, true, 'india_post_import'),
  ('560079', 'Karnataka', true, true, 'india_post_import'),
  ('560080', 'Karnataka', true, true, 'india_post_import'),
  ('560081', 'Karnataka', true, true, 'india_post_import'),
  ('560082', 'Karnataka', true, true, 'india_post_import'),
  ('560083', 'Karnataka', true, true, 'india_post_import'),
  ('560084', 'Karnataka', true, true, 'india_post_import'),
  ('560085', 'Karnataka', true, true, 'india_post_import'),
  ('560086', 'Karnataka', true, true, 'india_post_import'),
  ('560087', 'Karnataka', true, true, 'india_post_import'),
  ('560088', 'Karnataka', true, true, 'india_post_import'),
  ('560089', 'Karnataka', true, true, 'india_post_import'),
  ('560090', 'Karnataka', true, true, 'india_post_import'),
  ('560091', 'Karnataka', true, true, 'india_post_import'),
  ('560092', 'Karnataka', true, true, 'india_post_import'),
  ('560093', 'Karnataka', true, true, 'india_post_import'),
  ('560094', 'Karnataka', true, true, 'india_post_import'),
  ('560095', 'Karnataka', true, true, 'india_post_import'),
  ('560096', 'Karnataka', true, true, 'india_post_import'),
  ('560097', 'Karnataka', true, true, 'india_post_import'),
  ('560098', 'Karnataka', true, true, 'india_post_import'),
  ('560099', 'Karnataka', true, true, 'india_post_import'),
  ('560100', 'Karnataka', true, true, 'india_post_import'),
  ('560102', 'Karnataka', true, true, 'india_post_import'),
  ('560103', 'Karnataka', true, true, 'india_post_import'),
  ('560104', 'Karnataka', true, true, 'india_post_import'),
  ('560105', 'Karnataka', true, true, 'india_post_import'),
  ('560107', 'Karnataka', true, true, 'india_post_import'),
  ('560108', 'Karnataka', true, true, 'india_post_import'),
  ('560109', 'Karnataka', true, true, 'india_post_import'),
  ('560110', 'Karnataka', true, true, 'india_post_import'),
  ('560111', 'Karnataka', true, true, 'india_post_import'),
  ('560112', 'Karnataka', true, true, 'india_post_import'),
  ('560113', 'Karnataka', true, true, 'india_post_import'),
  ('560114', 'Karnataka', true, true, 'india_post_import'),
  ('560115', 'Karnataka', true, true, 'india_post_import'),
  ('560116', 'Karnataka', true, true, 'india_post_import'),
  ('560117', 'Karnataka', true, true, 'india_post_import'),
  ('560300', 'Karnataka', true, true, 'india_post_import'),
  ('560500', 'Karnataka', true, true, 'india_post_import'),
  ('561101', 'Karnataka', true, true, 'india_post_import'),
  ('561201', 'Karnataka', true, true, 'india_post_import'),
  ('561202', 'Karnataka', true, true, 'india_post_import'),
  ('561203', 'Karnataka', true, true, 'india_post_import'),
  ('561204', 'Karnataka', true, true, 'india_post_import'),
  ('561205', 'Karnataka', true, true, 'india_post_import'),
  ('561206', 'Karnataka', true, true, 'india_post_import'),
  ('561207', 'Karnataka', true, true, 'india_post_import'),
  ('561208', 'Karnataka', true, true, 'india_post_import'),
  ('561209', 'Karnataka', true, true, 'india_post_import'),
  ('561210', 'Karnataka', true, true, 'india_post_import'),
  ('561211', 'Karnataka', true, true, 'india_post_import'),
  ('561212', 'Karnataka', true, true, 'india_post_import'),
  ('561213', 'Karnataka', true, true, 'india_post_import'),
  ('561228', 'Karnataka', true, true, 'india_post_import'),
  ('562101', 'Karnataka', true, true, 'india_post_import'),
  ('562102', 'Karnataka', true, true, 'india_post_import'),
  ('562103', 'Karnataka', true, true, 'india_post_import'),
  ('562104', 'Karnataka', true, true, 'india_post_import'),
  ('562105', 'Karnataka', true, true, 'india_post_import'),
  ('562106', 'Karnataka', true, true, 'india_post_import'),
  ('562107', 'Karnataka', true, true, 'india_post_import'),
  ('562108', 'Karnataka', true, true, 'india_post_import'),
  ('562109', 'Karnataka', true, true, 'india_post_import'),
  ('562110', 'Karnataka', true, true, 'india_post_import'),
  ('562111', 'Karnataka', true, true, 'india_post_import'),
  ('562112', 'Karnataka', true, true, 'india_post_import'),
  ('562114', 'Karnataka', true, true, 'india_post_import'),
  ('562117', 'Karnataka', true, true, 'india_post_import'),
  ('562119', 'Karnataka', true, true, 'india_post_import'),
  ('562120', 'Karnataka', true, true, 'india_post_import'),
  ('562121', 'Karnataka', true, true, 'india_post_import'),
  ('562122', 'Karnataka', true, true, 'india_post_import'),
  ('562123', 'Karnataka', true, true, 'india_post_import'),
  ('562125', 'Karnataka', true, true, 'india_post_import'),
  ('562126', 'Karnataka', true, true, 'india_post_import'),
  ('562127', 'Karnataka', true, true, 'india_post_import'),
  ('562128', 'Karnataka', true, true, 'india_post_import'),
  ('562129', 'Karnataka', true, true, 'india_post_import'),
  ('562130', 'Karnataka', true, true, 'india_post_import'),
  ('562131', 'Karnataka', true, true, 'india_post_import'),
  ('562132', 'Karnataka', true, true, 'india_post_import'),
  ('562135', 'Karnataka', true, true, 'india_post_import'),
  ('562138', 'Karnataka', true, true, 'india_post_import'),
  ('562149', 'Karnataka', true, true, 'india_post_import'),
  ('562157', 'Karnataka', true, true, 'india_post_import'),
  ('562159', 'Karnataka', true, true, 'india_post_import'),
  ('562160', 'Karnataka', true, true, 'india_post_import'),
  ('562161', 'Karnataka', true, true, 'india_post_import'),
  ('562162', 'Karnataka', true, true, 'india_post_import'),
  ('562163', 'Karnataka', true, true, 'india_post_import'),
  ('562164', 'Karnataka', true, true, 'india_post_import'),
  ('562165', 'Karnataka', true, true, 'india_post_import'),
  ('563101', 'Karnataka', true, true, 'india_post_import'),
  ('563103', 'Karnataka', true, true, 'india_post_import'),
  ('563113', 'Karnataka', true, true, 'india_post_import'),
  ('563114', 'Karnataka', true, true, 'india_post_import'),
  ('563115', 'Karnataka', true, true, 'india_post_import'),
  ('563116', 'Karnataka', true, true, 'india_post_import'),
  ('563117', 'Karnataka', true, true, 'india_post_import'),
  ('563118', 'Karnataka', true, true, 'india_post_import'),
  ('563119', 'Karnataka', true, true, 'india_post_import'),
  ('563120', 'Karnataka', true, true, 'india_post_import'),
  ('563121', 'Karnataka', true, true, 'india_post_import'),
  ('563122', 'Karnataka', true, true, 'india_post_import'),
  ('563123', 'Karnataka', true, true, 'india_post_import'),
  ('563124', 'Karnataka', true, true, 'india_post_import'),
  ('563125', 'Karnataka', true, true, 'india_post_import'),
  ('563126', 'Karnataka', true, true, 'india_post_import'),
  ('563127', 'Karnataka', true, true, 'india_post_import'),
  ('563128', 'Karnataka', true, true, 'india_post_import'),
  ('563129', 'Karnataka', true, true, 'india_post_import'),
  ('563130', 'Karnataka', true, true, 'india_post_import'),
  ('563131', 'Karnataka', true, true, 'india_post_import'),
  ('563132', 'Karnataka', true, true, 'india_post_import'),
  ('563133', 'Karnataka', true, true, 'india_post_import'),
  ('563134', 'Karnataka', true, true, 'india_post_import'),
  ('563135', 'Karnataka', true, true, 'india_post_import'),
  ('563136', 'Karnataka', true, true, 'india_post_import'),
  ('563137', 'Karnataka', true, true, 'india_post_import'),
  ('563138', 'Karnataka', true, true, 'india_post_import'),
  ('563139', 'Karnataka', true, true, 'india_post_import'),
  ('563146', 'Karnataka', true, true, 'india_post_import'),
  ('563147', 'Karnataka', true, true, 'india_post_import'),
  ('563157', 'Karnataka', true, true, 'india_post_import'),
  ('563159', 'Karnataka', true, true, 'india_post_import'),
  ('563160', 'Karnataka', true, true, 'india_post_import'),
  ('563161', 'Karnataka', true, true, 'india_post_import'),
  ('563162', 'Karnataka', true, true, 'india_post_import'),
  ('563163', 'Karnataka', true, true, 'india_post_import'),
  ('570001', 'Karnataka', true, true, 'india_post_import'),
  ('570002', 'Karnataka', true, true, 'india_post_import'),
  ('570003', 'Karnataka', true, true, 'india_post_import'),
  ('570004', 'Karnataka', true, true, 'india_post_import'),
  ('570005', 'Karnataka', true, true, 'india_post_import'),
  ('570006', 'Karnataka', true, true, 'india_post_import'),
  ('570007', 'Karnataka', true, true, 'india_post_import'),
  ('570008', 'Karnataka', true, true, 'india_post_import'),
  ('570009', 'Karnataka', true, true, 'india_post_import'),
  ('570010', 'Karnataka', true, true, 'india_post_import'),
  ('570011', 'Karnataka', true, true, 'india_post_import'),
  ('570012', 'Karnataka', true, true, 'india_post_import'),
  ('570014', 'Karnataka', true, true, 'india_post_import'),
  ('570015', 'Karnataka', true, true, 'india_post_import'),
  ('570016', 'Karnataka', true, true, 'india_post_import'),
  ('570017', 'Karnataka', true, true, 'india_post_import'),
  ('570018', 'Karnataka', true, true, 'india_post_import'),
  ('570019', 'Karnataka', true, true, 'india_post_import'),
  ('570020', 'Karnataka', true, true, 'india_post_import'),
  ('570022', 'Karnataka', true, true, 'india_post_import'),
  ('570023', 'Karnataka', true, true, 'india_post_import'),
  ('570025', 'Karnataka', true, true, 'india_post_import'),
  ('570026', 'Karnataka', true, true, 'india_post_import'),
  ('570027', 'Karnataka', true, true, 'india_post_import'),
  ('570028', 'Karnataka', true, true, 'india_post_import'),
  ('570029', 'Karnataka', true, true, 'india_post_import'),
  ('570030', 'Karnataka', true, true, 'india_post_import'),
  ('570031', 'Karnataka', true, true, 'india_post_import'),
  ('570032', 'Karnataka', true, true, 'india_post_import'),
  ('570033', 'Karnataka', true, true, 'india_post_import'),
  ('570034', 'Karnataka', true, true, 'india_post_import'),
  ('571101', 'Karnataka', true, true, 'india_post_import'),
  ('571102', 'Karnataka', true, true, 'india_post_import'),
  ('571103', 'Karnataka', true, true, 'india_post_import'),
  ('571104', 'Karnataka', true, true, 'india_post_import'),
  ('571105', 'Karnataka', true, true, 'india_post_import'),
  ('571106', 'Karnataka', true, true, 'india_post_import'),
  ('571107', 'Karnataka', true, true, 'india_post_import'),
  ('571108', 'Karnataka', true, true, 'india_post_import'),
  ('571109', 'Karnataka', true, true, 'india_post_import'),
  ('571110', 'Karnataka', true, true, 'india_post_import'),
  ('571111', 'Karnataka', true, true, 'india_post_import'),
  ('571114', 'Karnataka', true, true, 'india_post_import'),
  ('571115', 'Karnataka', true, true, 'india_post_import'),
  ('571116', 'Karnataka', true, true, 'india_post_import'),
  ('571117', 'Karnataka', true, true, 'india_post_import'),
  ('571118', 'Karnataka', true, true, 'india_post_import'),
  ('571119', 'Karnataka', true, true, 'india_post_import'),
  ('571120', 'Karnataka', true, true, 'india_post_import'),
  ('571121', 'Karnataka', true, true, 'india_post_import'),
  ('571122', 'Karnataka', true, true, 'india_post_import'),
  ('571123', 'Karnataka', true, true, 'india_post_import'),
  ('571124', 'Karnataka', true, true, 'india_post_import'),
  ('571125', 'Karnataka', true, true, 'india_post_import'),
  ('571126', 'Karnataka', true, true, 'india_post_import'),
  ('571127', 'Karnataka', true, true, 'india_post_import'),
  ('571128', 'Karnataka', true, true, 'india_post_import'),
  ('571129', 'Karnataka', true, true, 'india_post_import'),
  ('571130', 'Karnataka', true, true, 'india_post_import'),
  ('571134', 'Karnataka', true, true, 'india_post_import'),
  ('571187', 'Karnataka', true, true, 'india_post_import'),
  ('571189', 'Karnataka', true, true, 'india_post_import'),
  ('571201', 'Karnataka', true, true, 'india_post_import'),
  ('571211', 'Karnataka', true, true, 'india_post_import'),
  ('571212', 'Karnataka', true, true, 'india_post_import'),
  ('571213', 'Karnataka', true, true, 'india_post_import'),
  ('571214', 'Karnataka', true, true, 'india_post_import'),
  ('571215', 'Karnataka', true, true, 'india_post_import'),
  ('571216', 'Karnataka', true, true, 'india_post_import'),
  ('571217', 'Karnataka', true, true, 'india_post_import'),
  ('571218', 'Karnataka', true, true, 'india_post_import'),
  ('571219', 'Karnataka', true, true, 'india_post_import'),
  ('571231', 'Karnataka', true, true, 'india_post_import'),
  ('571232', 'Karnataka', true, true, 'india_post_import'),
  ('571234', 'Karnataka', true, true, 'india_post_import'),
  ('571235', 'Karnataka', true, true, 'india_post_import'),
  ('571236', 'Karnataka', true, true, 'india_post_import'),
  ('571237', 'Karnataka', true, true, 'india_post_import'),
  ('571247', 'Karnataka', true, true, 'india_post_import'),
  ('571248', 'Karnataka', true, true, 'india_post_import'),
  ('571249', 'Karnataka', true, true, 'india_post_import'),
  ('571250', 'Karnataka', true, true, 'india_post_import'),
  ('571251', 'Karnataka', true, true, 'india_post_import'),
  ('571252', 'Karnataka', true, true, 'india_post_import'),
  ('571253', 'Karnataka', true, true, 'india_post_import'),
  ('571254', 'Karnataka', true, true, 'india_post_import'),
  ('571301', 'Karnataka', true, true, 'india_post_import'),
  ('571302', 'Karnataka', true, true, 'india_post_import'),
  ('571311', 'Karnataka', true, true, 'india_post_import'),
  ('571312', 'Karnataka', true, true, 'india_post_import'),
  ('571313', 'Karnataka', true, true, 'india_post_import'),
  ('571314', 'Karnataka', true, true, 'india_post_import'),
  ('571315', 'Karnataka', true, true, 'india_post_import'),
  ('571316', 'Karnataka', true, true, 'india_post_import'),
  ('571320', 'Karnataka', true, true, 'india_post_import'),
  ('571342', 'Karnataka', true, true, 'india_post_import'),
  ('571401', 'Karnataka', true, true, 'india_post_import'),
  ('571402', 'Karnataka', true, true, 'india_post_import'),
  ('571403', 'Karnataka', true, true, 'india_post_import'),
  ('571404', 'Karnataka', true, true, 'india_post_import'),
  ('571405', 'Karnataka', true, true, 'india_post_import'),
  ('571415', 'Karnataka', true, true, 'india_post_import'),
  ('571416', 'Karnataka', true, true, 'india_post_import'),
  ('571417', 'Karnataka', true, true, 'india_post_import'),
  ('571418', 'Karnataka', true, true, 'india_post_import'),
  ('571419', 'Karnataka', true, true, 'india_post_import'),
  ('571421', 'Karnataka', true, true, 'india_post_import'),
  ('571422', 'Karnataka', true, true, 'india_post_import'),
  ('571423', 'Karnataka', true, true, 'india_post_import'),
  ('571424', 'Karnataka', true, true, 'india_post_import'),
  ('571425', 'Karnataka', true, true, 'india_post_import'),
  ('571426', 'Karnataka', true, true, 'india_post_import'),
  ('571427', 'Karnataka', true, true, 'india_post_import'),
  ('571428', 'Karnataka', true, true, 'india_post_import'),
  ('571429', 'Karnataka', true, true, 'india_post_import'),
  ('571430', 'Karnataka', true, true, 'india_post_import'),
  ('571431', 'Karnataka', true, true, 'india_post_import'),
  ('571432', 'Karnataka', true, true, 'india_post_import'),
  ('571433', 'Karnataka', true, true, 'india_post_import'),
  ('571434', 'Karnataka', true, true, 'india_post_import'),
  ('571435', 'Karnataka', true, true, 'india_post_import'),
  ('571436', 'Karnataka', true, true, 'india_post_import'),
  ('571438', 'Karnataka', true, true, 'india_post_import'),
  ('571439', 'Karnataka', true, true, 'india_post_import'),
  ('571440', 'Karnataka', true, true, 'india_post_import'),
  ('571441', 'Karnataka', true, true, 'india_post_import'),
  ('571442', 'Karnataka', true, true, 'india_post_import'),
  ('571443', 'Karnataka', true, true, 'india_post_import'),
  ('571444', 'Karnataka', true, true, 'india_post_import'),
  ('571445', 'Karnataka', true, true, 'india_post_import'),
  ('571446', 'Karnataka', true, true, 'india_post_import'),
  ('571448', 'Karnataka', true, true, 'india_post_import'),
  ('571450', 'Karnataka', true, true, 'india_post_import'),
  ('571455', 'Karnataka', true, true, 'india_post_import'),
  ('571457', 'Karnataka', true, true, 'india_post_import'),
  ('571463', 'Karnataka', true, true, 'india_post_import'),
  ('571475', 'Karnataka', true, true, 'india_post_import'),
  ('571476', 'Karnataka', true, true, 'india_post_import'),
  ('571477', 'Karnataka', true, true, 'india_post_import'),
  ('571478', 'Karnataka', true, true, 'india_post_import'),
  ('571490', 'Karnataka', true, true, 'india_post_import'),
  ('571601', 'Karnataka', true, true, 'india_post_import'),
  ('571602', 'Karnataka', true, true, 'india_post_import'),
  ('571603', 'Karnataka', true, true, 'india_post_import'),
  ('571604', 'Karnataka', true, true, 'india_post_import'),
  ('571605', 'Karnataka', true, true, 'india_post_import'),
  ('571606', 'Karnataka', true, true, 'india_post_import'),
  ('571607', 'Karnataka', true, true, 'india_post_import'),
  ('571610', 'Karnataka', true, true, 'india_post_import'),
  ('571617', 'Karnataka', true, true, 'india_post_import'),
  ('571802', 'Karnataka', true, true, 'india_post_import'),
  ('571807', 'Karnataka', true, true, 'india_post_import'),
  ('571811', 'Karnataka', true, true, 'india_post_import'),
  ('571812', 'Karnataka', true, true, 'india_post_import'),
  ('572101', 'Karnataka', true, true, 'india_post_import'),
  ('572102', 'Karnataka', true, true, 'india_post_import'),
  ('572103', 'Karnataka', true, true, 'india_post_import'),
  ('572104', 'Karnataka', true, true, 'india_post_import'),
  ('572105', 'Karnataka', true, true, 'india_post_import'),
  ('572106', 'Karnataka', true, true, 'india_post_import'),
  ('572107', 'Karnataka', true, true, 'india_post_import'),
  ('572111', 'Karnataka', true, true, 'india_post_import'),
  ('572112', 'Karnataka', true, true, 'india_post_import'),
  ('572113', 'Karnataka', true, true, 'india_post_import'),
  ('572114', 'Karnataka', true, true, 'india_post_import'),
  ('572115', 'Karnataka', true, true, 'india_post_import'),
  ('572116', 'Karnataka', true, true, 'india_post_import'),
  ('572117', 'Karnataka', true, true, 'india_post_import'),
  ('572118', 'Karnataka', true, true, 'india_post_import'),
  ('572119', 'Karnataka', true, true, 'india_post_import'),
  ('572120', 'Karnataka', true, true, 'india_post_import'),
  ('572121', 'Karnataka', true, true, 'india_post_import'),
  ('572122', 'Karnataka', true, true, 'india_post_import'),
  ('572123', 'Karnataka', true, true, 'india_post_import'),
  ('572124', 'Karnataka', true, true, 'india_post_import'),
  ('572125', 'Karnataka', true, true, 'india_post_import'),
  ('572126', 'Karnataka', true, true, 'india_post_import'),
  ('572127', 'Karnataka', true, true, 'india_post_import'),
  ('572128', 'Karnataka', true, true, 'india_post_import'),
  ('572129', 'Karnataka', true, true, 'india_post_import'),
  ('572130', 'Karnataka', true, true, 'india_post_import'),
  ('572132', 'Karnataka', true, true, 'india_post_import'),
  ('572133', 'Karnataka', true, true, 'india_post_import'),
  ('572134', 'Karnataka', true, true, 'india_post_import'),
  ('572135', 'Karnataka', true, true, 'india_post_import')
on conflict (pincode) do nothing;