-- =====================================================================
-- Jayvi Foods — Pincode seed, file 20 of 21: pincodes rows 17371-18335
-- Run supabase_seed_pincodes_01_states.sql FIRST. Files 02-21 can then
-- run in any order (each is independent, uses ON CONFLICT DO NOTHING —
-- safe to re-run this specific file if it fails partway).
-- This file: 965 rows.
-- =====================================================================

insert into public.pincodes (pincode, state, serviceable, active, source) values
  ('262725', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262726', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262727', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262728', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262801', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262802', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262803', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262804', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262805', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262901', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262902', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262903', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262904', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262905', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262906', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262907', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('262908', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271129', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271208', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271209', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271210', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271215', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271307', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271308', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271309', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271310', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271311', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271312', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271313', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271319', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271502', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271503', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271504', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271601', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271602', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271603', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271604', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271607', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271609', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271801', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271802', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271803', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271804', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271805', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271806', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271821', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271824', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271825', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271830', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271831', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271835', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271840', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271841', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271845', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271851', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271855', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271861', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271865', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271870', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271871', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271872', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271875', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271881', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271882', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271901', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271902', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271903', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('271904', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272127', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272128', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272129', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272130', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272131', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272148', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272150', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272151', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272152', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272153', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272154', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272155', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272161', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272162', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272163', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272164', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272165', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272171', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272172', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272173', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272175', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272176', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272177', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272178', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272181', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272182', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272189', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272190', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272191', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272192', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272193', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272194', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272195', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272199', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272208', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272270', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272271', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('272302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273004', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273005', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273006', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273007', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273008', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273009', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273010', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273012', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273013', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273014', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273015', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273016', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273017', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273151', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273152', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273155', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273157', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273158', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273161', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273162', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273163', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273164', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273165', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273209', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273211', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273212', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273213', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273308', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273309', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273310', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273311', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273404', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273405', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273406', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273407', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273408', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273409', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273411', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273412', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('273413', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274149', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274182', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274208', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274307', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274308', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274309', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274404', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274405', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274406', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274407', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274408', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274409', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274501', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274502', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274505', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274506', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274508', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274509', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274601', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274602', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274603', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274604', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274701', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274702', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274703', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274704', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274705', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274801', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274802', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274805', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274806', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274807', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('274808', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275101', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275102', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275103', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275105', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('275307', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276127', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276128', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276129', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276131', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276135', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276136', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276137', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276138', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276139', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276140', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276141', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276142', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276143', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276208', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276288', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276404', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276405', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('276406', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277208', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277209', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277210', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277211', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277213', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277214', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277216', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277219', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277501', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277502', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277503', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277504', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('277506', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281004', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281005', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281006', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281104', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281307', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281308', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281404', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281405', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281406', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281501', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281502', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('281504', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282004', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282005', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282006', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282007', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282008', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282009', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('282010', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283101', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283102', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283103', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283104', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283105', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283110', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283111', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283112', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283113', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283114', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283115', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283119', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283130', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283135', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283136', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283141', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283142', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283145', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283151', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283152', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('283207', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284002', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284003', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284120', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284127', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284128', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284135', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284136', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284301', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284302', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284303', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284304', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284305', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284306', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284401', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284402', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284403', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284404', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284405', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284406', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284419', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('284501', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285001', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285121', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285122', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285123', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285124', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285125', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285126', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285127', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285128', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285129', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285130', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285201', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285202', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285203', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285204', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285205', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285206', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('285223', 'Uttar Pradesh', true, true, 'india_post_import'),
  ('244712', 'Uttarakhand', true, true, 'india_post_import'),
  ('244713', 'Uttarakhand', true, true, 'india_post_import'),
  ('244715', 'Uttarakhand', true, true, 'india_post_import'),
  ('244716', 'Uttarakhand', true, true, 'india_post_import'),
  ('244717', 'Uttarakhand', true, true, 'india_post_import'),
  ('244720', 'Uttarakhand', true, true, 'india_post_import'),
  ('246001', 'Uttarakhand', true, true, 'india_post_import'),
  ('246113', 'Uttarakhand', true, true, 'india_post_import'),
  ('246121', 'Uttarakhand', true, true, 'india_post_import'),
  ('246123', 'Uttarakhand', true, true, 'india_post_import'),
  ('246124', 'Uttarakhand', true, true, 'india_post_import'),
  ('246125', 'Uttarakhand', true, true, 'india_post_import'),
  ('246127', 'Uttarakhand', true, true, 'india_post_import'),
  ('246128', 'Uttarakhand', true, true, 'india_post_import'),
  ('246129', 'Uttarakhand', true, true, 'india_post_import'),
  ('246130', 'Uttarakhand', true, true, 'india_post_import'),
  ('246131', 'Uttarakhand', true, true, 'india_post_import'),
  ('246141', 'Uttarakhand', true, true, 'india_post_import'),
  ('246142', 'Uttarakhand', true, true, 'india_post_import'),
  ('246144', 'Uttarakhand', true, true, 'india_post_import'),
  ('246146', 'Uttarakhand', true, true, 'india_post_import'),
  ('246147', 'Uttarakhand', true, true, 'india_post_import'),
  ('246148', 'Uttarakhand', true, true, 'india_post_import'),
  ('246149', 'Uttarakhand', true, true, 'india_post_import'),
  ('246150', 'Uttarakhand', true, true, 'india_post_import'),
  ('246155', 'Uttarakhand', true, true, 'india_post_import'),
  ('246159', 'Uttarakhand', true, true, 'india_post_import'),
  ('246161', 'Uttarakhand', true, true, 'india_post_import'),
  ('246162', 'Uttarakhand', true, true, 'india_post_import'),
  ('246163', 'Uttarakhand', true, true, 'india_post_import'),
  ('246164', 'Uttarakhand', true, true, 'india_post_import'),
  ('246165', 'Uttarakhand', true, true, 'india_post_import'),
  ('246166', 'Uttarakhand', true, true, 'india_post_import'),
  ('246167', 'Uttarakhand', true, true, 'india_post_import'),
  ('246169', 'Uttarakhand', true, true, 'india_post_import'),
  ('246171', 'Uttarakhand', true, true, 'india_post_import'),
  ('246172', 'Uttarakhand', true, true, 'india_post_import'),
  ('246173', 'Uttarakhand', true, true, 'india_post_import'),
  ('246174', 'Uttarakhand', true, true, 'india_post_import'),
  ('246175', 'Uttarakhand', true, true, 'india_post_import'),
  ('246176', 'Uttarakhand', true, true, 'india_post_import'),
  ('246177', 'Uttarakhand', true, true, 'india_post_import'),
  ('246178', 'Uttarakhand', true, true, 'india_post_import'),
  ('246179', 'Uttarakhand', true, true, 'india_post_import'),
  ('246193', 'Uttarakhand', true, true, 'india_post_import'),
  ('246194', 'Uttarakhand', true, true, 'india_post_import'),
  ('246275', 'Uttarakhand', true, true, 'india_post_import'),
  ('246276', 'Uttarakhand', true, true, 'india_post_import'),
  ('246277', 'Uttarakhand', true, true, 'india_post_import'),
  ('246278', 'Uttarakhand', true, true, 'india_post_import'),
  ('246279', 'Uttarakhand', true, true, 'india_post_import'),
  ('246285', 'Uttarakhand', true, true, 'india_post_import'),
  ('246401', 'Uttarakhand', true, true, 'india_post_import'),
  ('246419', 'Uttarakhand', true, true, 'india_post_import'),
  ('246421', 'Uttarakhand', true, true, 'india_post_import'),
  ('246422', 'Uttarakhand', true, true, 'india_post_import'),
  ('246424', 'Uttarakhand', true, true, 'india_post_import'),
  ('246425', 'Uttarakhand', true, true, 'india_post_import'),
  ('246426', 'Uttarakhand', true, true, 'india_post_import'),
  ('246427', 'Uttarakhand', true, true, 'india_post_import'),
  ('246428', 'Uttarakhand', true, true, 'india_post_import'),
  ('246429', 'Uttarakhand', true, true, 'india_post_import'),
  ('246431', 'Uttarakhand', true, true, 'india_post_import'),
  ('246435', 'Uttarakhand', true, true, 'india_post_import'),
  ('246439', 'Uttarakhand', true, true, 'india_post_import'),
  ('246440', 'Uttarakhand', true, true, 'india_post_import'),
  ('246441', 'Uttarakhand', true, true, 'india_post_import'),
  ('246442', 'Uttarakhand', true, true, 'india_post_import'),
  ('246443', 'Uttarakhand', true, true, 'india_post_import'),
  ('246444', 'Uttarakhand', true, true, 'india_post_import'),
  ('246445', 'Uttarakhand', true, true, 'india_post_import'),
  ('246446', 'Uttarakhand', true, true, 'india_post_import'),
  ('246448', 'Uttarakhand', true, true, 'india_post_import'),
  ('246449', 'Uttarakhand', true, true, 'india_post_import'),
  ('246453', 'Uttarakhand', true, true, 'india_post_import'),
  ('246455', 'Uttarakhand', true, true, 'india_post_import'),
  ('246469', 'Uttarakhand', true, true, 'india_post_import'),
  ('246471', 'Uttarakhand', true, true, 'india_post_import'),
  ('246472', 'Uttarakhand', true, true, 'india_post_import'),
  ('246473', 'Uttarakhand', true, true, 'india_post_import'),
  ('246474', 'Uttarakhand', true, true, 'india_post_import'),
  ('246475', 'Uttarakhand', true, true, 'india_post_import'),
  ('246481', 'Uttarakhand', true, true, 'india_post_import'),
  ('246482', 'Uttarakhand', true, true, 'india_post_import'),
  ('246483', 'Uttarakhand', true, true, 'india_post_import'),
  ('246486', 'Uttarakhand', true, true, 'india_post_import'),
  ('246487', 'Uttarakhand', true, true, 'india_post_import'),
  ('246488', 'Uttarakhand', true, true, 'india_post_import'),
  ('246495', 'Uttarakhand', true, true, 'india_post_import'),
  ('247656', 'Uttarakhand', true, true, 'india_post_import'),
  ('247661', 'Uttarakhand', true, true, 'india_post_import'),
  ('247663', 'Uttarakhand', true, true, 'india_post_import'),
  ('247664', 'Uttarakhand', true, true, 'india_post_import'),
  ('247665', 'Uttarakhand', true, true, 'india_post_import'),
  ('247666', 'Uttarakhand', true, true, 'india_post_import'),
  ('247667', 'Uttarakhand', true, true, 'india_post_import'),
  ('247668', 'Uttarakhand', true, true, 'india_post_import'),
  ('247670', 'Uttarakhand', true, true, 'india_post_import'),
  ('247671', 'Uttarakhand', true, true, 'india_post_import'),
  ('248001', 'Uttarakhand', true, true, 'india_post_import'),
  ('248002', 'Uttarakhand', true, true, 'india_post_import'),
  ('248003', 'Uttarakhand', true, true, 'india_post_import'),
  ('248005', 'Uttarakhand', true, true, 'india_post_import'),
  ('248006', 'Uttarakhand', true, true, 'india_post_import'),
  ('248007', 'Uttarakhand', true, true, 'india_post_import'),
  ('248008', 'Uttarakhand', true, true, 'india_post_import'),
  ('248009', 'Uttarakhand', true, true, 'india_post_import'),
  ('248011', 'Uttarakhand', true, true, 'india_post_import'),
  ('248012', 'Uttarakhand', true, true, 'india_post_import'),
  ('248013', 'Uttarakhand', true, true, 'india_post_import'),
  ('248014', 'Uttarakhand', true, true, 'india_post_import'),
  ('248015', 'Uttarakhand', true, true, 'india_post_import'),
  ('248016', 'Uttarakhand', true, true, 'india_post_import'),
  ('248018', 'Uttarakhand', true, true, 'india_post_import'),
  ('248019', 'Uttarakhand', true, true, 'india_post_import'),
  ('248121', 'Uttarakhand', true, true, 'india_post_import'),
  ('248122', 'Uttarakhand', true, true, 'india_post_import'),
  ('248123', 'Uttarakhand', true, true, 'india_post_import'),
  ('248124', 'Uttarakhand', true, true, 'india_post_import'),
  ('248125', 'Uttarakhand', true, true, 'india_post_import'),
  ('248140', 'Uttarakhand', true, true, 'india_post_import'),
  ('248142', 'Uttarakhand', true, true, 'india_post_import'),
  ('248143', 'Uttarakhand', true, true, 'india_post_import'),
  ('248145', 'Uttarakhand', true, true, 'india_post_import'),
  ('248146', 'Uttarakhand', true, true, 'india_post_import'),
  ('248158', 'Uttarakhand', true, true, 'india_post_import'),
  ('248159', 'Uttarakhand', true, true, 'india_post_import'),
  ('248165', 'Uttarakhand', true, true, 'india_post_import'),
  ('248171', 'Uttarakhand', true, true, 'india_post_import'),
  ('248179', 'Uttarakhand', true, true, 'india_post_import'),
  ('248195', 'Uttarakhand', true, true, 'india_post_import'),
  ('248196', 'Uttarakhand', true, true, 'india_post_import'),
  ('248197', 'Uttarakhand', true, true, 'india_post_import'),
  ('248198', 'Uttarakhand', true, true, 'india_post_import'),
  ('248199', 'Uttarakhand', true, true, 'india_post_import'),
  ('249001', 'Uttarakhand', true, true, 'india_post_import'),
  ('249121', 'Uttarakhand', true, true, 'india_post_import'),
  ('249122', 'Uttarakhand', true, true, 'india_post_import'),
  ('249123', 'Uttarakhand', true, true, 'india_post_import'),
  ('249124', 'Uttarakhand', true, true, 'india_post_import'),
  ('249125', 'Uttarakhand', true, true, 'india_post_import'),
  ('249126', 'Uttarakhand', true, true, 'india_post_import'),
  ('249127', 'Uttarakhand', true, true, 'india_post_import'),
  ('249128', 'Uttarakhand', true, true, 'india_post_import'),
  ('249130', 'Uttarakhand', true, true, 'india_post_import'),
  ('249131', 'Uttarakhand', true, true, 'india_post_import'),
  ('249132', 'Uttarakhand', true, true, 'india_post_import'),
  ('249135', 'Uttarakhand', true, true, 'india_post_import'),
  ('249136', 'Uttarakhand', true, true, 'india_post_import'),
  ('249137', 'Uttarakhand', true, true, 'india_post_import'),
  ('249141', 'Uttarakhand', true, true, 'india_post_import'),
  ('249145', 'Uttarakhand', true, true, 'india_post_import'),
  ('249146', 'Uttarakhand', true, true, 'india_post_import'),
  ('249151', 'Uttarakhand', true, true, 'india_post_import'),
  ('249152', 'Uttarakhand', true, true, 'india_post_import'),
  ('249155', 'Uttarakhand', true, true, 'india_post_import'),
  ('249161', 'Uttarakhand', true, true, 'india_post_import'),
  ('249165', 'Uttarakhand', true, true, 'india_post_import'),
  ('249171', 'Uttarakhand', true, true, 'india_post_import'),
  ('249175', 'Uttarakhand', true, true, 'india_post_import'),
  ('249180', 'Uttarakhand', true, true, 'india_post_import'),
  ('249181', 'Uttarakhand', true, true, 'india_post_import'),
  ('249185', 'Uttarakhand', true, true, 'india_post_import'),
  ('249186', 'Uttarakhand', true, true, 'india_post_import'),
  ('249192', 'Uttarakhand', true, true, 'india_post_import'),
  ('249193', 'Uttarakhand', true, true, 'india_post_import'),
  ('249194', 'Uttarakhand', true, true, 'india_post_import'),
  ('249195', 'Uttarakhand', true, true, 'india_post_import'),
  ('249196', 'Uttarakhand', true, true, 'india_post_import'),
  ('249199', 'Uttarakhand', true, true, 'india_post_import'),
  ('249201', 'Uttarakhand', true, true, 'india_post_import'),
  ('249202', 'Uttarakhand', true, true, 'india_post_import'),
  ('249203', 'Uttarakhand', true, true, 'india_post_import'),
  ('249204', 'Uttarakhand', true, true, 'india_post_import'),
  ('249205', 'Uttarakhand', true, true, 'india_post_import'),
  ('249301', 'Uttarakhand', true, true, 'india_post_import'),
  ('249302', 'Uttarakhand', true, true, 'india_post_import'),
  ('249304', 'Uttarakhand', true, true, 'india_post_import'),
  ('249306', 'Uttarakhand', true, true, 'india_post_import'),
  ('249401', 'Uttarakhand', true, true, 'india_post_import'),
  ('249402', 'Uttarakhand', true, true, 'india_post_import'),
  ('249403', 'Uttarakhand', true, true, 'india_post_import'),
  ('249404', 'Uttarakhand', true, true, 'india_post_import'),
  ('249405', 'Uttarakhand', true, true, 'india_post_import'),
  ('249407', 'Uttarakhand', true, true, 'india_post_import'),
  ('249408', 'Uttarakhand', true, true, 'india_post_import'),
  ('249410', 'Uttarakhand', true, true, 'india_post_import'),
  ('249411', 'Uttarakhand', true, true, 'india_post_import'),
  ('262308', 'Uttarakhand', true, true, 'india_post_import'),
  ('262309', 'Uttarakhand', true, true, 'india_post_import'),
  ('262310', 'Uttarakhand', true, true, 'india_post_import'),
  ('262311', 'Uttarakhand', true, true, 'india_post_import'),
  ('262401', 'Uttarakhand', true, true, 'india_post_import'),
  ('262402', 'Uttarakhand', true, true, 'india_post_import'),
  ('262405', 'Uttarakhand', true, true, 'india_post_import'),
  ('262501', 'Uttarakhand', true, true, 'india_post_import'),
  ('262502', 'Uttarakhand', true, true, 'india_post_import'),
  ('262520', 'Uttarakhand', true, true, 'india_post_import'),
  ('262521', 'Uttarakhand', true, true, 'india_post_import'),
  ('262522', 'Uttarakhand', true, true, 'india_post_import'),
  ('262523', 'Uttarakhand', true, true, 'india_post_import'),
  ('262524', 'Uttarakhand', true, true, 'india_post_import'),
  ('262525', 'Uttarakhand', true, true, 'india_post_import'),
  ('262526', 'Uttarakhand', true, true, 'india_post_import'),
  ('262527', 'Uttarakhand', true, true, 'india_post_import'),
  ('262528', 'Uttarakhand', true, true, 'india_post_import'),
  ('262529', 'Uttarakhand', true, true, 'india_post_import'),
  ('262530', 'Uttarakhand', true, true, 'india_post_import'),
  ('262531', 'Uttarakhand', true, true, 'india_post_import'),
  ('262532', 'Uttarakhand', true, true, 'india_post_import'),
  ('262533', 'Uttarakhand', true, true, 'india_post_import'),
  ('262534', 'Uttarakhand', true, true, 'india_post_import'),
  ('262540', 'Uttarakhand', true, true, 'india_post_import'),
  ('262541', 'Uttarakhand', true, true, 'india_post_import'),
  ('262542', 'Uttarakhand', true, true, 'india_post_import'),
  ('262543', 'Uttarakhand', true, true, 'india_post_import'),
  ('262544', 'Uttarakhand', true, true, 'india_post_import'),
  ('262545', 'Uttarakhand', true, true, 'india_post_import'),
  ('262546', 'Uttarakhand', true, true, 'india_post_import'),
  ('262547', 'Uttarakhand', true, true, 'india_post_import'),
  ('262550', 'Uttarakhand', true, true, 'india_post_import'),
  ('262551', 'Uttarakhand', true, true, 'india_post_import'),
  ('262552', 'Uttarakhand', true, true, 'india_post_import'),
  ('262553', 'Uttarakhand', true, true, 'india_post_import'),
  ('262554', 'Uttarakhand', true, true, 'india_post_import'),
  ('262555', 'Uttarakhand', true, true, 'india_post_import'),
  ('262561', 'Uttarakhand', true, true, 'india_post_import'),
  ('262572', 'Uttarakhand', true, true, 'india_post_import'),
  ('262576', 'Uttarakhand', true, true, 'india_post_import'),
  ('262580', 'Uttarakhand', true, true, 'india_post_import'),
  ('263001', 'Uttarakhand', true, true, 'india_post_import'),
  ('263126', 'Uttarakhand', true, true, 'india_post_import'),
  ('263127', 'Uttarakhand', true, true, 'india_post_import'),
  ('263128', 'Uttarakhand', true, true, 'india_post_import'),
  ('263132', 'Uttarakhand', true, true, 'india_post_import'),
  ('263134', 'Uttarakhand', true, true, 'india_post_import'),
  ('263135', 'Uttarakhand', true, true, 'india_post_import'),
  ('263136', 'Uttarakhand', true, true, 'india_post_import'),
  ('263137', 'Uttarakhand', true, true, 'india_post_import'),
  ('263138', 'Uttarakhand', true, true, 'india_post_import'),
  ('263139', 'Uttarakhand', true, true, 'india_post_import'),
  ('263140', 'Uttarakhand', true, true, 'india_post_import'),
  ('263142', 'Uttarakhand', true, true, 'india_post_import'),
  ('263145', 'Uttarakhand', true, true, 'india_post_import'),
  ('263148', 'Uttarakhand', true, true, 'india_post_import'),
  ('263149', 'Uttarakhand', true, true, 'india_post_import'),
  ('263150', 'Uttarakhand', true, true, 'india_post_import'),
  ('263151', 'Uttarakhand', true, true, 'india_post_import'),
  ('263152', 'Uttarakhand', true, true, 'india_post_import'),
  ('263153', 'Uttarakhand', true, true, 'india_post_import'),
  ('263156', 'Uttarakhand', true, true, 'india_post_import'),
  ('263157', 'Uttarakhand', true, true, 'india_post_import'),
  ('263158', 'Uttarakhand', true, true, 'india_post_import'),
  ('263159', 'Uttarakhand', true, true, 'india_post_import'),
  ('263160', 'Uttarakhand', true, true, 'india_post_import'),
  ('263601', 'Uttarakhand', true, true, 'india_post_import'),
  ('263619', 'Uttarakhand', true, true, 'india_post_import'),
  ('263620', 'Uttarakhand', true, true, 'india_post_import'),
  ('263621', 'Uttarakhand', true, true, 'india_post_import'),
  ('263622', 'Uttarakhand', true, true, 'india_post_import'),
  ('263623', 'Uttarakhand', true, true, 'india_post_import'),
  ('263624', 'Uttarakhand', true, true, 'india_post_import'),
  ('263625', 'Uttarakhand', true, true, 'india_post_import'),
  ('263626', 'Uttarakhand', true, true, 'india_post_import'),
  ('263628', 'Uttarakhand', true, true, 'india_post_import'),
  ('263629', 'Uttarakhand', true, true, 'india_post_import'),
  ('263630', 'Uttarakhand', true, true, 'india_post_import'),
  ('263631', 'Uttarakhand', true, true, 'india_post_import'),
  ('263632', 'Uttarakhand', true, true, 'india_post_import'),
  ('263633', 'Uttarakhand', true, true, 'india_post_import'),
  ('263634', 'Uttarakhand', true, true, 'india_post_import'),
  ('263635', 'Uttarakhand', true, true, 'india_post_import'),
  ('263636', 'Uttarakhand', true, true, 'india_post_import'),
  ('263637', 'Uttarakhand', true, true, 'india_post_import'),
  ('263638', 'Uttarakhand', true, true, 'india_post_import'),
  ('263639', 'Uttarakhand', true, true, 'india_post_import'),
  ('263640', 'Uttarakhand', true, true, 'india_post_import'),
  ('263641', 'Uttarakhand', true, true, 'india_post_import'),
  ('263642', 'Uttarakhand', true, true, 'india_post_import'),
  ('263643', 'Uttarakhand', true, true, 'india_post_import'),
  ('263645', 'Uttarakhand', true, true, 'india_post_import'),
  ('263646', 'Uttarakhand', true, true, 'india_post_import'),
  ('263651', 'Uttarakhand', true, true, 'india_post_import'),
  ('263652', 'Uttarakhand', true, true, 'india_post_import'),
  ('263653', 'Uttarakhand', true, true, 'india_post_import'),
  ('263655', 'Uttarakhand', true, true, 'india_post_import'),
  ('263656', 'Uttarakhand', true, true, 'india_post_import'),
  ('263658', 'Uttarakhand', true, true, 'india_post_import'),
  ('263659', 'Uttarakhand', true, true, 'india_post_import'),
  ('263660', 'Uttarakhand', true, true, 'india_post_import'),
  ('263661', 'Uttarakhand', true, true, 'india_post_import'),
  ('263663', 'Uttarakhand', true, true, 'india_post_import'),
  ('263664', 'Uttarakhand', true, true, 'india_post_import'),
  ('263665', 'Uttarakhand', true, true, 'india_post_import'),
  ('263667', 'Uttarakhand', true, true, 'india_post_import'),
  ('263676', 'Uttarakhand', true, true, 'india_post_import'),
  ('263678', 'Uttarakhand', true, true, 'india_post_import'),
  ('263679', 'Uttarakhand', true, true, 'india_post_import'),
  ('263680', 'Uttarakhand', true, true, 'india_post_import'),
  ('700001', 'West Bengal', true, true, 'india_post_import'),
  ('700002', 'West Bengal', true, true, 'india_post_import'),
  ('700003', 'West Bengal', true, true, 'india_post_import'),
  ('700004', 'West Bengal', true, true, 'india_post_import'),
  ('700005', 'West Bengal', true, true, 'india_post_import'),
  ('700006', 'West Bengal', true, true, 'india_post_import'),
  ('700007', 'West Bengal', true, true, 'india_post_import'),
  ('700008', 'West Bengal', true, true, 'india_post_import'),
  ('700009', 'West Bengal', true, true, 'india_post_import'),
  ('700010', 'West Bengal', true, true, 'india_post_import'),
  ('700011', 'West Bengal', true, true, 'india_post_import'),
  ('700012', 'West Bengal', true, true, 'india_post_import'),
  ('700013', 'West Bengal', true, true, 'india_post_import'),
  ('700014', 'West Bengal', true, true, 'india_post_import'),
  ('700015', 'West Bengal', true, true, 'india_post_import'),
  ('700016', 'West Bengal', true, true, 'india_post_import'),
  ('700017', 'West Bengal', true, true, 'india_post_import'),
  ('700018', 'West Bengal', true, true, 'india_post_import'),
  ('700019', 'West Bengal', true, true, 'india_post_import'),
  ('700020', 'West Bengal', true, true, 'india_post_import'),
  ('700021', 'West Bengal', true, true, 'india_post_import'),
  ('700022', 'West Bengal', true, true, 'india_post_import'),
  ('700023', 'West Bengal', true, true, 'india_post_import'),
  ('700024', 'West Bengal', true, true, 'india_post_import'),
  ('700025', 'West Bengal', true, true, 'india_post_import'),
  ('700026', 'West Bengal', true, true, 'india_post_import'),
  ('700027', 'West Bengal', true, true, 'india_post_import'),
  ('700028', 'West Bengal', true, true, 'india_post_import'),
  ('700029', 'West Bengal', true, true, 'india_post_import'),
  ('700030', 'West Bengal', true, true, 'india_post_import'),
  ('700031', 'West Bengal', true, true, 'india_post_import'),
  ('700032', 'West Bengal', true, true, 'india_post_import'),
  ('700033', 'West Bengal', true, true, 'india_post_import'),
  ('700034', 'West Bengal', true, true, 'india_post_import'),
  ('700035', 'West Bengal', true, true, 'india_post_import'),
  ('700036', 'West Bengal', true, true, 'india_post_import'),
  ('700037', 'West Bengal', true, true, 'india_post_import'),
  ('700038', 'West Bengal', true, true, 'india_post_import'),
  ('700039', 'West Bengal', true, true, 'india_post_import'),
  ('700040', 'West Bengal', true, true, 'india_post_import'),
  ('700041', 'West Bengal', true, true, 'india_post_import'),
  ('700042', 'West Bengal', true, true, 'india_post_import'),
  ('700043', 'West Bengal', true, true, 'india_post_import'),
  ('700044', 'West Bengal', true, true, 'india_post_import'),
  ('700045', 'West Bengal', true, true, 'india_post_import'),
  ('700046', 'West Bengal', true, true, 'india_post_import'),
  ('700047', 'West Bengal', true, true, 'india_post_import'),
  ('700048', 'West Bengal', true, true, 'india_post_import'),
  ('700049', 'West Bengal', true, true, 'india_post_import'),
  ('700050', 'West Bengal', true, true, 'india_post_import'),
  ('700051', 'West Bengal', true, true, 'india_post_import'),
  ('700052', 'West Bengal', true, true, 'india_post_import'),
  ('700053', 'West Bengal', true, true, 'india_post_import'),
  ('700054', 'West Bengal', true, true, 'india_post_import'),
  ('700055', 'West Bengal', true, true, 'india_post_import'),
  ('700056', 'West Bengal', true, true, 'india_post_import'),
  ('700057', 'West Bengal', true, true, 'india_post_import'),
  ('700058', 'West Bengal', true, true, 'india_post_import'),
  ('700059', 'West Bengal', true, true, 'india_post_import'),
  ('700060', 'West Bengal', true, true, 'india_post_import'),
  ('700061', 'West Bengal', true, true, 'india_post_import'),
  ('700062', 'West Bengal', true, true, 'india_post_import'),
  ('700063', 'West Bengal', true, true, 'india_post_import'),
  ('700064', 'West Bengal', true, true, 'india_post_import'),
  ('700065', 'West Bengal', true, true, 'india_post_import'),
  ('700066', 'West Bengal', true, true, 'india_post_import'),
  ('700067', 'West Bengal', true, true, 'india_post_import'),
  ('700068', 'West Bengal', true, true, 'india_post_import'),
  ('700069', 'West Bengal', true, true, 'india_post_import'),
  ('700070', 'West Bengal', true, true, 'india_post_import'),
  ('700071', 'West Bengal', true, true, 'india_post_import'),
  ('700072', 'West Bengal', true, true, 'india_post_import'),
  ('700073', 'West Bengal', true, true, 'india_post_import'),
  ('700074', 'West Bengal', true, true, 'india_post_import'),
  ('700075', 'West Bengal', true, true, 'india_post_import'),
  ('700076', 'West Bengal', true, true, 'india_post_import'),
  ('700077', 'West Bengal', true, true, 'india_post_import'),
  ('700078', 'West Bengal', true, true, 'india_post_import'),
  ('700079', 'West Bengal', true, true, 'india_post_import'),
  ('700080', 'West Bengal', true, true, 'india_post_import'),
  ('700081', 'West Bengal', true, true, 'india_post_import'),
  ('700082', 'West Bengal', true, true, 'india_post_import'),
  ('700083', 'West Bengal', true, true, 'india_post_import'),
  ('700084', 'West Bengal', true, true, 'india_post_import'),
  ('700085', 'West Bengal', true, true, 'india_post_import'),
  ('700086', 'West Bengal', true, true, 'india_post_import'),
  ('700087', 'West Bengal', true, true, 'india_post_import'),
  ('700088', 'West Bengal', true, true, 'india_post_import'),
  ('700089', 'West Bengal', true, true, 'india_post_import'),
  ('700090', 'West Bengal', true, true, 'india_post_import'),
  ('700091', 'West Bengal', true, true, 'india_post_import'),
  ('700092', 'West Bengal', true, true, 'india_post_import'),
  ('700093', 'West Bengal', true, true, 'india_post_import'),
  ('700094', 'West Bengal', true, true, 'india_post_import'),
  ('700095', 'West Bengal', true, true, 'india_post_import'),
  ('700096', 'West Bengal', true, true, 'india_post_import'),
  ('700097', 'West Bengal', true, true, 'india_post_import'),
  ('700099', 'West Bengal', true, true, 'india_post_import'),
  ('700100', 'West Bengal', true, true, 'india_post_import'),
  ('700101', 'West Bengal', true, true, 'india_post_import'),
  ('700102', 'West Bengal', true, true, 'india_post_import'),
  ('700103', 'West Bengal', true, true, 'india_post_import'),
  ('700104', 'West Bengal', true, true, 'india_post_import'),
  ('700105', 'West Bengal', true, true, 'india_post_import'),
  ('700106', 'West Bengal', true, true, 'india_post_import'),
  ('700107', 'West Bengal', true, true, 'india_post_import'),
  ('700108', 'West Bengal', true, true, 'india_post_import'),
  ('700109', 'West Bengal', true, true, 'india_post_import'),
  ('700110', 'West Bengal', true, true, 'india_post_import'),
  ('700111', 'West Bengal', true, true, 'india_post_import'),
  ('700112', 'West Bengal', true, true, 'india_post_import'),
  ('700113', 'West Bengal', true, true, 'india_post_import'),
  ('700114', 'West Bengal', true, true, 'india_post_import'),
  ('700115', 'West Bengal', true, true, 'india_post_import'),
  ('700116', 'West Bengal', true, true, 'india_post_import'),
  ('700117', 'West Bengal', true, true, 'india_post_import'),
  ('700118', 'West Bengal', true, true, 'india_post_import'),
  ('700119', 'West Bengal', true, true, 'india_post_import'),
  ('700120', 'West Bengal', true, true, 'india_post_import'),
  ('700121', 'West Bengal', true, true, 'india_post_import'),
  ('700122', 'West Bengal', true, true, 'india_post_import'),
  ('700123', 'West Bengal', true, true, 'india_post_import'),
  ('700124', 'West Bengal', true, true, 'india_post_import'),
  ('700125', 'West Bengal', true, true, 'india_post_import'),
  ('700126', 'West Bengal', true, true, 'india_post_import'),
  ('700127', 'West Bengal', true, true, 'india_post_import'),
  ('700128', 'West Bengal', true, true, 'india_post_import'),
  ('700129', 'West Bengal', true, true, 'india_post_import'),
  ('700130', 'West Bengal', true, true, 'india_post_import'),
  ('700131', 'West Bengal', true, true, 'india_post_import'),
  ('700132', 'West Bengal', true, true, 'india_post_import'),
  ('700133', 'West Bengal', true, true, 'india_post_import'),
  ('700134', 'West Bengal', true, true, 'india_post_import'),
  ('700135', 'West Bengal', true, true, 'india_post_import'),
  ('700136', 'West Bengal', true, true, 'india_post_import'),
  ('700137', 'West Bengal', true, true, 'india_post_import'),
  ('700138', 'West Bengal', true, true, 'india_post_import'),
  ('700139', 'West Bengal', true, true, 'india_post_import'),
  ('700140', 'West Bengal', true, true, 'india_post_import'),
  ('700141', 'West Bengal', true, true, 'india_post_import'),
  ('700142', 'West Bengal', true, true, 'india_post_import'),
  ('700143', 'West Bengal', true, true, 'india_post_import'),
  ('700144', 'West Bengal', true, true, 'india_post_import'),
  ('700145', 'West Bengal', true, true, 'india_post_import'),
  ('700146', 'West Bengal', true, true, 'india_post_import'),
  ('700147', 'West Bengal', true, true, 'india_post_import'),
  ('700148', 'West Bengal', true, true, 'india_post_import'),
  ('700149', 'West Bengal', true, true, 'india_post_import'),
  ('700150', 'West Bengal', true, true, 'india_post_import'),
  ('700151', 'West Bengal', true, true, 'india_post_import'),
  ('700152', 'West Bengal', true, true, 'india_post_import'),
  ('700153', 'West Bengal', true, true, 'india_post_import'),
  ('700154', 'West Bengal', true, true, 'india_post_import'),
  ('700155', 'West Bengal', true, true, 'india_post_import'),
  ('700156', 'West Bengal', true, true, 'india_post_import'),
  ('700157', 'West Bengal', true, true, 'india_post_import'),
  ('700158', 'West Bengal', true, true, 'india_post_import'),
  ('700159', 'West Bengal', true, true, 'india_post_import'),
  ('700160', 'West Bengal', true, true, 'india_post_import'),
  ('700161', 'West Bengal', true, true, 'india_post_import'),
  ('700162', 'West Bengal', true, true, 'india_post_import'),
  ('700163', 'West Bengal', true, true, 'india_post_import'),
  ('711101', 'West Bengal', true, true, 'india_post_import'),
  ('711102', 'West Bengal', true, true, 'india_post_import'),
  ('711103', 'West Bengal', true, true, 'india_post_import'),
  ('711104', 'West Bengal', true, true, 'india_post_import'),
  ('711105', 'West Bengal', true, true, 'india_post_import'),
  ('711106', 'West Bengal', true, true, 'india_post_import'),
  ('711107', 'West Bengal', true, true, 'india_post_import'),
  ('711108', 'West Bengal', true, true, 'india_post_import'),
  ('711109', 'West Bengal', true, true, 'india_post_import'),
  ('711110', 'West Bengal', true, true, 'india_post_import'),
  ('711111', 'West Bengal', true, true, 'india_post_import'),
  ('711112', 'West Bengal', true, true, 'india_post_import'),
  ('711113', 'West Bengal', true, true, 'india_post_import'),
  ('711114', 'West Bengal', true, true, 'india_post_import'),
  ('711115', 'West Bengal', true, true, 'india_post_import'),
  ('711201', 'West Bengal', true, true, 'india_post_import'),
  ('711202', 'West Bengal', true, true, 'india_post_import'),
  ('711203', 'West Bengal', true, true, 'india_post_import'),
  ('711204', 'West Bengal', true, true, 'india_post_import'),
  ('711205', 'West Bengal', true, true, 'india_post_import'),
  ('711206', 'West Bengal', true, true, 'india_post_import'),
  ('711225', 'West Bengal', true, true, 'india_post_import'),
  ('711226', 'West Bengal', true, true, 'india_post_import'),
  ('711227', 'West Bengal', true, true, 'india_post_import'),
  ('711301', 'West Bengal', true, true, 'india_post_import'),
  ('711302', 'West Bengal', true, true, 'india_post_import'),
  ('711303', 'West Bengal', true, true, 'india_post_import'),
  ('711304', 'West Bengal', true, true, 'india_post_import'),
  ('711305', 'West Bengal', true, true, 'india_post_import'),
  ('711306', 'West Bengal', true, true, 'india_post_import'),
  ('711307', 'West Bengal', true, true, 'india_post_import'),
  ('711308', 'West Bengal', true, true, 'india_post_import'),
  ('711309', 'West Bengal', true, true, 'india_post_import'),
  ('711310', 'West Bengal', true, true, 'india_post_import'),
  ('711312', 'West Bengal', true, true, 'india_post_import'),
  ('711313', 'West Bengal', true, true, 'india_post_import'),
  ('711314', 'West Bengal', true, true, 'india_post_import'),
  ('711315', 'West Bengal', true, true, 'india_post_import'),
  ('711316', 'West Bengal', true, true, 'india_post_import'),
  ('711317', 'West Bengal', true, true, 'india_post_import'),
  ('711322', 'West Bengal', true, true, 'india_post_import'),
  ('711331', 'West Bengal', true, true, 'india_post_import'),
  ('711401', 'West Bengal', true, true, 'india_post_import')
on conflict (pincode) do nothing;