-- =====================================================================
-- Jayvi Foods — Pincode seed, file 10 of 21: pincodes rows 7721-8685
-- Run supabase_seed_pincodes_01_states.sql FIRST. Files 02-21 can then
-- run in any order (each is independent, uses ON CONFLICT DO NOTHING —
-- safe to re-run this specific file if it fails partway).
-- This file: 965 rows.
-- =====================================================================

insert into public.pincodes (pincode, state, serviceable, active, source) values
  ('686670', 'Kerala', true, true, 'india_post_import'),
  ('686671', 'Kerala', true, true, 'india_post_import'),
  ('686672', 'Kerala', true, true, 'india_post_import'),
  ('686673', 'Kerala', true, true, 'india_post_import'),
  ('686681', 'Kerala', true, true, 'india_post_import'),
  ('686691', 'Kerala', true, true, 'india_post_import'),
  ('686692', 'Kerala', true, true, 'india_post_import'),
  ('686693', 'Kerala', true, true, 'india_post_import'),
  ('688001', 'Kerala', true, true, 'india_post_import'),
  ('688002', 'Kerala', true, true, 'india_post_import'),
  ('688003', 'Kerala', true, true, 'india_post_import'),
  ('688004', 'Kerala', true, true, 'india_post_import'),
  ('688005', 'Kerala', true, true, 'india_post_import'),
  ('688006', 'Kerala', true, true, 'india_post_import'),
  ('688007', 'Kerala', true, true, 'india_post_import'),
  ('688008', 'Kerala', true, true, 'india_post_import'),
  ('688009', 'Kerala', true, true, 'india_post_import'),
  ('688011', 'Kerala', true, true, 'india_post_import'),
  ('688012', 'Kerala', true, true, 'india_post_import'),
  ('688013', 'Kerala', true, true, 'india_post_import'),
  ('688014', 'Kerala', true, true, 'india_post_import'),
  ('688501', 'Kerala', true, true, 'india_post_import'),
  ('688502', 'Kerala', true, true, 'india_post_import'),
  ('688503', 'Kerala', true, true, 'india_post_import'),
  ('688504', 'Kerala', true, true, 'india_post_import'),
  ('688505', 'Kerala', true, true, 'india_post_import'),
  ('688506', 'Kerala', true, true, 'india_post_import'),
  ('688521', 'Kerala', true, true, 'india_post_import'),
  ('688522', 'Kerala', true, true, 'india_post_import'),
  ('688523', 'Kerala', true, true, 'india_post_import'),
  ('688524', 'Kerala', true, true, 'india_post_import'),
  ('688525', 'Kerala', true, true, 'india_post_import'),
  ('688526', 'Kerala', true, true, 'india_post_import'),
  ('688527', 'Kerala', true, true, 'india_post_import'),
  ('688528', 'Kerala', true, true, 'india_post_import'),
  ('688529', 'Kerala', true, true, 'india_post_import'),
  ('688530', 'Kerala', true, true, 'india_post_import'),
  ('688531', 'Kerala', true, true, 'india_post_import'),
  ('688532', 'Kerala', true, true, 'india_post_import'),
  ('688533', 'Kerala', true, true, 'india_post_import'),
  ('688534', 'Kerala', true, true, 'india_post_import'),
  ('688535', 'Kerala', true, true, 'india_post_import'),
  ('688536', 'Kerala', true, true, 'india_post_import'),
  ('688537', 'Kerala', true, true, 'india_post_import'),
  ('688538', 'Kerala', true, true, 'india_post_import'),
  ('688539', 'Kerala', true, true, 'india_post_import'),
  ('688540', 'Kerala', true, true, 'india_post_import'),
  ('688541', 'Kerala', true, true, 'india_post_import'),
  ('688555', 'Kerala', true, true, 'india_post_import'),
  ('688561', 'Kerala', true, true, 'india_post_import'),
  ('688562', 'Kerala', true, true, 'india_post_import'),
  ('688570', 'Kerala', true, true, 'india_post_import'),
  ('688582', 'Kerala', true, true, 'india_post_import'),
  ('689101', 'Kerala', true, true, 'india_post_import'),
  ('689102', 'Kerala', true, true, 'india_post_import'),
  ('689103', 'Kerala', true, true, 'india_post_import'),
  ('689104', 'Kerala', true, true, 'india_post_import'),
  ('689105', 'Kerala', true, true, 'india_post_import'),
  ('689106', 'Kerala', true, true, 'india_post_import'),
  ('689107', 'Kerala', true, true, 'india_post_import'),
  ('689108', 'Kerala', true, true, 'india_post_import'),
  ('689109', 'Kerala', true, true, 'india_post_import'),
  ('689110', 'Kerala', true, true, 'india_post_import'),
  ('689111', 'Kerala', true, true, 'india_post_import'),
  ('689112', 'Kerala', true, true, 'india_post_import'),
  ('689113', 'Kerala', true, true, 'india_post_import'),
  ('689115', 'Kerala', true, true, 'india_post_import'),
  ('689121', 'Kerala', true, true, 'india_post_import'),
  ('689122', 'Kerala', true, true, 'india_post_import'),
  ('689123', 'Kerala', true, true, 'india_post_import'),
  ('689124', 'Kerala', true, true, 'india_post_import'),
  ('689126', 'Kerala', true, true, 'india_post_import'),
  ('689501', 'Kerala', true, true, 'india_post_import'),
  ('689502', 'Kerala', true, true, 'india_post_import'),
  ('689503', 'Kerala', true, true, 'india_post_import'),
  ('689504', 'Kerala', true, true, 'india_post_import'),
  ('689505', 'Kerala', true, true, 'india_post_import'),
  ('689506', 'Kerala', true, true, 'india_post_import'),
  ('689507', 'Kerala', true, true, 'india_post_import'),
  ('689508', 'Kerala', true, true, 'india_post_import'),
  ('689509', 'Kerala', true, true, 'india_post_import'),
  ('689510', 'Kerala', true, true, 'india_post_import'),
  ('689511', 'Kerala', true, true, 'india_post_import'),
  ('689512', 'Kerala', true, true, 'india_post_import'),
  ('689513', 'Kerala', true, true, 'india_post_import'),
  ('689514', 'Kerala', true, true, 'india_post_import'),
  ('689515', 'Kerala', true, true, 'india_post_import'),
  ('689520', 'Kerala', true, true, 'india_post_import'),
  ('689521', 'Kerala', true, true, 'india_post_import'),
  ('689531', 'Kerala', true, true, 'india_post_import'),
  ('689532', 'Kerala', true, true, 'india_post_import'),
  ('689533', 'Kerala', true, true, 'india_post_import'),
  ('689541', 'Kerala', true, true, 'india_post_import'),
  ('689542', 'Kerala', true, true, 'india_post_import'),
  ('689543', 'Kerala', true, true, 'india_post_import'),
  ('689544', 'Kerala', true, true, 'india_post_import'),
  ('689545', 'Kerala', true, true, 'india_post_import'),
  ('689546', 'Kerala', true, true, 'india_post_import'),
  ('689547', 'Kerala', true, true, 'india_post_import'),
  ('689548', 'Kerala', true, true, 'india_post_import'),
  ('689549', 'Kerala', true, true, 'india_post_import'),
  ('689550', 'Kerala', true, true, 'india_post_import'),
  ('689551', 'Kerala', true, true, 'india_post_import'),
  ('689571', 'Kerala', true, true, 'india_post_import'),
  ('689572', 'Kerala', true, true, 'india_post_import'),
  ('689573', 'Kerala', true, true, 'india_post_import'),
  ('689574', 'Kerala', true, true, 'india_post_import'),
  ('689581', 'Kerala', true, true, 'india_post_import'),
  ('689582', 'Kerala', true, true, 'india_post_import'),
  ('689583', 'Kerala', true, true, 'india_post_import'),
  ('689584', 'Kerala', true, true, 'india_post_import'),
  ('689585', 'Kerala', true, true, 'india_post_import'),
  ('689586', 'Kerala', true, true, 'india_post_import'),
  ('689587', 'Kerala', true, true, 'india_post_import'),
  ('689588', 'Kerala', true, true, 'india_post_import'),
  ('689589', 'Kerala', true, true, 'india_post_import'),
  ('689590', 'Kerala', true, true, 'india_post_import'),
  ('689591', 'Kerala', true, true, 'india_post_import'),
  ('689592', 'Kerala', true, true, 'india_post_import'),
  ('689594', 'Kerala', true, true, 'india_post_import'),
  ('689595', 'Kerala', true, true, 'india_post_import'),
  ('689597', 'Kerala', true, true, 'india_post_import'),
  ('689602', 'Kerala', true, true, 'india_post_import'),
  ('689611', 'Kerala', true, true, 'india_post_import'),
  ('689612', 'Kerala', true, true, 'india_post_import'),
  ('689613', 'Kerala', true, true, 'india_post_import'),
  ('689614', 'Kerala', true, true, 'india_post_import'),
  ('689615', 'Kerala', true, true, 'india_post_import'),
  ('689621', 'Kerala', true, true, 'india_post_import'),
  ('689622', 'Kerala', true, true, 'india_post_import'),
  ('689623', 'Kerala', true, true, 'india_post_import'),
  ('689624', 'Kerala', true, true, 'india_post_import'),
  ('689625', 'Kerala', true, true, 'india_post_import'),
  ('689626', 'Kerala', true, true, 'india_post_import'),
  ('689627', 'Kerala', true, true, 'india_post_import'),
  ('689641', 'Kerala', true, true, 'india_post_import'),
  ('689642', 'Kerala', true, true, 'india_post_import'),
  ('689643', 'Kerala', true, true, 'india_post_import'),
  ('689644', 'Kerala', true, true, 'india_post_import'),
  ('689645', 'Kerala', true, true, 'india_post_import'),
  ('689646', 'Kerala', true, true, 'india_post_import'),
  ('689647', 'Kerala', true, true, 'india_post_import'),
  ('689648', 'Kerala', true, true, 'india_post_import'),
  ('689649', 'Kerala', true, true, 'india_post_import'),
  ('689650', 'Kerala', true, true, 'india_post_import'),
  ('689652', 'Kerala', true, true, 'india_post_import'),
  ('689653', 'Kerala', true, true, 'india_post_import'),
  ('689654', 'Kerala', true, true, 'india_post_import'),
  ('689656', 'Kerala', true, true, 'india_post_import'),
  ('689661', 'Kerala', true, true, 'india_post_import'),
  ('689662', 'Kerala', true, true, 'india_post_import'),
  ('689663', 'Kerala', true, true, 'india_post_import'),
  ('689664', 'Kerala', true, true, 'india_post_import'),
  ('689666', 'Kerala', true, true, 'india_post_import'),
  ('689667', 'Kerala', true, true, 'india_post_import'),
  ('689668', 'Kerala', true, true, 'india_post_import'),
  ('689671', 'Kerala', true, true, 'india_post_import'),
  ('689672', 'Kerala', true, true, 'india_post_import'),
  ('689673', 'Kerala', true, true, 'india_post_import'),
  ('689674', 'Kerala', true, true, 'india_post_import'),
  ('689675', 'Kerala', true, true, 'india_post_import'),
  ('689676', 'Kerala', true, true, 'india_post_import'),
  ('689677', 'Kerala', true, true, 'india_post_import'),
  ('689678', 'Kerala', true, true, 'india_post_import'),
  ('689691', 'Kerala', true, true, 'india_post_import'),
  ('689692', 'Kerala', true, true, 'india_post_import'),
  ('689693', 'Kerala', true, true, 'india_post_import'),
  ('689694', 'Kerala', true, true, 'india_post_import'),
  ('689695', 'Kerala', true, true, 'india_post_import'),
  ('689696', 'Kerala', true, true, 'india_post_import'),
  ('689698', 'Kerala', true, true, 'india_post_import'),
  ('689699', 'Kerala', true, true, 'india_post_import'),
  ('689711', 'Kerala', true, true, 'india_post_import'),
  ('689713', 'Kerala', true, true, 'india_post_import'),
  ('690101', 'Kerala', true, true, 'india_post_import'),
  ('690102', 'Kerala', true, true, 'india_post_import'),
  ('690103', 'Kerala', true, true, 'india_post_import'),
  ('690104', 'Kerala', true, true, 'india_post_import'),
  ('690105', 'Kerala', true, true, 'india_post_import'),
  ('690106', 'Kerala', true, true, 'india_post_import'),
  ('690107', 'Kerala', true, true, 'india_post_import'),
  ('690108', 'Kerala', true, true, 'india_post_import'),
  ('690110', 'Kerala', true, true, 'india_post_import'),
  ('690501', 'Kerala', true, true, 'india_post_import'),
  ('690502', 'Kerala', true, true, 'india_post_import'),
  ('690503', 'Kerala', true, true, 'india_post_import'),
  ('690504', 'Kerala', true, true, 'india_post_import'),
  ('690505', 'Kerala', true, true, 'india_post_import'),
  ('690506', 'Kerala', true, true, 'india_post_import'),
  ('690507', 'Kerala', true, true, 'india_post_import'),
  ('690508', 'Kerala', true, true, 'india_post_import'),
  ('690509', 'Kerala', true, true, 'india_post_import'),
  ('690510', 'Kerala', true, true, 'india_post_import'),
  ('690511', 'Kerala', true, true, 'india_post_import'),
  ('690512', 'Kerala', true, true, 'india_post_import'),
  ('690513', 'Kerala', true, true, 'india_post_import'),
  ('690514', 'Kerala', true, true, 'india_post_import'),
  ('690515', 'Kerala', true, true, 'india_post_import'),
  ('690516', 'Kerala', true, true, 'india_post_import'),
  ('690517', 'Kerala', true, true, 'india_post_import'),
  ('690518', 'Kerala', true, true, 'india_post_import'),
  ('690519', 'Kerala', true, true, 'india_post_import'),
  ('690520', 'Kerala', true, true, 'india_post_import'),
  ('690521', 'Kerala', true, true, 'india_post_import'),
  ('690522', 'Kerala', true, true, 'india_post_import'),
  ('690523', 'Kerala', true, true, 'india_post_import'),
  ('690524', 'Kerala', true, true, 'india_post_import'),
  ('690525', 'Kerala', true, true, 'india_post_import'),
  ('690526', 'Kerala', true, true, 'india_post_import'),
  ('690527', 'Kerala', true, true, 'india_post_import'),
  ('690528', 'Kerala', true, true, 'india_post_import'),
  ('690529', 'Kerala', true, true, 'india_post_import'),
  ('690530', 'Kerala', true, true, 'india_post_import'),
  ('690531', 'Kerala', true, true, 'india_post_import'),
  ('690532', 'Kerala', true, true, 'india_post_import'),
  ('690533', 'Kerala', true, true, 'india_post_import'),
  ('690534', 'Kerala', true, true, 'india_post_import'),
  ('690535', 'Kerala', true, true, 'india_post_import'),
  ('690536', 'Kerala', true, true, 'india_post_import'),
  ('690537', 'Kerala', true, true, 'india_post_import'),
  ('690538', 'Kerala', true, true, 'india_post_import'),
  ('690539', 'Kerala', true, true, 'india_post_import'),
  ('690540', 'Kerala', true, true, 'india_post_import'),
  ('690542', 'Kerala', true, true, 'india_post_import'),
  ('690544', 'Kerala', true, true, 'india_post_import'),
  ('690546', 'Kerala', true, true, 'india_post_import'),
  ('690547', 'Kerala', true, true, 'india_post_import'),
  ('690548', 'Kerala', true, true, 'india_post_import'),
  ('690558', 'Kerala', true, true, 'india_post_import'),
  ('690559', 'Kerala', true, true, 'india_post_import'),
  ('690561', 'Kerala', true, true, 'india_post_import'),
  ('690571', 'Kerala', true, true, 'india_post_import'),
  ('690572', 'Kerala', true, true, 'india_post_import'),
  ('690573', 'Kerala', true, true, 'india_post_import'),
  ('690574', 'Kerala', true, true, 'india_post_import'),
  ('691001', 'Kerala', true, true, 'india_post_import'),
  ('691002', 'Kerala', true, true, 'india_post_import'),
  ('691003', 'Kerala', true, true, 'india_post_import'),
  ('691004', 'Kerala', true, true, 'india_post_import'),
  ('691005', 'Kerala', true, true, 'india_post_import'),
  ('691006', 'Kerala', true, true, 'india_post_import'),
  ('691007', 'Kerala', true, true, 'india_post_import'),
  ('691008', 'Kerala', true, true, 'india_post_import'),
  ('691009', 'Kerala', true, true, 'india_post_import'),
  ('691010', 'Kerala', true, true, 'india_post_import'),
  ('691011', 'Kerala', true, true, 'india_post_import'),
  ('691012', 'Kerala', true, true, 'india_post_import'),
  ('691013', 'Kerala', true, true, 'india_post_import'),
  ('691014', 'Kerala', true, true, 'india_post_import'),
  ('691015', 'Kerala', true, true, 'india_post_import'),
  ('691016', 'Kerala', true, true, 'india_post_import'),
  ('691019', 'Kerala', true, true, 'india_post_import'),
  ('691020', 'Kerala', true, true, 'india_post_import'),
  ('691021', 'Kerala', true, true, 'india_post_import'),
  ('691301', 'Kerala', true, true, 'india_post_import'),
  ('691302', 'Kerala', true, true, 'india_post_import'),
  ('691303', 'Kerala', true, true, 'india_post_import'),
  ('691304', 'Kerala', true, true, 'india_post_import'),
  ('691305', 'Kerala', true, true, 'india_post_import'),
  ('691306', 'Kerala', true, true, 'india_post_import'),
  ('691307', 'Kerala', true, true, 'india_post_import'),
  ('691308', 'Kerala', true, true, 'india_post_import'),
  ('691309', 'Kerala', true, true, 'india_post_import'),
  ('691310', 'Kerala', true, true, 'india_post_import'),
  ('691311', 'Kerala', true, true, 'india_post_import'),
  ('691312', 'Kerala', true, true, 'india_post_import'),
  ('691319', 'Kerala', true, true, 'india_post_import'),
  ('691322', 'Kerala', true, true, 'india_post_import'),
  ('691331', 'Kerala', true, true, 'india_post_import'),
  ('691332', 'Kerala', true, true, 'india_post_import'),
  ('691333', 'Kerala', true, true, 'india_post_import'),
  ('691334', 'Kerala', true, true, 'india_post_import'),
  ('691500', 'Kerala', true, true, 'india_post_import'),
  ('691501', 'Kerala', true, true, 'india_post_import'),
  ('691502', 'Kerala', true, true, 'india_post_import'),
  ('691503', 'Kerala', true, true, 'india_post_import'),
  ('691504', 'Kerala', true, true, 'india_post_import'),
  ('691505', 'Kerala', true, true, 'india_post_import'),
  ('691506', 'Kerala', true, true, 'india_post_import'),
  ('691507', 'Kerala', true, true, 'india_post_import'),
  ('691508', 'Kerala', true, true, 'india_post_import'),
  ('691509', 'Kerala', true, true, 'india_post_import'),
  ('691510', 'Kerala', true, true, 'india_post_import'),
  ('691511', 'Kerala', true, true, 'india_post_import'),
  ('691512', 'Kerala', true, true, 'india_post_import'),
  ('691515', 'Kerala', true, true, 'india_post_import'),
  ('691516', 'Kerala', true, true, 'india_post_import'),
  ('691520', 'Kerala', true, true, 'india_post_import'),
  ('691521', 'Kerala', true, true, 'india_post_import'),
  ('691522', 'Kerala', true, true, 'india_post_import'),
  ('691523', 'Kerala', true, true, 'india_post_import'),
  ('691524', 'Kerala', true, true, 'india_post_import'),
  ('691525', 'Kerala', true, true, 'india_post_import'),
  ('691526', 'Kerala', true, true, 'india_post_import'),
  ('691527', 'Kerala', true, true, 'india_post_import'),
  ('691530', 'Kerala', true, true, 'india_post_import'),
  ('691531', 'Kerala', true, true, 'india_post_import'),
  ('691532', 'Kerala', true, true, 'india_post_import'),
  ('691533', 'Kerala', true, true, 'india_post_import'),
  ('691534', 'Kerala', true, true, 'india_post_import'),
  ('691535', 'Kerala', true, true, 'india_post_import'),
  ('691536', 'Kerala', true, true, 'india_post_import'),
  ('691537', 'Kerala', true, true, 'india_post_import'),
  ('691538', 'Kerala', true, true, 'india_post_import'),
  ('691540', 'Kerala', true, true, 'india_post_import'),
  ('691541', 'Kerala', true, true, 'india_post_import'),
  ('691543', 'Kerala', true, true, 'india_post_import'),
  ('691551', 'Kerala', true, true, 'india_post_import'),
  ('691552', 'Kerala', true, true, 'india_post_import'),
  ('691553', 'Kerala', true, true, 'india_post_import'),
  ('691554', 'Kerala', true, true, 'india_post_import'),
  ('691555', 'Kerala', true, true, 'india_post_import'),
  ('691556', 'Kerala', true, true, 'india_post_import'),
  ('691557', 'Kerala', true, true, 'india_post_import'),
  ('691559', 'Kerala', true, true, 'india_post_import'),
  ('691560', 'Kerala', true, true, 'india_post_import'),
  ('691566', 'Kerala', true, true, 'india_post_import'),
  ('691571', 'Kerala', true, true, 'india_post_import'),
  ('691572', 'Kerala', true, true, 'india_post_import'),
  ('691573', 'Kerala', true, true, 'india_post_import'),
  ('691574', 'Kerala', true, true, 'india_post_import'),
  ('691576', 'Kerala', true, true, 'india_post_import'),
  ('691577', 'Kerala', true, true, 'india_post_import'),
  ('691578', 'Kerala', true, true, 'india_post_import'),
  ('691579', 'Kerala', true, true, 'india_post_import'),
  ('691581', 'Kerala', true, true, 'india_post_import'),
  ('691582', 'Kerala', true, true, 'india_post_import'),
  ('691583', 'Kerala', true, true, 'india_post_import'),
  ('691584', 'Kerala', true, true, 'india_post_import'),
  ('691585', 'Kerala', true, true, 'india_post_import'),
  ('691589', 'Kerala', true, true, 'india_post_import'),
  ('691590', 'Kerala', true, true, 'india_post_import'),
  ('691601', 'Kerala', true, true, 'india_post_import'),
  ('691602', 'Kerala', true, true, 'india_post_import'),
  ('695001', 'Kerala', true, true, 'india_post_import'),
  ('695002', 'Kerala', true, true, 'india_post_import'),
  ('695003', 'Kerala', true, true, 'india_post_import'),
  ('695004', 'Kerala', true, true, 'india_post_import'),
  ('695005', 'Kerala', true, true, 'india_post_import'),
  ('695006', 'Kerala', true, true, 'india_post_import'),
  ('695007', 'Kerala', true, true, 'india_post_import'),
  ('695008', 'Kerala', true, true, 'india_post_import'),
  ('695009', 'Kerala', true, true, 'india_post_import'),
  ('695010', 'Kerala', true, true, 'india_post_import'),
  ('695011', 'Kerala', true, true, 'india_post_import'),
  ('695012', 'Kerala', true, true, 'india_post_import'),
  ('695013', 'Kerala', true, true, 'india_post_import'),
  ('695014', 'Kerala', true, true, 'india_post_import'),
  ('695015', 'Kerala', true, true, 'india_post_import'),
  ('695016', 'Kerala', true, true, 'india_post_import'),
  ('695017', 'Kerala', true, true, 'india_post_import'),
  ('695018', 'Kerala', true, true, 'india_post_import'),
  ('695019', 'Kerala', true, true, 'india_post_import'),
  ('695020', 'Kerala', true, true, 'india_post_import'),
  ('695021', 'Kerala', true, true, 'india_post_import'),
  ('695022', 'Kerala', true, true, 'india_post_import'),
  ('695023', 'Kerala', true, true, 'india_post_import'),
  ('695024', 'Kerala', true, true, 'india_post_import'),
  ('695025', 'Kerala', true, true, 'india_post_import'),
  ('695026', 'Kerala', true, true, 'india_post_import'),
  ('695027', 'Kerala', true, true, 'india_post_import'),
  ('695028', 'Kerala', true, true, 'india_post_import'),
  ('695029', 'Kerala', true, true, 'india_post_import'),
  ('695030', 'Kerala', true, true, 'india_post_import'),
  ('695032', 'Kerala', true, true, 'india_post_import'),
  ('695033', 'Kerala', true, true, 'india_post_import'),
  ('695034', 'Kerala', true, true, 'india_post_import'),
  ('695035', 'Kerala', true, true, 'india_post_import'),
  ('695036', 'Kerala', true, true, 'india_post_import'),
  ('695038', 'Kerala', true, true, 'india_post_import'),
  ('695040', 'Kerala', true, true, 'india_post_import'),
  ('695042', 'Kerala', true, true, 'india_post_import'),
  ('695043', 'Kerala', true, true, 'india_post_import'),
  ('695051', 'Kerala', true, true, 'india_post_import'),
  ('695099', 'Kerala', true, true, 'india_post_import'),
  ('695101', 'Kerala', true, true, 'india_post_import'),
  ('695102', 'Kerala', true, true, 'india_post_import'),
  ('695103', 'Kerala', true, true, 'india_post_import'),
  ('695104', 'Kerala', true, true, 'india_post_import'),
  ('695121', 'Kerala', true, true, 'india_post_import'),
  ('695122', 'Kerala', true, true, 'india_post_import'),
  ('695123', 'Kerala', true, true, 'india_post_import'),
  ('695124', 'Kerala', true, true, 'india_post_import'),
  ('695125', 'Kerala', true, true, 'india_post_import'),
  ('695126', 'Kerala', true, true, 'india_post_import'),
  ('695132', 'Kerala', true, true, 'india_post_import'),
  ('695133', 'Kerala', true, true, 'india_post_import'),
  ('695134', 'Kerala', true, true, 'india_post_import'),
  ('695141', 'Kerala', true, true, 'india_post_import'),
  ('695142', 'Kerala', true, true, 'india_post_import'),
  ('695143', 'Kerala', true, true, 'india_post_import'),
  ('695144', 'Kerala', true, true, 'india_post_import'),
  ('695145', 'Kerala', true, true, 'india_post_import'),
  ('695146', 'Kerala', true, true, 'india_post_import'),
  ('695301', 'Kerala', true, true, 'india_post_import'),
  ('695302', 'Kerala', true, true, 'india_post_import'),
  ('695303', 'Kerala', true, true, 'india_post_import'),
  ('695304', 'Kerala', true, true, 'india_post_import'),
  ('695305', 'Kerala', true, true, 'india_post_import'),
  ('695306', 'Kerala', true, true, 'india_post_import'),
  ('695307', 'Kerala', true, true, 'india_post_import'),
  ('695308', 'Kerala', true, true, 'india_post_import'),
  ('695309', 'Kerala', true, true, 'india_post_import'),
  ('695310', 'Kerala', true, true, 'india_post_import'),
  ('695311', 'Kerala', true, true, 'india_post_import'),
  ('695312', 'Kerala', true, true, 'india_post_import'),
  ('695313', 'Kerala', true, true, 'india_post_import'),
  ('695316', 'Kerala', true, true, 'india_post_import'),
  ('695317', 'Kerala', true, true, 'india_post_import'),
  ('695318', 'Kerala', true, true, 'india_post_import'),
  ('695501', 'Kerala', true, true, 'india_post_import'),
  ('695502', 'Kerala', true, true, 'india_post_import'),
  ('695503', 'Kerala', true, true, 'india_post_import'),
  ('695504', 'Kerala', true, true, 'india_post_import'),
  ('695505', 'Kerala', true, true, 'india_post_import'),
  ('695506', 'Kerala', true, true, 'india_post_import'),
  ('695507', 'Kerala', true, true, 'india_post_import'),
  ('695508', 'Kerala', true, true, 'india_post_import'),
  ('695512', 'Kerala', true, true, 'india_post_import'),
  ('695513', 'Kerala', true, true, 'india_post_import'),
  ('695521', 'Kerala', true, true, 'india_post_import'),
  ('695522', 'Kerala', true, true, 'india_post_import'),
  ('695523', 'Kerala', true, true, 'india_post_import'),
  ('695524', 'Kerala', true, true, 'india_post_import'),
  ('695525', 'Kerala', true, true, 'india_post_import'),
  ('695526', 'Kerala', true, true, 'india_post_import'),
  ('695527', 'Kerala', true, true, 'india_post_import'),
  ('695528', 'Kerala', true, true, 'india_post_import'),
  ('695541', 'Kerala', true, true, 'india_post_import'),
  ('695542', 'Kerala', true, true, 'india_post_import'),
  ('695543', 'Kerala', true, true, 'india_post_import'),
  ('695547', 'Kerala', true, true, 'india_post_import'),
  ('695551', 'Kerala', true, true, 'india_post_import'),
  ('695561', 'Kerala', true, true, 'india_post_import'),
  ('695562', 'Kerala', true, true, 'india_post_import'),
  ('695563', 'Kerala', true, true, 'india_post_import'),
  ('695564', 'Kerala', true, true, 'india_post_import'),
  ('695568', 'Kerala', true, true, 'india_post_import'),
  ('695570', 'Kerala', true, true, 'india_post_import'),
  ('695571', 'Kerala', true, true, 'india_post_import'),
  ('695572', 'Kerala', true, true, 'india_post_import'),
  ('695573', 'Kerala', true, true, 'india_post_import'),
  ('695574', 'Kerala', true, true, 'india_post_import'),
  ('695575', 'Kerala', true, true, 'india_post_import'),
  ('695581', 'Kerala', true, true, 'india_post_import'),
  ('695582', 'Kerala', true, true, 'india_post_import'),
  ('695583', 'Kerala', true, true, 'india_post_import'),
  ('695584', 'Kerala', true, true, 'india_post_import'),
  ('695585', 'Kerala', true, true, 'india_post_import'),
  ('695586', 'Kerala', true, true, 'india_post_import'),
  ('695587', 'Kerala', true, true, 'india_post_import'),
  ('695588', 'Kerala', true, true, 'india_post_import'),
  ('695589', 'Kerala', true, true, 'india_post_import'),
  ('695601', 'Kerala', true, true, 'india_post_import'),
  ('695602', 'Kerala', true, true, 'india_post_import'),
  ('695603', 'Kerala', true, true, 'india_post_import'),
  ('695604', 'Kerala', true, true, 'india_post_import'),
  ('695605', 'Kerala', true, true, 'india_post_import'),
  ('695606', 'Kerala', true, true, 'india_post_import'),
  ('695607', 'Kerala', true, true, 'india_post_import'),
  ('695608', 'Kerala', true, true, 'india_post_import'),
  ('695609', 'Kerala', true, true, 'india_post_import'),
  ('695610', 'Kerala', true, true, 'india_post_import'),
  ('695611', 'Kerala', true, true, 'india_post_import'),
  ('695612', 'Kerala', true, true, 'india_post_import'),
  ('695614', 'Kerala', true, true, 'india_post_import'),
  ('695615', 'Kerala', true, true, 'india_post_import'),
  ('450001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450051', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450112', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450117', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450119', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450554', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('450991', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451224', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451225', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451228', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451442', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451449', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451556', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451660', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451666', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('451881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452006', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452007', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452009', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452010', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452011', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452012', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452013', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452014', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452015', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452016', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452018', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('452020', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453112', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453552', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453555', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453556', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('453771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454010', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454449', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454552', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454660', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454773', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454774', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('454775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455223', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455227', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455336', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455339', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('455459', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456006', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456010', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456222', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456224', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456313', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456443', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456550', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456664', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456668', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('456776', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457119', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457222', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457333', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457336', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457339', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457340', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457550', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457555', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457772', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457773', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457777', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457779', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457882', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457885', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457887', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457888', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('457993', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458228', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458330', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458336', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458339', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458389', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458468', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458470', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458553', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458556', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458558', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458664', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458667', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458669', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458778', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458880', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458883', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458888', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458895', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('458990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460004', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460225', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460330', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460443', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460449', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460553', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460554', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460557', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460663', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460666', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('460668', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461122', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461223', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461228', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461668', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('461990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462004', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462008', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462010', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462011', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462016', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462020', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462022', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462023', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462024', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462026', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462027', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462030', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462031', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462033', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462036', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462037', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462038', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462039', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462040', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462041', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462042', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462043', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462044', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462045', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462046', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462047', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462066', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462100', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462101', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('462120', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('463106', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('463111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464224', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464228', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464240', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464258', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464334', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464570', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464573', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464651', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464668', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464671', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464672', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464774', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464776', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464884', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464886', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464986', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('464993', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465106', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465223', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465227', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465230', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465333', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465339', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465449', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465550', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465667', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465669', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465674', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465677', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465679', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465680', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465683', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465685', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465687', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465689', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465691', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465693', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('465697', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466120', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466125', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466448', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466554', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466651', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('466665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470004', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470021', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470051', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470117', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470119', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470120', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470124', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470125', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470223', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470227', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470228', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470229', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470232', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470235', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470339', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470340', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470442', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470663', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470664', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470666', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470669', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470672', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470673', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470675', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470772', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470880', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('470881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471101', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471105', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471201', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471301', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471311', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471313', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471315', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471318', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471405', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471408', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471411', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471501', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471510', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471515', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471516', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471525', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471606', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('471625', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472010', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472101', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472246', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472336', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472339', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472442', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('472447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473101', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473105', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473112', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473222', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473249', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473287', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473330', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473443', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473444', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473585', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473638', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473660', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473662', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473670', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473774', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473781', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473793', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473865', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473880', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473885', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('473995', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474004', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474006', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474007', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474008', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474009', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474010', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474011', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474012', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474015', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('474020', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475330', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475336', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475671', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475673', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475675', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475682', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475685', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('475686', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476134', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476219', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476224', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476228', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476229', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476335', 'Madhya Pradesh', true, true, 'india_post_import')
on conflict (pincode) do nothing;