-- =====================================================================
-- Jayvi Foods — Pincode seed, file 6 of 21: pincodes rows 3861-4825
-- Run supabase_seed_pincodes_01_states.sql FIRST. Files 02-21 can then
-- run in any order (each is independent, uses ON CONFLICT DO NOTHING —
-- safe to re-run this specific file if it fails partway).
-- This file: 965 rows.
-- =====================================================================

insert into public.pincodes (pincode, state, serviceable, active, source) values
  ('393010', 'Gujarat', true, true, 'india_post_import'),
  ('393017', 'Gujarat', true, true, 'india_post_import'),
  ('393020', 'Gujarat', true, true, 'india_post_import'),
  ('393025', 'Gujarat', true, true, 'india_post_import'),
  ('393030', 'Gujarat', true, true, 'india_post_import'),
  ('393040', 'Gujarat', true, true, 'india_post_import'),
  ('393041', 'Gujarat', true, true, 'india_post_import'),
  ('393050', 'Gujarat', true, true, 'india_post_import'),
  ('393105', 'Gujarat', true, true, 'india_post_import'),
  ('393110', 'Gujarat', true, true, 'india_post_import'),
  ('393115', 'Gujarat', true, true, 'india_post_import'),
  ('393120', 'Gujarat', true, true, 'india_post_import'),
  ('393125', 'Gujarat', true, true, 'india_post_import'),
  ('393130', 'Gujarat', true, true, 'india_post_import'),
  ('393135', 'Gujarat', true, true, 'india_post_import'),
  ('393140', 'Gujarat', true, true, 'india_post_import'),
  ('393145', 'Gujarat', true, true, 'india_post_import'),
  ('393150', 'Gujarat', true, true, 'india_post_import'),
  ('393151', 'Gujarat', true, true, 'india_post_import'),
  ('393155', 'Gujarat', true, true, 'india_post_import'),
  ('394101', 'Gujarat', true, true, 'india_post_import'),
  ('394105', 'Gujarat', true, true, 'india_post_import'),
  ('394107', 'Gujarat', true, true, 'india_post_import'),
  ('394110', 'Gujarat', true, true, 'india_post_import'),
  ('394111', 'Gujarat', true, true, 'india_post_import'),
  ('394112', 'Gujarat', true, true, 'india_post_import'),
  ('394115', 'Gujarat', true, true, 'india_post_import'),
  ('394120', 'Gujarat', true, true, 'india_post_import'),
  ('394125', 'Gujarat', true, true, 'india_post_import'),
  ('394130', 'Gujarat', true, true, 'india_post_import'),
  ('394140', 'Gujarat', true, true, 'india_post_import'),
  ('394150', 'Gujarat', true, true, 'india_post_import'),
  ('394155', 'Gujarat', true, true, 'india_post_import'),
  ('394160', 'Gujarat', true, true, 'india_post_import'),
  ('394163', 'Gujarat', true, true, 'india_post_import'),
  ('394170', 'Gujarat', true, true, 'india_post_import'),
  ('394180', 'Gujarat', true, true, 'india_post_import'),
  ('394185', 'Gujarat', true, true, 'india_post_import'),
  ('394190', 'Gujarat', true, true, 'india_post_import'),
  ('394210', 'Gujarat', true, true, 'india_post_import'),
  ('394221', 'Gujarat', true, true, 'india_post_import'),
  ('394230', 'Gujarat', true, true, 'india_post_import'),
  ('394235', 'Gujarat', true, true, 'india_post_import'),
  ('394240', 'Gujarat', true, true, 'india_post_import'),
  ('394245', 'Gujarat', true, true, 'india_post_import'),
  ('394246', 'Gujarat', true, true, 'india_post_import'),
  ('394248', 'Gujarat', true, true, 'india_post_import'),
  ('394250', 'Gujarat', true, true, 'india_post_import'),
  ('394270', 'Gujarat', true, true, 'india_post_import'),
  ('394305', 'Gujarat', true, true, 'india_post_import'),
  ('394310', 'Gujarat', true, true, 'india_post_import'),
  ('394315', 'Gujarat', true, true, 'india_post_import'),
  ('394317', 'Gujarat', true, true, 'india_post_import'),
  ('394320', 'Gujarat', true, true, 'india_post_import'),
  ('394325', 'Gujarat', true, true, 'india_post_import'),
  ('394326', 'Gujarat', true, true, 'india_post_import'),
  ('394327', 'Gujarat', true, true, 'india_post_import'),
  ('394330', 'Gujarat', true, true, 'india_post_import'),
  ('394335', 'Gujarat', true, true, 'india_post_import'),
  ('394340', 'Gujarat', true, true, 'india_post_import'),
  ('394345', 'Gujarat', true, true, 'india_post_import'),
  ('394350', 'Gujarat', true, true, 'india_post_import'),
  ('394352', 'Gujarat', true, true, 'india_post_import'),
  ('394355', 'Gujarat', true, true, 'india_post_import'),
  ('394360', 'Gujarat', true, true, 'india_post_import'),
  ('394365', 'Gujarat', true, true, 'india_post_import'),
  ('394370', 'Gujarat', true, true, 'india_post_import'),
  ('394375', 'Gujarat', true, true, 'india_post_import'),
  ('394380', 'Gujarat', true, true, 'india_post_import'),
  ('394405', 'Gujarat', true, true, 'india_post_import'),
  ('394410', 'Gujarat', true, true, 'india_post_import'),
  ('394421', 'Gujarat', true, true, 'india_post_import'),
  ('394430', 'Gujarat', true, true, 'india_post_import'),
  ('394440', 'Gujarat', true, true, 'india_post_import'),
  ('394445', 'Gujarat', true, true, 'india_post_import'),
  ('394510', 'Gujarat', true, true, 'india_post_import'),
  ('394515', 'Gujarat', true, true, 'india_post_import'),
  ('394516', 'Gujarat', true, true, 'india_post_import'),
  ('394517', 'Gujarat', true, true, 'india_post_import'),
  ('394518', 'Gujarat', true, true, 'india_post_import'),
  ('394520', 'Gujarat', true, true, 'india_post_import'),
  ('394530', 'Gujarat', true, true, 'india_post_import'),
  ('394540', 'Gujarat', true, true, 'india_post_import'),
  ('394541', 'Gujarat', true, true, 'india_post_import'),
  ('394550', 'Gujarat', true, true, 'india_post_import'),
  ('394601', 'Gujarat', true, true, 'india_post_import'),
  ('394620', 'Gujarat', true, true, 'india_post_import'),
  ('394630', 'Gujarat', true, true, 'india_post_import'),
  ('394633', 'Gujarat', true, true, 'india_post_import'),
  ('394635', 'Gujarat', true, true, 'india_post_import'),
  ('394640', 'Gujarat', true, true, 'india_post_import'),
  ('394641', 'Gujarat', true, true, 'india_post_import'),
  ('394650', 'Gujarat', true, true, 'india_post_import'),
  ('394651', 'Gujarat', true, true, 'india_post_import'),
  ('394652', 'Gujarat', true, true, 'india_post_import'),
  ('394655', 'Gujarat', true, true, 'india_post_import'),
  ('394660', 'Gujarat', true, true, 'india_post_import'),
  ('394670', 'Gujarat', true, true, 'india_post_import'),
  ('394680', 'Gujarat', true, true, 'india_post_import'),
  ('394690', 'Gujarat', true, true, 'india_post_import'),
  ('394710', 'Gujarat', true, true, 'india_post_import'),
  ('394715', 'Gujarat', true, true, 'india_post_import'),
  ('394716', 'Gujarat', true, true, 'india_post_import'),
  ('394720', 'Gujarat', true, true, 'india_post_import'),
  ('394730', 'Gujarat', true, true, 'india_post_import'),
  ('394810', 'Gujarat', true, true, 'india_post_import'),
  ('395001', 'Gujarat', true, true, 'india_post_import'),
  ('395002', 'Gujarat', true, true, 'india_post_import'),
  ('395003', 'Gujarat', true, true, 'india_post_import'),
  ('395004', 'Gujarat', true, true, 'india_post_import'),
  ('395005', 'Gujarat', true, true, 'india_post_import'),
  ('395006', 'Gujarat', true, true, 'india_post_import'),
  ('395007', 'Gujarat', true, true, 'india_post_import'),
  ('395008', 'Gujarat', true, true, 'india_post_import'),
  ('395009', 'Gujarat', true, true, 'india_post_import'),
  ('395010', 'Gujarat', true, true, 'india_post_import'),
  ('395011', 'Gujarat', true, true, 'india_post_import'),
  ('395012', 'Gujarat', true, true, 'india_post_import'),
  ('395013', 'Gujarat', true, true, 'india_post_import'),
  ('395017', 'Gujarat', true, true, 'india_post_import'),
  ('395023', 'Gujarat', true, true, 'india_post_import'),
  ('396001', 'Gujarat', true, true, 'india_post_import'),
  ('396002', 'Gujarat', true, true, 'india_post_import'),
  ('396007', 'Gujarat', true, true, 'india_post_import'),
  ('396020', 'Gujarat', true, true, 'india_post_import'),
  ('396030', 'Gujarat', true, true, 'india_post_import'),
  ('396035', 'Gujarat', true, true, 'india_post_import'),
  ('396040', 'Gujarat', true, true, 'india_post_import'),
  ('396045', 'Gujarat', true, true, 'india_post_import'),
  ('396050', 'Gujarat', true, true, 'india_post_import'),
  ('396051', 'Gujarat', true, true, 'india_post_import'),
  ('396055', 'Gujarat', true, true, 'india_post_import'),
  ('396060', 'Gujarat', true, true, 'india_post_import'),
  ('396065', 'Gujarat', true, true, 'india_post_import'),
  ('396067', 'Gujarat', true, true, 'india_post_import'),
  ('396105', 'Gujarat', true, true, 'india_post_import'),
  ('396110', 'Gujarat', true, true, 'india_post_import'),
  ('396115', 'Gujarat', true, true, 'india_post_import'),
  ('396120', 'Gujarat', true, true, 'india_post_import'),
  ('396125', 'Gujarat', true, true, 'india_post_import'),
  ('396126', 'Gujarat', true, true, 'india_post_import'),
  ('396130', 'Gujarat', true, true, 'india_post_import'),
  ('396135', 'Gujarat', true, true, 'india_post_import'),
  ('396140', 'Gujarat', true, true, 'india_post_import'),
  ('396145', 'Gujarat', true, true, 'india_post_import'),
  ('396150', 'Gujarat', true, true, 'india_post_import'),
  ('396155', 'Gujarat', true, true, 'india_post_import'),
  ('396165', 'Gujarat', true, true, 'india_post_import'),
  ('396170', 'Gujarat', true, true, 'india_post_import'),
  ('396171', 'Gujarat', true, true, 'india_post_import'),
  ('396180', 'Gujarat', true, true, 'india_post_import'),
  ('396185', 'Gujarat', true, true, 'india_post_import'),
  ('396191', 'Gujarat', true, true, 'india_post_import'),
  ('396193', 'Gujarat', true, true, 'india_post_import'),
  ('396195', 'Gujarat', true, true, 'india_post_import'),
  ('396210', 'Gujarat', true, true, 'india_post_import'),
  ('396215', 'Gujarat', true, true, 'india_post_import'),
  ('396220', 'Gujarat', true, true, 'india_post_import'),
  ('396230', 'Gujarat', true, true, 'india_post_import'),
  ('396235', 'Gujarat', true, true, 'india_post_import'),
  ('396240', 'Gujarat', true, true, 'india_post_import'),
  ('396310', 'Gujarat', true, true, 'india_post_import'),
  ('396321', 'Gujarat', true, true, 'india_post_import'),
  ('396325', 'Gujarat', true, true, 'india_post_import'),
  ('396350', 'Gujarat', true, true, 'india_post_import'),
  ('396360', 'Gujarat', true, true, 'india_post_import'),
  ('396370', 'Gujarat', true, true, 'india_post_import'),
  ('396375', 'Gujarat', true, true, 'india_post_import'),
  ('396380', 'Gujarat', true, true, 'india_post_import'),
  ('396385', 'Gujarat', true, true, 'india_post_import'),
  ('396403', 'Gujarat', true, true, 'india_post_import'),
  ('396406', 'Gujarat', true, true, 'india_post_import'),
  ('396409', 'Gujarat', true, true, 'india_post_import'),
  ('396412', 'Gujarat', true, true, 'india_post_import'),
  ('396415', 'Gujarat', true, true, 'india_post_import'),
  ('396418', 'Gujarat', true, true, 'india_post_import'),
  ('396421', 'Gujarat', true, true, 'india_post_import'),
  ('396424', 'Gujarat', true, true, 'india_post_import'),
  ('396427', 'Gujarat', true, true, 'india_post_import'),
  ('396430', 'Gujarat', true, true, 'india_post_import'),
  ('396433', 'Gujarat', true, true, 'india_post_import'),
  ('396436', 'Gujarat', true, true, 'india_post_import'),
  ('396439', 'Gujarat', true, true, 'india_post_import'),
  ('396440', 'Gujarat', true, true, 'india_post_import'),
  ('396445', 'Gujarat', true, true, 'india_post_import'),
  ('396450', 'Gujarat', true, true, 'india_post_import'),
  ('396460', 'Gujarat', true, true, 'india_post_import'),
  ('396463', 'Gujarat', true, true, 'india_post_import'),
  ('396466', 'Gujarat', true, true, 'india_post_import'),
  ('396469', 'Gujarat', true, true, 'india_post_import'),
  ('396472', 'Gujarat', true, true, 'india_post_import'),
  ('396475', 'Gujarat', true, true, 'india_post_import'),
  ('396510', 'Gujarat', true, true, 'india_post_import'),
  ('396521', 'Gujarat', true, true, 'india_post_import'),
  ('396530', 'Gujarat', true, true, 'india_post_import'),
  ('396540', 'Gujarat', true, true, 'india_post_import'),
  ('396560', 'Gujarat', true, true, 'india_post_import'),
  ('396570', 'Gujarat', true, true, 'india_post_import'),
  ('396580', 'Gujarat', true, true, 'india_post_import'),
  ('396590', 'Gujarat', true, true, 'india_post_import'),
  ('121001', 'Haryana', true, true, 'india_post_import'),
  ('121002', 'Haryana', true, true, 'india_post_import'),
  ('121003', 'Haryana', true, true, 'india_post_import'),
  ('121004', 'Haryana', true, true, 'india_post_import'),
  ('121005', 'Haryana', true, true, 'india_post_import'),
  ('121006', 'Haryana', true, true, 'india_post_import'),
  ('121007', 'Haryana', true, true, 'india_post_import'),
  ('121008', 'Haryana', true, true, 'india_post_import'),
  ('121009', 'Haryana', true, true, 'india_post_import'),
  ('121010', 'Haryana', true, true, 'india_post_import'),
  ('121012', 'Haryana', true, true, 'india_post_import'),
  ('121013', 'Haryana', true, true, 'india_post_import'),
  ('121014', 'Haryana', true, true, 'india_post_import'),
  ('121015', 'Haryana', true, true, 'india_post_import'),
  ('121101', 'Haryana', true, true, 'india_post_import'),
  ('121102', 'Haryana', true, true, 'india_post_import'),
  ('121103', 'Haryana', true, true, 'india_post_import'),
  ('121105', 'Haryana', true, true, 'india_post_import'),
  ('121106', 'Haryana', true, true, 'india_post_import'),
  ('121107', 'Haryana', true, true, 'india_post_import'),
  ('122001', 'Haryana', true, true, 'india_post_import'),
  ('122002', 'Haryana', true, true, 'india_post_import'),
  ('122003', 'Haryana', true, true, 'india_post_import'),
  ('122004', 'Haryana', true, true, 'india_post_import'),
  ('122005', 'Haryana', true, true, 'india_post_import'),
  ('122006', 'Haryana', true, true, 'india_post_import'),
  ('122007', 'Haryana', true, true, 'india_post_import'),
  ('122008', 'Haryana', true, true, 'india_post_import'),
  ('122009', 'Haryana', true, true, 'india_post_import'),
  ('122010', 'Haryana', true, true, 'india_post_import'),
  ('122011', 'Haryana', true, true, 'india_post_import'),
  ('122012', 'Haryana', true, true, 'india_post_import'),
  ('122015', 'Haryana', true, true, 'india_post_import'),
  ('122016', 'Haryana', true, true, 'india_post_import'),
  ('122017', 'Haryana', true, true, 'india_post_import'),
  ('122018', 'Haryana', true, true, 'india_post_import'),
  ('122051', 'Haryana', true, true, 'india_post_import'),
  ('122052', 'Haryana', true, true, 'india_post_import'),
  ('122098', 'Haryana', true, true, 'india_post_import'),
  ('122101', 'Haryana', true, true, 'india_post_import'),
  ('122102', 'Haryana', true, true, 'india_post_import'),
  ('122103', 'Haryana', true, true, 'india_post_import'),
  ('122104', 'Haryana', true, true, 'india_post_import'),
  ('122105', 'Haryana', true, true, 'india_post_import'),
  ('122107', 'Haryana', true, true, 'india_post_import'),
  ('122108', 'Haryana', true, true, 'india_post_import'),
  ('122413', 'Haryana', true, true, 'india_post_import'),
  ('122414', 'Haryana', true, true, 'india_post_import'),
  ('122502', 'Haryana', true, true, 'india_post_import'),
  ('122503', 'Haryana', true, true, 'india_post_import'),
  ('122504', 'Haryana', true, true, 'india_post_import'),
  ('122505', 'Haryana', true, true, 'india_post_import'),
  ('122506', 'Haryana', true, true, 'india_post_import'),
  ('122508', 'Haryana', true, true, 'india_post_import'),
  ('123001', 'Haryana', true, true, 'india_post_import'),
  ('123021', 'Haryana', true, true, 'india_post_import'),
  ('123023', 'Haryana', true, true, 'india_post_import'),
  ('123024', 'Haryana', true, true, 'india_post_import'),
  ('123027', 'Haryana', true, true, 'india_post_import'),
  ('123028', 'Haryana', true, true, 'india_post_import'),
  ('123029', 'Haryana', true, true, 'india_post_import'),
  ('123031', 'Haryana', true, true, 'india_post_import'),
  ('123034', 'Haryana', true, true, 'india_post_import'),
  ('123035', 'Haryana', true, true, 'india_post_import'),
  ('123101', 'Haryana', true, true, 'india_post_import'),
  ('123102', 'Haryana', true, true, 'india_post_import'),
  ('123103', 'Haryana', true, true, 'india_post_import'),
  ('123106', 'Haryana', true, true, 'india_post_import'),
  ('123110', 'Haryana', true, true, 'india_post_import'),
  ('123301', 'Haryana', true, true, 'india_post_import'),
  ('123302', 'Haryana', true, true, 'india_post_import'),
  ('123303', 'Haryana', true, true, 'india_post_import'),
  ('123401', 'Haryana', true, true, 'india_post_import'),
  ('123411', 'Haryana', true, true, 'india_post_import'),
  ('123412', 'Haryana', true, true, 'india_post_import'),
  ('123501', 'Haryana', true, true, 'india_post_import'),
  ('124001', 'Haryana', true, true, 'india_post_import'),
  ('124010', 'Haryana', true, true, 'india_post_import'),
  ('124021', 'Haryana', true, true, 'india_post_import'),
  ('124022', 'Haryana', true, true, 'india_post_import'),
  ('124102', 'Haryana', true, true, 'india_post_import'),
  ('124103', 'Haryana', true, true, 'india_post_import'),
  ('124104', 'Haryana', true, true, 'india_post_import'),
  ('124105', 'Haryana', true, true, 'india_post_import'),
  ('124106', 'Haryana', true, true, 'india_post_import'),
  ('124107', 'Haryana', true, true, 'india_post_import'),
  ('124108', 'Haryana', true, true, 'india_post_import'),
  ('124109', 'Haryana', true, true, 'india_post_import'),
  ('124111', 'Haryana', true, true, 'india_post_import'),
  ('124112', 'Haryana', true, true, 'india_post_import'),
  ('124113', 'Haryana', true, true, 'india_post_import'),
  ('124141', 'Haryana', true, true, 'india_post_import'),
  ('124142', 'Haryana', true, true, 'india_post_import'),
  ('124146', 'Haryana', true, true, 'india_post_import'),
  ('124201', 'Haryana', true, true, 'india_post_import'),
  ('124202', 'Haryana', true, true, 'india_post_import'),
  ('124303', 'Haryana', true, true, 'india_post_import'),
  ('124401', 'Haryana', true, true, 'india_post_import'),
  ('124404', 'Haryana', true, true, 'india_post_import'),
  ('124406', 'Haryana', true, true, 'india_post_import'),
  ('124411', 'Haryana', true, true, 'india_post_import'),
  ('124412', 'Haryana', true, true, 'india_post_import'),
  ('124501', 'Haryana', true, true, 'india_post_import'),
  ('124504', 'Haryana', true, true, 'india_post_import'),
  ('124505', 'Haryana', true, true, 'india_post_import'),
  ('124506', 'Haryana', true, true, 'india_post_import'),
  ('124507', 'Haryana', true, true, 'india_post_import'),
  ('124508', 'Haryana', true, true, 'india_post_import'),
  ('124513', 'Haryana', true, true, 'india_post_import'),
  ('124514', 'Haryana', true, true, 'india_post_import'),
  ('125001', 'Haryana', true, true, 'india_post_import'),
  ('125004', 'Haryana', true, true, 'india_post_import'),
  ('125005', 'Haryana', true, true, 'india_post_import'),
  ('125006', 'Haryana', true, true, 'india_post_import'),
  ('125007', 'Haryana', true, true, 'india_post_import'),
  ('125011', 'Haryana', true, true, 'india_post_import'),
  ('125033', 'Haryana', true, true, 'india_post_import'),
  ('125037', 'Haryana', true, true, 'india_post_import'),
  ('125038', 'Haryana', true, true, 'india_post_import'),
  ('125039', 'Haryana', true, true, 'india_post_import'),
  ('125042', 'Haryana', true, true, 'india_post_import'),
  ('125044', 'Haryana', true, true, 'india_post_import'),
  ('125047', 'Haryana', true, true, 'india_post_import'),
  ('125048', 'Haryana', true, true, 'india_post_import'),
  ('125049', 'Haryana', true, true, 'india_post_import'),
  ('125050', 'Haryana', true, true, 'india_post_import'),
  ('125051', 'Haryana', true, true, 'india_post_import'),
  ('125052', 'Haryana', true, true, 'india_post_import'),
  ('125053', 'Haryana', true, true, 'india_post_import'),
  ('125054', 'Haryana', true, true, 'india_post_import'),
  ('125055', 'Haryana', true, true, 'india_post_import'),
  ('125056', 'Haryana', true, true, 'india_post_import'),
  ('125058', 'Haryana', true, true, 'india_post_import'),
  ('125060', 'Haryana', true, true, 'india_post_import'),
  ('125075', 'Haryana', true, true, 'india_post_import'),
  ('125076', 'Haryana', true, true, 'india_post_import'),
  ('125077', 'Haryana', true, true, 'india_post_import'),
  ('125078', 'Haryana', true, true, 'india_post_import'),
  ('125101', 'Haryana', true, true, 'india_post_import'),
  ('125102', 'Haryana', true, true, 'india_post_import'),
  ('125103', 'Haryana', true, true, 'india_post_import'),
  ('125104', 'Haryana', true, true, 'india_post_import'),
  ('125106', 'Haryana', true, true, 'india_post_import'),
  ('125110', 'Haryana', true, true, 'india_post_import'),
  ('125111', 'Haryana', true, true, 'india_post_import'),
  ('125112', 'Haryana', true, true, 'india_post_import'),
  ('125113', 'Haryana', true, true, 'india_post_import'),
  ('125120', 'Haryana', true, true, 'india_post_import'),
  ('125121', 'Haryana', true, true, 'india_post_import'),
  ('125133', 'Haryana', true, true, 'india_post_import'),
  ('125201', 'Haryana', true, true, 'india_post_import'),
  ('126101', 'Haryana', true, true, 'india_post_import'),
  ('126102', 'Haryana', true, true, 'india_post_import'),
  ('126110', 'Haryana', true, true, 'india_post_import'),
  ('126111', 'Haryana', true, true, 'india_post_import'),
  ('126112', 'Haryana', true, true, 'india_post_import'),
  ('126113', 'Haryana', true, true, 'india_post_import'),
  ('126114', 'Haryana', true, true, 'india_post_import'),
  ('126115', 'Haryana', true, true, 'india_post_import'),
  ('126116', 'Haryana', true, true, 'india_post_import'),
  ('126125', 'Haryana', true, true, 'india_post_import'),
  ('126152', 'Haryana', true, true, 'india_post_import'),
  ('127021', 'Haryana', true, true, 'india_post_import'),
  ('127022', 'Haryana', true, true, 'india_post_import'),
  ('127025', 'Haryana', true, true, 'india_post_import'),
  ('127026', 'Haryana', true, true, 'india_post_import'),
  ('127027', 'Haryana', true, true, 'india_post_import'),
  ('127028', 'Haryana', true, true, 'india_post_import'),
  ('127029', 'Haryana', true, true, 'india_post_import'),
  ('127030', 'Haryana', true, true, 'india_post_import'),
  ('127031', 'Haryana', true, true, 'india_post_import'),
  ('127032', 'Haryana', true, true, 'india_post_import'),
  ('127035', 'Haryana', true, true, 'india_post_import'),
  ('127040', 'Haryana', true, true, 'india_post_import'),
  ('127041', 'Haryana', true, true, 'india_post_import'),
  ('127042', 'Haryana', true, true, 'india_post_import'),
  ('127043', 'Haryana', true, true, 'india_post_import'),
  ('127045', 'Haryana', true, true, 'india_post_import'),
  ('127046', 'Haryana', true, true, 'india_post_import'),
  ('127111', 'Haryana', true, true, 'india_post_import'),
  ('127114', 'Haryana', true, true, 'india_post_import'),
  ('127201', 'Haryana', true, true, 'india_post_import'),
  ('127306', 'Haryana', true, true, 'india_post_import'),
  ('127307', 'Haryana', true, true, 'india_post_import'),
  ('127308', 'Haryana', true, true, 'india_post_import'),
  ('127309', 'Haryana', true, true, 'india_post_import'),
  ('127310', 'Haryana', true, true, 'india_post_import'),
  ('127311', 'Haryana', true, true, 'india_post_import'),
  ('127312', 'Haryana', true, true, 'india_post_import'),
  ('131001', 'Haryana', true, true, 'india_post_import'),
  ('131021', 'Haryana', true, true, 'india_post_import'),
  ('131022', 'Haryana', true, true, 'india_post_import'),
  ('131023', 'Haryana', true, true, 'india_post_import'),
  ('131024', 'Haryana', true, true, 'india_post_import'),
  ('131027', 'Haryana', true, true, 'india_post_import'),
  ('131028', 'Haryana', true, true, 'india_post_import'),
  ('131029', 'Haryana', true, true, 'india_post_import'),
  ('131030', 'Haryana', true, true, 'india_post_import'),
  ('131039', 'Haryana', true, true, 'india_post_import'),
  ('131101', 'Haryana', true, true, 'india_post_import'),
  ('131102', 'Haryana', true, true, 'india_post_import'),
  ('131103', 'Haryana', true, true, 'india_post_import'),
  ('131301', 'Haryana', true, true, 'india_post_import'),
  ('131302', 'Haryana', true, true, 'india_post_import'),
  ('131304', 'Haryana', true, true, 'india_post_import'),
  ('131305', 'Haryana', true, true, 'india_post_import'),
  ('131306', 'Haryana', true, true, 'india_post_import'),
  ('131402', 'Haryana', true, true, 'india_post_import'),
  ('131403', 'Haryana', true, true, 'india_post_import'),
  ('131408', 'Haryana', true, true, 'india_post_import'),
  ('131409', 'Haryana', true, true, 'india_post_import'),
  ('132001', 'Haryana', true, true, 'india_post_import'),
  ('132022', 'Haryana', true, true, 'india_post_import'),
  ('132023', 'Haryana', true, true, 'india_post_import'),
  ('132024', 'Haryana', true, true, 'india_post_import'),
  ('132036', 'Haryana', true, true, 'india_post_import'),
  ('132037', 'Haryana', true, true, 'india_post_import'),
  ('132039', 'Haryana', true, true, 'india_post_import'),
  ('132040', 'Haryana', true, true, 'india_post_import'),
  ('132041', 'Haryana', true, true, 'india_post_import'),
  ('132046', 'Haryana', true, true, 'india_post_import'),
  ('132054', 'Haryana', true, true, 'india_post_import'),
  ('132101', 'Haryana', true, true, 'india_post_import'),
  ('132102', 'Haryana', true, true, 'india_post_import'),
  ('132103', 'Haryana', true, true, 'india_post_import'),
  ('132104', 'Haryana', true, true, 'india_post_import'),
  ('132105', 'Haryana', true, true, 'india_post_import'),
  ('132106', 'Haryana', true, true, 'india_post_import'),
  ('132107', 'Haryana', true, true, 'india_post_import'),
  ('132108', 'Haryana', true, true, 'india_post_import'),
  ('132113', 'Haryana', true, true, 'india_post_import'),
  ('132114', 'Haryana', true, true, 'india_post_import'),
  ('132115', 'Haryana', true, true, 'india_post_import'),
  ('132116', 'Haryana', true, true, 'india_post_import'),
  ('132117', 'Haryana', true, true, 'india_post_import'),
  ('132122', 'Haryana', true, true, 'india_post_import'),
  ('132140', 'Haryana', true, true, 'india_post_import'),
  ('132145', 'Haryana', true, true, 'india_post_import'),
  ('132157', 'Haryana', true, true, 'india_post_import'),
  ('133001', 'Haryana', true, true, 'india_post_import'),
  ('133004', 'Haryana', true, true, 'india_post_import'),
  ('133005', 'Haryana', true, true, 'india_post_import'),
  ('133006', 'Haryana', true, true, 'india_post_import'),
  ('133008', 'Haryana', true, true, 'india_post_import'),
  ('133010', 'Haryana', true, true, 'india_post_import'),
  ('133101', 'Haryana', true, true, 'india_post_import'),
  ('133102', 'Haryana', true, true, 'india_post_import'),
  ('133103', 'Haryana', true, true, 'india_post_import'),
  ('133104', 'Haryana', true, true, 'india_post_import'),
  ('133201', 'Haryana', true, true, 'india_post_import'),
  ('133202', 'Haryana', true, true, 'india_post_import'),
  ('133203', 'Haryana', true, true, 'india_post_import'),
  ('133204', 'Haryana', true, true, 'india_post_import'),
  ('133205', 'Haryana', true, true, 'india_post_import'),
  ('133206', 'Haryana', true, true, 'india_post_import'),
  ('133207', 'Haryana', true, true, 'india_post_import'),
  ('133301', 'Haryana', true, true, 'india_post_import'),
  ('133302', 'Haryana', true, true, 'india_post_import'),
  ('134003', 'Haryana', true, true, 'india_post_import'),
  ('134005', 'Haryana', true, true, 'india_post_import'),
  ('134007', 'Haryana', true, true, 'india_post_import'),
  ('134008', 'Haryana', true, true, 'india_post_import'),
  ('134101', 'Haryana', true, true, 'india_post_import'),
  ('134102', 'Haryana', true, true, 'india_post_import'),
  ('134103', 'Haryana', true, true, 'india_post_import'),
  ('134104', 'Haryana', true, true, 'india_post_import'),
  ('134105', 'Haryana', true, true, 'india_post_import'),
  ('134107', 'Haryana', true, true, 'india_post_import'),
  ('134108', 'Haryana', true, true, 'india_post_import'),
  ('134109', 'Haryana', true, true, 'india_post_import'),
  ('134112', 'Haryana', true, true, 'india_post_import'),
  ('134113', 'Haryana', true, true, 'india_post_import'),
  ('134114', 'Haryana', true, true, 'india_post_import'),
  ('134116', 'Haryana', true, true, 'india_post_import'),
  ('134117', 'Haryana', true, true, 'india_post_import'),
  ('134118', 'Haryana', true, true, 'india_post_import'),
  ('134201', 'Haryana', true, true, 'india_post_import'),
  ('134202', 'Haryana', true, true, 'india_post_import'),
  ('134203', 'Haryana', true, true, 'india_post_import'),
  ('134204', 'Haryana', true, true, 'india_post_import'),
  ('134205', 'Haryana', true, true, 'india_post_import'),
  ('135001', 'Haryana', true, true, 'india_post_import'),
  ('135002', 'Haryana', true, true, 'india_post_import'),
  ('135003', 'Haryana', true, true, 'india_post_import'),
  ('135004', 'Haryana', true, true, 'india_post_import'),
  ('135021', 'Haryana', true, true, 'india_post_import'),
  ('135101', 'Haryana', true, true, 'india_post_import'),
  ('135102', 'Haryana', true, true, 'india_post_import'),
  ('135103', 'Haryana', true, true, 'india_post_import'),
  ('135106', 'Haryana', true, true, 'india_post_import'),
  ('135133', 'Haryana', true, true, 'india_post_import'),
  ('136020', 'Haryana', true, true, 'india_post_import'),
  ('136021', 'Haryana', true, true, 'india_post_import'),
  ('136026', 'Haryana', true, true, 'india_post_import'),
  ('136027', 'Haryana', true, true, 'india_post_import'),
  ('136030', 'Haryana', true, true, 'india_post_import'),
  ('136033', 'Haryana', true, true, 'india_post_import'),
  ('136034', 'Haryana', true, true, 'india_post_import'),
  ('136035', 'Haryana', true, true, 'india_post_import'),
  ('136038', 'Haryana', true, true, 'india_post_import'),
  ('136042', 'Haryana', true, true, 'india_post_import'),
  ('136043', 'Haryana', true, true, 'india_post_import'),
  ('136044', 'Haryana', true, true, 'india_post_import'),
  ('136117', 'Haryana', true, true, 'india_post_import'),
  ('136118', 'Haryana', true, true, 'india_post_import'),
  ('136119', 'Haryana', true, true, 'india_post_import'),
  ('136128', 'Haryana', true, true, 'india_post_import'),
  ('136129', 'Haryana', true, true, 'india_post_import'),
  ('136130', 'Haryana', true, true, 'india_post_import'),
  ('136131', 'Haryana', true, true, 'india_post_import'),
  ('136132', 'Haryana', true, true, 'india_post_import'),
  ('136134', 'Haryana', true, true, 'india_post_import'),
  ('136135', 'Haryana', true, true, 'india_post_import'),
  ('136136', 'Haryana', true, true, 'india_post_import'),
  ('136156', 'Haryana', true, true, 'india_post_import'),
  ('171001', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171002', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171003', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171004', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171005', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171006', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171007', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171008', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171009', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171010', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171011', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171012', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171013', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171014', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171015', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171018', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171019', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171102', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171103', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171201', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171202', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171203', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171204', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171205', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171206', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171207', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171208', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171209', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171210', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171211', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171212', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171213', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171214', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171215', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171216', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171217', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171218', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171219', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171220', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171221', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171222', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171223', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171224', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171225', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171226', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('171301', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172001', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172002', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172021', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172022', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172023', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172024', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172025', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172026', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172027', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172028', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172029', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172030', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172031', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172032', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172033', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172034', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172101', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172102', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172103', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172104', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172105', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172106', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172107', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172108', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172109', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172110', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172111', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172112', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172113', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172114', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172115', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172116', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172117', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172118', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('172201', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173001', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173021', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173022', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173023', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173024', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173025', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173026', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173027', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173029', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173030', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173031', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173032', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173101', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173104', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173201', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173202', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173204', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173205', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173206', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173207', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173208', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173209', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173210', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173211', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173212', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173213', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173214', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173215', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173217', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173218', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173220', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173221', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173222', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173223', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173225', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173229', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173230', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173233', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173234', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173235', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('173236', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174001', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174002', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174003', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174004', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174005', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174011', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174012', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174013', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174015', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174017', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174021', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174023', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174024', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174026', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174027', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174028', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174029', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174030', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174031', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174032', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174033', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174034', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174035', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174036', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174101', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174102', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174103', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174201', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174301', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174302', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174303', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174304', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174305', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174306', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174307', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174308', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174309', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174310', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174311', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174312', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174314', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174315', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174316', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174317', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174319', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174320', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174321', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174405', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174503', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174505', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('174507', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175001', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175002', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175003', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175004', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175005', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175006', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175007', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175008', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175009', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175010', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175011', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175012', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175013', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175014', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175015', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175016', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175017', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175018', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175019', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175020', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175021', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175023', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175024', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175025', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175026', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175027', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175028', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175029', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175030', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175031', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175032', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175033', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175034', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175035', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175036', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175037', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175038', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175039', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175040', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175042', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175045', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175046', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175047', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175048', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175049', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175050', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175051', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175052', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175075', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175101', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175102', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175103', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175104', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175105', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175106', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175121', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175123', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175124', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175125', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175126', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175128', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175129', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175130', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175131', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175132', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175133', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175134', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175136', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175138', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175139', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175140', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175141', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175142', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('175143', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176001', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176002', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176021', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176022', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176023', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176025', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176026', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176027', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176028', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176029', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176030', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176031', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176032', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176033', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176036', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176037', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176038', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176039', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176040', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176041', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176042', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176043', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176044', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176045', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176047', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176048', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176049', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176051', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176052', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176053', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176054', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176055', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176056', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176057', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176058', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176059', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176060', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176061', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176062', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176063', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176064', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176065', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176066', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176067', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176071', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176073', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176075', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176076', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176077', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176081', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176082', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176083', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176084', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176085', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176086', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176087', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176088', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176089', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176090', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176091', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176092', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176093', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176094', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176095', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176096', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176097', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176098', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176101', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176102', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176103', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176107', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176108', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176109', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176110', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176111', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176115', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176125', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176128', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176200', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176201', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176202', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176203', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176204', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176205', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176206', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176207', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176208', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176209', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176210', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176211', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176213', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176214', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176215', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176216', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176217', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176218', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176219', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176225', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176301', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176302', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176303', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176304', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176305', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176306', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176308', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176309', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176310', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176311', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176312', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176313', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176314', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176315', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176316', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176317', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176318', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176319', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176320', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176321', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176323', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176324', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176325', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176326', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176401', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176402', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176403', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176501', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176502', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('176601', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177001', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177005', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177006', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177007', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177020', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177021', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177022', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177023', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177024', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177025', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177026', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177027', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177028', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177029', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177031', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177033', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177034', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177038', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177039', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177040', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177041', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177042', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177043', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177044', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177045', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177048', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177101', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177103', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177104', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177105', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177106', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177107', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177108', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177109', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177110', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177111', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177112', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177113', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177114', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177117', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177118', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177119', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177201', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177202', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177203', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177204', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177205', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177206', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177207', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177208', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177209', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177210', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177211', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177212', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177213', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177219', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177220', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177301', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177401', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177501', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('177601', 'Himachal Pradesh', true, true, 'india_post_import'),
  ('180001', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180002', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180003', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180004', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180005', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180006', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180007', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180009', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180010', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180011', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180012', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180013', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180015', 'Jammu & Kashmir', true, true, 'india_post_import'),
  ('180016', 'Jammu & Kashmir', true, true, 'india_post_import')
on conflict (pincode) do nothing;