-- =====================================================================
-- Jayvi Foods — Pincode seed, file 11 of 21: pincodes rows 8686-9650
-- Run supabase_seed_pincodes_01_states.sql FIRST. Files 02-21 can then
-- run in any order (each is independent, uses ON CONFLICT DO NOTHING —
-- safe to re-run this specific file if it fails partway).
-- This file: 965 rows.
-- =====================================================================

insert into public.pincodes (pincode, state, serviceable, active, source) values
  ('476337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476339', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476355', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476444', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('476554', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477105', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477117', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477222', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477227', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477333', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477449', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477450', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477555', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477557', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477566', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('477660', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480105', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480106', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480107', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480108', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480109', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480112', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480223', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480224', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480334', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480338', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480449', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480555', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480557', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480559', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480667', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480880', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480882', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480884', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480886', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480887', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480888', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480991', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480994', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480996', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480997', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('480999', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481051', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481102', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481105', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481117', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481222', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481224', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481449', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481556', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481662', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481663', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481664', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481666', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481668', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481672', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481768', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481776', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481778', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481879', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481880', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481882', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481883', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481884', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481885', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481995', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481996', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('481998', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482004', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482008', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482009', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482010', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482011', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482020', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482021', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482051', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('482056', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483053', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483105', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483119', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483222', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483225', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483330', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483332', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483334', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483336', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483442', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483501', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483504', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483773', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483880', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('483990', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484116', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484117', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484120', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484224', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484330', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484334', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484336', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484444', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484555', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484660', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484664', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484665', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484669', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484774', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484776', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484886', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('484887', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485112', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485113', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485334', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485666', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485772', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485773', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485774', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485778', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('485881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486002', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486003', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486004', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486005', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486006', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486111', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486115', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486117', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486123', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486223', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486226', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486331', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486333', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486335', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486338', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486340', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486341', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486440', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486445', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486447', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486448', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486450', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486550', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486553', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486556', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486666', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486669', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486670', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486675', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486771', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486775', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486776', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486882', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486884', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486885', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486886', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486887', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486888', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486889', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486890', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('486892', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487110', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487114', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487118', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487221', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487225', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487330', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487334', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487337', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487551', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487555', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487661', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487770', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('487881', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488001', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488050', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488051', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488059', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488220', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488222', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488333', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488441', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488442', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488443', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488446', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('488448', 'Madhya Pradesh', true, true, 'india_post_import'),
  ('400001', 'Maharashtra', true, true, 'india_post_import'),
  ('400002', 'Maharashtra', true, true, 'india_post_import'),
  ('400003', 'Maharashtra', true, true, 'india_post_import'),
  ('400004', 'Maharashtra', true, true, 'india_post_import'),
  ('400005', 'Maharashtra', true, true, 'india_post_import'),
  ('400006', 'Maharashtra', true, true, 'india_post_import'),
  ('400007', 'Maharashtra', true, true, 'india_post_import'),
  ('400008', 'Maharashtra', true, true, 'india_post_import'),
  ('400009', 'Maharashtra', true, true, 'india_post_import'),
  ('400010', 'Maharashtra', true, true, 'india_post_import'),
  ('400011', 'Maharashtra', true, true, 'india_post_import'),
  ('400012', 'Maharashtra', true, true, 'india_post_import'),
  ('400013', 'Maharashtra', true, true, 'india_post_import'),
  ('400014', 'Maharashtra', true, true, 'india_post_import'),
  ('400015', 'Maharashtra', true, true, 'india_post_import'),
  ('400016', 'Maharashtra', true, true, 'india_post_import'),
  ('400017', 'Maharashtra', true, true, 'india_post_import'),
  ('400018', 'Maharashtra', true, true, 'india_post_import'),
  ('400019', 'Maharashtra', true, true, 'india_post_import'),
  ('400020', 'Maharashtra', true, true, 'india_post_import'),
  ('400021', 'Maharashtra', true, true, 'india_post_import'),
  ('400022', 'Maharashtra', true, true, 'india_post_import'),
  ('400024', 'Maharashtra', true, true, 'india_post_import'),
  ('400025', 'Maharashtra', true, true, 'india_post_import'),
  ('400026', 'Maharashtra', true, true, 'india_post_import'),
  ('400027', 'Maharashtra', true, true, 'india_post_import'),
  ('400028', 'Maharashtra', true, true, 'india_post_import'),
  ('400029', 'Maharashtra', true, true, 'india_post_import'),
  ('400030', 'Maharashtra', true, true, 'india_post_import'),
  ('400031', 'Maharashtra', true, true, 'india_post_import'),
  ('400032', 'Maharashtra', true, true, 'india_post_import'),
  ('400033', 'Maharashtra', true, true, 'india_post_import'),
  ('400034', 'Maharashtra', true, true, 'india_post_import'),
  ('400035', 'Maharashtra', true, true, 'india_post_import'),
  ('400037', 'Maharashtra', true, true, 'india_post_import'),
  ('400042', 'Maharashtra', true, true, 'india_post_import'),
  ('400043', 'Maharashtra', true, true, 'india_post_import'),
  ('400049', 'Maharashtra', true, true, 'india_post_import'),
  ('400050', 'Maharashtra', true, true, 'india_post_import'),
  ('400051', 'Maharashtra', true, true, 'india_post_import'),
  ('400052', 'Maharashtra', true, true, 'india_post_import'),
  ('400053', 'Maharashtra', true, true, 'india_post_import'),
  ('400054', 'Maharashtra', true, true, 'india_post_import'),
  ('400055', 'Maharashtra', true, true, 'india_post_import'),
  ('400056', 'Maharashtra', true, true, 'india_post_import'),
  ('400057', 'Maharashtra', true, true, 'india_post_import'),
  ('400058', 'Maharashtra', true, true, 'india_post_import'),
  ('400059', 'Maharashtra', true, true, 'india_post_import'),
  ('400060', 'Maharashtra', true, true, 'india_post_import'),
  ('400061', 'Maharashtra', true, true, 'india_post_import'),
  ('400063', 'Maharashtra', true, true, 'india_post_import'),
  ('400064', 'Maharashtra', true, true, 'india_post_import'),
  ('400065', 'Maharashtra', true, true, 'india_post_import'),
  ('400066', 'Maharashtra', true, true, 'india_post_import'),
  ('400067', 'Maharashtra', true, true, 'india_post_import'),
  ('400068', 'Maharashtra', true, true, 'india_post_import'),
  ('400069', 'Maharashtra', true, true, 'india_post_import'),
  ('400070', 'Maharashtra', true, true, 'india_post_import'),
  ('400071', 'Maharashtra', true, true, 'india_post_import'),
  ('400072', 'Maharashtra', true, true, 'india_post_import'),
  ('400074', 'Maharashtra', true, true, 'india_post_import'),
  ('400075', 'Maharashtra', true, true, 'india_post_import'),
  ('400076', 'Maharashtra', true, true, 'india_post_import'),
  ('400077', 'Maharashtra', true, true, 'india_post_import'),
  ('400078', 'Maharashtra', true, true, 'india_post_import'),
  ('400079', 'Maharashtra', true, true, 'india_post_import'),
  ('400080', 'Maharashtra', true, true, 'india_post_import'),
  ('400081', 'Maharashtra', true, true, 'india_post_import'),
  ('400082', 'Maharashtra', true, true, 'india_post_import'),
  ('400083', 'Maharashtra', true, true, 'india_post_import'),
  ('400084', 'Maharashtra', true, true, 'india_post_import'),
  ('400085', 'Maharashtra', true, true, 'india_post_import'),
  ('400086', 'Maharashtra', true, true, 'india_post_import'),
  ('400087', 'Maharashtra', true, true, 'india_post_import'),
  ('400088', 'Maharashtra', true, true, 'india_post_import'),
  ('400089', 'Maharashtra', true, true, 'india_post_import'),
  ('400091', 'Maharashtra', true, true, 'india_post_import'),
  ('400092', 'Maharashtra', true, true, 'india_post_import'),
  ('400093', 'Maharashtra', true, true, 'india_post_import'),
  ('400094', 'Maharashtra', true, true, 'india_post_import'),
  ('400095', 'Maharashtra', true, true, 'india_post_import'),
  ('400096', 'Maharashtra', true, true, 'india_post_import'),
  ('400097', 'Maharashtra', true, true, 'india_post_import'),
  ('400098', 'Maharashtra', true, true, 'india_post_import'),
  ('400099', 'Maharashtra', true, true, 'india_post_import'),
  ('400101', 'Maharashtra', true, true, 'india_post_import'),
  ('400102', 'Maharashtra', true, true, 'india_post_import'),
  ('400103', 'Maharashtra', true, true, 'india_post_import'),
  ('400104', 'Maharashtra', true, true, 'india_post_import'),
  ('400601', 'Maharashtra', true, true, 'india_post_import'),
  ('400602', 'Maharashtra', true, true, 'india_post_import'),
  ('400603', 'Maharashtra', true, true, 'india_post_import'),
  ('400604', 'Maharashtra', true, true, 'india_post_import'),
  ('400605', 'Maharashtra', true, true, 'india_post_import'),
  ('400606', 'Maharashtra', true, true, 'india_post_import'),
  ('400607', 'Maharashtra', true, true, 'india_post_import'),
  ('400608', 'Maharashtra', true, true, 'india_post_import'),
  ('400610', 'Maharashtra', true, true, 'india_post_import'),
  ('400612', 'Maharashtra', true, true, 'india_post_import'),
  ('400614', 'Maharashtra', true, true, 'india_post_import'),
  ('400615', 'Maharashtra', true, true, 'india_post_import'),
  ('400701', 'Maharashtra', true, true, 'india_post_import'),
  ('400702', 'Maharashtra', true, true, 'india_post_import'),
  ('400703', 'Maharashtra', true, true, 'india_post_import'),
  ('400704', 'Maharashtra', true, true, 'india_post_import'),
  ('400705', 'Maharashtra', true, true, 'india_post_import'),
  ('400706', 'Maharashtra', true, true, 'india_post_import'),
  ('400707', 'Maharashtra', true, true, 'india_post_import'),
  ('400708', 'Maharashtra', true, true, 'india_post_import'),
  ('400709', 'Maharashtra', true, true, 'india_post_import'),
  ('400710', 'Maharashtra', true, true, 'india_post_import'),
  ('401101', 'Maharashtra', true, true, 'india_post_import'),
  ('401102', 'Maharashtra', true, true, 'india_post_import'),
  ('401103', 'Maharashtra', true, true, 'india_post_import'),
  ('401105', 'Maharashtra', true, true, 'india_post_import'),
  ('401106', 'Maharashtra', true, true, 'india_post_import'),
  ('401107', 'Maharashtra', true, true, 'india_post_import'),
  ('401201', 'Maharashtra', true, true, 'india_post_import'),
  ('401202', 'Maharashtra', true, true, 'india_post_import'),
  ('401203', 'Maharashtra', true, true, 'india_post_import'),
  ('401204', 'Maharashtra', true, true, 'india_post_import'),
  ('401206', 'Maharashtra', true, true, 'india_post_import'),
  ('401207', 'Maharashtra', true, true, 'india_post_import'),
  ('401208', 'Maharashtra', true, true, 'india_post_import'),
  ('401209', 'Maharashtra', true, true, 'india_post_import'),
  ('401301', 'Maharashtra', true, true, 'india_post_import'),
  ('401302', 'Maharashtra', true, true, 'india_post_import'),
  ('401303', 'Maharashtra', true, true, 'india_post_import'),
  ('401304', 'Maharashtra', true, true, 'india_post_import'),
  ('401305', 'Maharashtra', true, true, 'india_post_import'),
  ('401401', 'Maharashtra', true, true, 'india_post_import'),
  ('401402', 'Maharashtra', true, true, 'india_post_import'),
  ('401403', 'Maharashtra', true, true, 'india_post_import'),
  ('401404', 'Maharashtra', true, true, 'india_post_import'),
  ('401405', 'Maharashtra', true, true, 'india_post_import'),
  ('401501', 'Maharashtra', true, true, 'india_post_import'),
  ('401502', 'Maharashtra', true, true, 'india_post_import'),
  ('401503', 'Maharashtra', true, true, 'india_post_import'),
  ('401504', 'Maharashtra', true, true, 'india_post_import'),
  ('401506', 'Maharashtra', true, true, 'india_post_import'),
  ('401601', 'Maharashtra', true, true, 'india_post_import'),
  ('401602', 'Maharashtra', true, true, 'india_post_import'),
  ('401603', 'Maharashtra', true, true, 'india_post_import'),
  ('401604', 'Maharashtra', true, true, 'india_post_import'),
  ('401605', 'Maharashtra', true, true, 'india_post_import'),
  ('401606', 'Maharashtra', true, true, 'india_post_import'),
  ('401607', 'Maharashtra', true, true, 'india_post_import'),
  ('401608', 'Maharashtra', true, true, 'india_post_import'),
  ('401701', 'Maharashtra', true, true, 'india_post_import'),
  ('401702', 'Maharashtra', true, true, 'india_post_import'),
  ('401703', 'Maharashtra', true, true, 'india_post_import'),
  ('402101', 'Maharashtra', true, true, 'india_post_import'),
  ('402102', 'Maharashtra', true, true, 'india_post_import'),
  ('402103', 'Maharashtra', true, true, 'india_post_import'),
  ('402104', 'Maharashtra', true, true, 'india_post_import'),
  ('402105', 'Maharashtra', true, true, 'india_post_import'),
  ('402106', 'Maharashtra', true, true, 'india_post_import'),
  ('402107', 'Maharashtra', true, true, 'india_post_import'),
  ('402108', 'Maharashtra', true, true, 'india_post_import'),
  ('402109', 'Maharashtra', true, true, 'india_post_import'),
  ('402110', 'Maharashtra', true, true, 'india_post_import'),
  ('402111', 'Maharashtra', true, true, 'india_post_import'),
  ('402112', 'Maharashtra', true, true, 'india_post_import'),
  ('402113', 'Maharashtra', true, true, 'india_post_import'),
  ('402114', 'Maharashtra', true, true, 'india_post_import'),
  ('402115', 'Maharashtra', true, true, 'india_post_import'),
  ('402116', 'Maharashtra', true, true, 'india_post_import'),
  ('402117', 'Maharashtra', true, true, 'india_post_import'),
  ('402120', 'Maharashtra', true, true, 'india_post_import'),
  ('402122', 'Maharashtra', true, true, 'india_post_import'),
  ('402125', 'Maharashtra', true, true, 'india_post_import'),
  ('402126', 'Maharashtra', true, true, 'india_post_import'),
  ('402201', 'Maharashtra', true, true, 'india_post_import'),
  ('402202', 'Maharashtra', true, true, 'india_post_import'),
  ('402203', 'Maharashtra', true, true, 'india_post_import'),
  ('402204', 'Maharashtra', true, true, 'india_post_import'),
  ('402207', 'Maharashtra', true, true, 'india_post_import'),
  ('402208', 'Maharashtra', true, true, 'india_post_import'),
  ('402209', 'Maharashtra', true, true, 'india_post_import'),
  ('402301', 'Maharashtra', true, true, 'india_post_import'),
  ('402302', 'Maharashtra', true, true, 'india_post_import'),
  ('402303', 'Maharashtra', true, true, 'india_post_import'),
  ('402304', 'Maharashtra', true, true, 'india_post_import'),
  ('402305', 'Maharashtra', true, true, 'india_post_import'),
  ('402306', 'Maharashtra', true, true, 'india_post_import'),
  ('402307', 'Maharashtra', true, true, 'india_post_import'),
  ('402308', 'Maharashtra', true, true, 'india_post_import'),
  ('402309', 'Maharashtra', true, true, 'india_post_import'),
  ('402401', 'Maharashtra', true, true, 'india_post_import'),
  ('402402', 'Maharashtra', true, true, 'india_post_import'),
  ('402403', 'Maharashtra', true, true, 'india_post_import'),
  ('402404', 'Maharashtra', true, true, 'india_post_import'),
  ('403001', 'Maharashtra', true, true, 'india_post_import'),
  ('403002', 'Maharashtra', true, true, 'india_post_import'),
  ('403004', 'Maharashtra', true, true, 'india_post_import'),
  ('403005', 'Maharashtra', true, true, 'india_post_import'),
  ('403006', 'Maharashtra', true, true, 'india_post_import'),
  ('403101', 'Maharashtra', true, true, 'india_post_import'),
  ('403102', 'Maharashtra', true, true, 'india_post_import'),
  ('403103', 'Maharashtra', true, true, 'india_post_import'),
  ('403104', 'Maharashtra', true, true, 'india_post_import'),
  ('403105', 'Maharashtra', true, true, 'india_post_import'),
  ('403106', 'Maharashtra', true, true, 'india_post_import'),
  ('403107', 'Maharashtra', true, true, 'india_post_import'),
  ('403108', 'Maharashtra', true, true, 'india_post_import'),
  ('403109', 'Maharashtra', true, true, 'india_post_import'),
  ('403110', 'Maharashtra', true, true, 'india_post_import'),
  ('403114', 'Maharashtra', true, true, 'india_post_import'),
  ('403115', 'Maharashtra', true, true, 'india_post_import'),
  ('403201', 'Maharashtra', true, true, 'india_post_import'),
  ('403202', 'Maharashtra', true, true, 'india_post_import'),
  ('403203', 'Maharashtra', true, true, 'india_post_import'),
  ('403204', 'Maharashtra', true, true, 'india_post_import'),
  ('403206', 'Maharashtra', true, true, 'india_post_import'),
  ('403401', 'Maharashtra', true, true, 'india_post_import'),
  ('403402', 'Maharashtra', true, true, 'india_post_import'),
  ('403403', 'Maharashtra', true, true, 'india_post_import'),
  ('403404', 'Maharashtra', true, true, 'india_post_import'),
  ('403406', 'Maharashtra', true, true, 'india_post_import'),
  ('403409', 'Maharashtra', true, true, 'india_post_import'),
  ('403410', 'Maharashtra', true, true, 'india_post_import'),
  ('403501', 'Maharashtra', true, true, 'india_post_import'),
  ('403502', 'Maharashtra', true, true, 'india_post_import'),
  ('403503', 'Maharashtra', true, true, 'india_post_import'),
  ('403504', 'Maharashtra', true, true, 'india_post_import'),
  ('403505', 'Maharashtra', true, true, 'india_post_import'),
  ('403506', 'Maharashtra', true, true, 'india_post_import'),
  ('403507', 'Maharashtra', true, true, 'india_post_import'),
  ('403508', 'Maharashtra', true, true, 'india_post_import'),
  ('403509', 'Maharashtra', true, true, 'india_post_import'),
  ('403510', 'Maharashtra', true, true, 'india_post_import'),
  ('403511', 'Maharashtra', true, true, 'india_post_import'),
  ('403512', 'Maharashtra', true, true, 'india_post_import'),
  ('403513', 'Maharashtra', true, true, 'india_post_import'),
  ('403515', 'Maharashtra', true, true, 'india_post_import'),
  ('403516', 'Maharashtra', true, true, 'india_post_import'),
  ('403517', 'Maharashtra', true, true, 'india_post_import'),
  ('403521', 'Maharashtra', true, true, 'india_post_import'),
  ('403523', 'Maharashtra', true, true, 'india_post_import'),
  ('403524', 'Maharashtra', true, true, 'india_post_import'),
  ('403526', 'Maharashtra', true, true, 'india_post_import'),
  ('403527', 'Maharashtra', true, true, 'india_post_import'),
  ('403529', 'Maharashtra', true, true, 'india_post_import'),
  ('403530', 'Maharashtra', true, true, 'india_post_import'),
  ('403601', 'Maharashtra', true, true, 'india_post_import'),
  ('403602', 'Maharashtra', true, true, 'india_post_import'),
  ('403701', 'Maharashtra', true, true, 'india_post_import'),
  ('403702', 'Maharashtra', true, true, 'india_post_import'),
  ('403703', 'Maharashtra', true, true, 'india_post_import'),
  ('403704', 'Maharashtra', true, true, 'india_post_import'),
  ('403705', 'Maharashtra', true, true, 'india_post_import'),
  ('403706', 'Maharashtra', true, true, 'india_post_import'),
  ('403707', 'Maharashtra', true, true, 'india_post_import'),
  ('403708', 'Maharashtra', true, true, 'india_post_import'),
  ('403709', 'Maharashtra', true, true, 'india_post_import'),
  ('403710', 'Maharashtra', true, true, 'india_post_import'),
  ('403711', 'Maharashtra', true, true, 'india_post_import'),
  ('403712', 'Maharashtra', true, true, 'india_post_import'),
  ('403713', 'Maharashtra', true, true, 'india_post_import'),
  ('403714', 'Maharashtra', true, true, 'india_post_import'),
  ('403715', 'Maharashtra', true, true, 'india_post_import'),
  ('403716', 'Maharashtra', true, true, 'india_post_import'),
  ('403717', 'Maharashtra', true, true, 'india_post_import'),
  ('403718', 'Maharashtra', true, true, 'india_post_import'),
  ('403719', 'Maharashtra', true, true, 'india_post_import'),
  ('403720', 'Maharashtra', true, true, 'india_post_import'),
  ('403721', 'Maharashtra', true, true, 'india_post_import'),
  ('403722', 'Maharashtra', true, true, 'india_post_import'),
  ('403723', 'Maharashtra', true, true, 'india_post_import'),
  ('403724', 'Maharashtra', true, true, 'india_post_import'),
  ('403725', 'Maharashtra', true, true, 'india_post_import'),
  ('403726', 'Maharashtra', true, true, 'india_post_import'),
  ('403728', 'Maharashtra', true, true, 'india_post_import'),
  ('403729', 'Maharashtra', true, true, 'india_post_import'),
  ('403731', 'Maharashtra', true, true, 'india_post_import'),
  ('403801', 'Maharashtra', true, true, 'india_post_import'),
  ('403802', 'Maharashtra', true, true, 'india_post_import'),
  ('403803', 'Maharashtra', true, true, 'india_post_import'),
  ('403804', 'Maharashtra', true, true, 'india_post_import'),
  ('403806', 'Maharashtra', true, true, 'india_post_import'),
  ('410101', 'Maharashtra', true, true, 'india_post_import'),
  ('410102', 'Maharashtra', true, true, 'india_post_import'),
  ('410201', 'Maharashtra', true, true, 'india_post_import'),
  ('410202', 'Maharashtra', true, true, 'india_post_import'),
  ('410203', 'Maharashtra', true, true, 'india_post_import'),
  ('410204', 'Maharashtra', true, true, 'india_post_import'),
  ('410205', 'Maharashtra', true, true, 'india_post_import'),
  ('410206', 'Maharashtra', true, true, 'india_post_import'),
  ('410207', 'Maharashtra', true, true, 'india_post_import'),
  ('410208', 'Maharashtra', true, true, 'india_post_import'),
  ('410209', 'Maharashtra', true, true, 'india_post_import'),
  ('410210', 'Maharashtra', true, true, 'india_post_import'),
  ('410216', 'Maharashtra', true, true, 'india_post_import'),
  ('410218', 'Maharashtra', true, true, 'india_post_import'),
  ('410220', 'Maharashtra', true, true, 'india_post_import'),
  ('410221', 'Maharashtra', true, true, 'india_post_import'),
  ('410222', 'Maharashtra', true, true, 'india_post_import'),
  ('410301', 'Maharashtra', true, true, 'india_post_import'),
  ('410302', 'Maharashtra', true, true, 'india_post_import'),
  ('410401', 'Maharashtra', true, true, 'india_post_import'),
  ('410402', 'Maharashtra', true, true, 'india_post_import'),
  ('410403', 'Maharashtra', true, true, 'india_post_import'),
  ('410405', 'Maharashtra', true, true, 'india_post_import'),
  ('410406', 'Maharashtra', true, true, 'india_post_import'),
  ('410501', 'Maharashtra', true, true, 'india_post_import'),
  ('410502', 'Maharashtra', true, true, 'india_post_import'),
  ('410503', 'Maharashtra', true, true, 'india_post_import'),
  ('410504', 'Maharashtra', true, true, 'india_post_import'),
  ('410505', 'Maharashtra', true, true, 'india_post_import'),
  ('410506', 'Maharashtra', true, true, 'india_post_import'),
  ('410507', 'Maharashtra', true, true, 'india_post_import'),
  ('410508', 'Maharashtra', true, true, 'india_post_import'),
  ('410509', 'Maharashtra', true, true, 'india_post_import'),
  ('410510', 'Maharashtra', true, true, 'india_post_import'),
  ('410511', 'Maharashtra', true, true, 'india_post_import'),
  ('410512', 'Maharashtra', true, true, 'india_post_import'),
  ('410513', 'Maharashtra', true, true, 'india_post_import'),
  ('410515', 'Maharashtra', true, true, 'india_post_import'),
  ('410516', 'Maharashtra', true, true, 'india_post_import'),
  ('411001', 'Maharashtra', true, true, 'india_post_import'),
  ('411002', 'Maharashtra', true, true, 'india_post_import'),
  ('411003', 'Maharashtra', true, true, 'india_post_import'),
  ('411004', 'Maharashtra', true, true, 'india_post_import'),
  ('411005', 'Maharashtra', true, true, 'india_post_import'),
  ('411006', 'Maharashtra', true, true, 'india_post_import'),
  ('411007', 'Maharashtra', true, true, 'india_post_import'),
  ('411008', 'Maharashtra', true, true, 'india_post_import'),
  ('411009', 'Maharashtra', true, true, 'india_post_import'),
  ('411011', 'Maharashtra', true, true, 'india_post_import'),
  ('411012', 'Maharashtra', true, true, 'india_post_import'),
  ('411013', 'Maharashtra', true, true, 'india_post_import'),
  ('411014', 'Maharashtra', true, true, 'india_post_import'),
  ('411015', 'Maharashtra', true, true, 'india_post_import'),
  ('411016', 'Maharashtra', true, true, 'india_post_import'),
  ('411017', 'Maharashtra', true, true, 'india_post_import'),
  ('411018', 'Maharashtra', true, true, 'india_post_import'),
  ('411019', 'Maharashtra', true, true, 'india_post_import'),
  ('411020', 'Maharashtra', true, true, 'india_post_import'),
  ('411021', 'Maharashtra', true, true, 'india_post_import'),
  ('411022', 'Maharashtra', true, true, 'india_post_import'),
  ('411023', 'Maharashtra', true, true, 'india_post_import'),
  ('411024', 'Maharashtra', true, true, 'india_post_import'),
  ('411025', 'Maharashtra', true, true, 'india_post_import'),
  ('411026', 'Maharashtra', true, true, 'india_post_import'),
  ('411027', 'Maharashtra', true, true, 'india_post_import'),
  ('411028', 'Maharashtra', true, true, 'india_post_import'),
  ('411030', 'Maharashtra', true, true, 'india_post_import'),
  ('411031', 'Maharashtra', true, true, 'india_post_import'),
  ('411032', 'Maharashtra', true, true, 'india_post_import'),
  ('411033', 'Maharashtra', true, true, 'india_post_import'),
  ('411034', 'Maharashtra', true, true, 'india_post_import'),
  ('411035', 'Maharashtra', true, true, 'india_post_import'),
  ('411036', 'Maharashtra', true, true, 'india_post_import'),
  ('411037', 'Maharashtra', true, true, 'india_post_import'),
  ('411038', 'Maharashtra', true, true, 'india_post_import'),
  ('411039', 'Maharashtra', true, true, 'india_post_import'),
  ('411040', 'Maharashtra', true, true, 'india_post_import'),
  ('411041', 'Maharashtra', true, true, 'india_post_import'),
  ('411042', 'Maharashtra', true, true, 'india_post_import'),
  ('411043', 'Maharashtra', true, true, 'india_post_import'),
  ('411044', 'Maharashtra', true, true, 'india_post_import'),
  ('411045', 'Maharashtra', true, true, 'india_post_import'),
  ('411046', 'Maharashtra', true, true, 'india_post_import'),
  ('411047', 'Maharashtra', true, true, 'india_post_import'),
  ('411048', 'Maharashtra', true, true, 'india_post_import'),
  ('411051', 'Maharashtra', true, true, 'india_post_import'),
  ('411052', 'Maharashtra', true, true, 'india_post_import'),
  ('411057', 'Maharashtra', true, true, 'india_post_import'),
  ('411058', 'Maharashtra', true, true, 'india_post_import'),
  ('411060', 'Maharashtra', true, true, 'india_post_import'),
  ('411061', 'Maharashtra', true, true, 'india_post_import'),
  ('411062', 'Maharashtra', true, true, 'india_post_import'),
  ('411067', 'Maharashtra', true, true, 'india_post_import'),
  ('411068', 'Maharashtra', true, true, 'india_post_import'),
  ('411069', 'Maharashtra', true, true, 'india_post_import'),
  ('412101', 'Maharashtra', true, true, 'india_post_import'),
  ('412102', 'Maharashtra', true, true, 'india_post_import'),
  ('412103', 'Maharashtra', true, true, 'india_post_import'),
  ('412104', 'Maharashtra', true, true, 'india_post_import'),
  ('412105', 'Maharashtra', true, true, 'india_post_import'),
  ('412106', 'Maharashtra', true, true, 'india_post_import'),
  ('412107', 'Maharashtra', true, true, 'india_post_import'),
  ('412108', 'Maharashtra', true, true, 'india_post_import'),
  ('412109', 'Maharashtra', true, true, 'india_post_import'),
  ('412110', 'Maharashtra', true, true, 'india_post_import'),
  ('412112', 'Maharashtra', true, true, 'india_post_import'),
  ('412115', 'Maharashtra', true, true, 'india_post_import'),
  ('412201', 'Maharashtra', true, true, 'india_post_import'),
  ('412202', 'Maharashtra', true, true, 'india_post_import'),
  ('412203', 'Maharashtra', true, true, 'india_post_import'),
  ('412204', 'Maharashtra', true, true, 'india_post_import'),
  ('412205', 'Maharashtra', true, true, 'india_post_import'),
  ('412206', 'Maharashtra', true, true, 'india_post_import'),
  ('412207', 'Maharashtra', true, true, 'india_post_import'),
  ('412208', 'Maharashtra', true, true, 'india_post_import'),
  ('412209', 'Maharashtra', true, true, 'india_post_import'),
  ('412210', 'Maharashtra', true, true, 'india_post_import'),
  ('412211', 'Maharashtra', true, true, 'india_post_import'),
  ('412212', 'Maharashtra', true, true, 'india_post_import'),
  ('412213', 'Maharashtra', true, true, 'india_post_import'),
  ('412214', 'Maharashtra', true, true, 'india_post_import'),
  ('412215', 'Maharashtra', true, true, 'india_post_import'),
  ('412216', 'Maharashtra', true, true, 'india_post_import'),
  ('412218', 'Maharashtra', true, true, 'india_post_import'),
  ('412219', 'Maharashtra', true, true, 'india_post_import'),
  ('412220', 'Maharashtra', true, true, 'india_post_import'),
  ('412301', 'Maharashtra', true, true, 'india_post_import'),
  ('412303', 'Maharashtra', true, true, 'india_post_import'),
  ('412304', 'Maharashtra', true, true, 'india_post_import'),
  ('412305', 'Maharashtra', true, true, 'india_post_import'),
  ('412306', 'Maharashtra', true, true, 'india_post_import'),
  ('412307', 'Maharashtra', true, true, 'india_post_import'),
  ('412308', 'Maharashtra', true, true, 'india_post_import'),
  ('412311', 'Maharashtra', true, true, 'india_post_import'),
  ('412312', 'Maharashtra', true, true, 'india_post_import'),
  ('412401', 'Maharashtra', true, true, 'india_post_import'),
  ('412402', 'Maharashtra', true, true, 'india_post_import'),
  ('412403', 'Maharashtra', true, true, 'india_post_import'),
  ('412404', 'Maharashtra', true, true, 'india_post_import'),
  ('412405', 'Maharashtra', true, true, 'india_post_import'),
  ('412406', 'Maharashtra', true, true, 'india_post_import'),
  ('412408', 'Maharashtra', true, true, 'india_post_import'),
  ('412409', 'Maharashtra', true, true, 'india_post_import'),
  ('412410', 'Maharashtra', true, true, 'india_post_import'),
  ('412411', 'Maharashtra', true, true, 'india_post_import'),
  ('412412', 'Maharashtra', true, true, 'india_post_import'),
  ('412801', 'Maharashtra', true, true, 'india_post_import'),
  ('412802', 'Maharashtra', true, true, 'india_post_import'),
  ('412803', 'Maharashtra', true, true, 'india_post_import'),
  ('412804', 'Maharashtra', true, true, 'india_post_import'),
  ('412805', 'Maharashtra', true, true, 'india_post_import'),
  ('412806', 'Maharashtra', true, true, 'india_post_import'),
  ('413001', 'Maharashtra', true, true, 'india_post_import'),
  ('413002', 'Maharashtra', true, true, 'india_post_import'),
  ('413003', 'Maharashtra', true, true, 'india_post_import'),
  ('413004', 'Maharashtra', true, true, 'india_post_import'),
  ('413005', 'Maharashtra', true, true, 'india_post_import'),
  ('413006', 'Maharashtra', true, true, 'india_post_import'),
  ('413007', 'Maharashtra', true, true, 'india_post_import'),
  ('413008', 'Maharashtra', true, true, 'india_post_import'),
  ('413101', 'Maharashtra', true, true, 'india_post_import'),
  ('413102', 'Maharashtra', true, true, 'india_post_import'),
  ('413103', 'Maharashtra', true, true, 'india_post_import'),
  ('413104', 'Maharashtra', true, true, 'india_post_import'),
  ('413105', 'Maharashtra', true, true, 'india_post_import'),
  ('413106', 'Maharashtra', true, true, 'india_post_import'),
  ('413107', 'Maharashtra', true, true, 'india_post_import'),
  ('413108', 'Maharashtra', true, true, 'india_post_import'),
  ('413109', 'Maharashtra', true, true, 'india_post_import'),
  ('413110', 'Maharashtra', true, true, 'india_post_import'),
  ('413111', 'Maharashtra', true, true, 'india_post_import'),
  ('413112', 'Maharashtra', true, true, 'india_post_import'),
  ('413113', 'Maharashtra', true, true, 'india_post_import'),
  ('413114', 'Maharashtra', true, true, 'india_post_import'),
  ('413115', 'Maharashtra', true, true, 'india_post_import'),
  ('413116', 'Maharashtra', true, true, 'india_post_import'),
  ('413118', 'Maharashtra', true, true, 'india_post_import'),
  ('413120', 'Maharashtra', true, true, 'india_post_import'),
  ('413130', 'Maharashtra', true, true, 'india_post_import'),
  ('413132', 'Maharashtra', true, true, 'india_post_import'),
  ('413133', 'Maharashtra', true, true, 'india_post_import'),
  ('413201', 'Maharashtra', true, true, 'india_post_import'),
  ('413202', 'Maharashtra', true, true, 'india_post_import'),
  ('413203', 'Maharashtra', true, true, 'india_post_import'),
  ('413204', 'Maharashtra', true, true, 'india_post_import'),
  ('413205', 'Maharashtra', true, true, 'india_post_import'),
  ('413206', 'Maharashtra', true, true, 'india_post_import'),
  ('413207', 'Maharashtra', true, true, 'india_post_import'),
  ('413208', 'Maharashtra', true, true, 'india_post_import'),
  ('413209', 'Maharashtra', true, true, 'india_post_import'),
  ('413210', 'Maharashtra', true, true, 'india_post_import'),
  ('413211', 'Maharashtra', true, true, 'india_post_import'),
  ('413212', 'Maharashtra', true, true, 'india_post_import'),
  ('413213', 'Maharashtra', true, true, 'india_post_import'),
  ('413214', 'Maharashtra', true, true, 'india_post_import'),
  ('413215', 'Maharashtra', true, true, 'india_post_import'),
  ('413216', 'Maharashtra', true, true, 'india_post_import'),
  ('413217', 'Maharashtra', true, true, 'india_post_import'),
  ('413218', 'Maharashtra', true, true, 'india_post_import'),
  ('413219', 'Maharashtra', true, true, 'india_post_import'),
  ('413220', 'Maharashtra', true, true, 'india_post_import'),
  ('413221', 'Maharashtra', true, true, 'india_post_import'),
  ('413222', 'Maharashtra', true, true, 'india_post_import'),
  ('413223', 'Maharashtra', true, true, 'india_post_import'),
  ('413224', 'Maharashtra', true, true, 'india_post_import'),
  ('413226', 'Maharashtra', true, true, 'india_post_import'),
  ('413227', 'Maharashtra', true, true, 'india_post_import'),
  ('413228', 'Maharashtra', true, true, 'india_post_import'),
  ('413229', 'Maharashtra', true, true, 'india_post_import'),
  ('413248', 'Maharashtra', true, true, 'india_post_import'),
  ('413249', 'Maharashtra', true, true, 'india_post_import'),
  ('413250', 'Maharashtra', true, true, 'india_post_import'),
  ('413251', 'Maharashtra', true, true, 'india_post_import'),
  ('413252', 'Maharashtra', true, true, 'india_post_import'),
  ('413253', 'Maharashtra', true, true, 'india_post_import'),
  ('413255', 'Maharashtra', true, true, 'india_post_import'),
  ('413301', 'Maharashtra', true, true, 'india_post_import'),
  ('413302', 'Maharashtra', true, true, 'india_post_import'),
  ('413303', 'Maharashtra', true, true, 'india_post_import'),
  ('413304', 'Maharashtra', true, true, 'india_post_import'),
  ('413305', 'Maharashtra', true, true, 'india_post_import'),
  ('413306', 'Maharashtra', true, true, 'india_post_import'),
  ('413307', 'Maharashtra', true, true, 'india_post_import'),
  ('413308', 'Maharashtra', true, true, 'india_post_import'),
  ('413309', 'Maharashtra', true, true, 'india_post_import'),
  ('413310', 'Maharashtra', true, true, 'india_post_import'),
  ('413314', 'Maharashtra', true, true, 'india_post_import'),
  ('413315', 'Maharashtra', true, true, 'india_post_import'),
  ('413317', 'Maharashtra', true, true, 'india_post_import'),
  ('413319', 'Maharashtra', true, true, 'india_post_import'),
  ('413322', 'Maharashtra', true, true, 'india_post_import'),
  ('413324', 'Maharashtra', true, true, 'india_post_import'),
  ('413401', 'Maharashtra', true, true, 'india_post_import'),
  ('413402', 'Maharashtra', true, true, 'india_post_import'),
  ('413403', 'Maharashtra', true, true, 'india_post_import'),
  ('413404', 'Maharashtra', true, true, 'india_post_import'),
  ('413405', 'Maharashtra', true, true, 'india_post_import'),
  ('413406', 'Maharashtra', true, true, 'india_post_import'),
  ('413409', 'Maharashtra', true, true, 'india_post_import'),
  ('413410', 'Maharashtra', true, true, 'india_post_import'),
  ('413411', 'Maharashtra', true, true, 'india_post_import'),
  ('413412', 'Maharashtra', true, true, 'india_post_import'),
  ('413501', 'Maharashtra', true, true, 'india_post_import'),
  ('413502', 'Maharashtra', true, true, 'india_post_import'),
  ('413503', 'Maharashtra', true, true, 'india_post_import'),
  ('413504', 'Maharashtra', true, true, 'india_post_import'),
  ('413505', 'Maharashtra', true, true, 'india_post_import'),
  ('413506', 'Maharashtra', true, true, 'india_post_import'),
  ('413507', 'Maharashtra', true, true, 'india_post_import'),
  ('413508', 'Maharashtra', true, true, 'india_post_import'),
  ('413509', 'Maharashtra', true, true, 'india_post_import'),
  ('413510', 'Maharashtra', true, true, 'india_post_import'),
  ('413511', 'Maharashtra', true, true, 'india_post_import'),
  ('413512', 'Maharashtra', true, true, 'india_post_import'),
  ('413513', 'Maharashtra', true, true, 'india_post_import'),
  ('413514', 'Maharashtra', true, true, 'india_post_import'),
  ('413515', 'Maharashtra', true, true, 'india_post_import'),
  ('413516', 'Maharashtra', true, true, 'india_post_import'),
  ('413517', 'Maharashtra', true, true, 'india_post_import'),
  ('413518', 'Maharashtra', true, true, 'india_post_import'),
  ('413519', 'Maharashtra', true, true, 'india_post_import'),
  ('413520', 'Maharashtra', true, true, 'india_post_import'),
  ('413521', 'Maharashtra', true, true, 'india_post_import'),
  ('413522', 'Maharashtra', true, true, 'india_post_import'),
  ('413523', 'Maharashtra', true, true, 'india_post_import'),
  ('413524', 'Maharashtra', true, true, 'india_post_import'),
  ('413525', 'Maharashtra', true, true, 'india_post_import'),
  ('413526', 'Maharashtra', true, true, 'india_post_import'),
  ('413527', 'Maharashtra', true, true, 'india_post_import'),
  ('413528', 'Maharashtra', true, true, 'india_post_import'),
  ('413529', 'Maharashtra', true, true, 'india_post_import'),
  ('413530', 'Maharashtra', true, true, 'india_post_import'),
  ('413531', 'Maharashtra', true, true, 'india_post_import'),
  ('413532', 'Maharashtra', true, true, 'india_post_import'),
  ('413534', 'Maharashtra', true, true, 'india_post_import'),
  ('413544', 'Maharashtra', true, true, 'india_post_import'),
  ('413581', 'Maharashtra', true, true, 'india_post_import'),
  ('413582', 'Maharashtra', true, true, 'india_post_import'),
  ('413601', 'Maharashtra', true, true, 'india_post_import'),
  ('413602', 'Maharashtra', true, true, 'india_post_import'),
  ('413603', 'Maharashtra', true, true, 'india_post_import'),
  ('413604', 'Maharashtra', true, true, 'india_post_import'),
  ('413605', 'Maharashtra', true, true, 'india_post_import'),
  ('413606', 'Maharashtra', true, true, 'india_post_import'),
  ('413607', 'Maharashtra', true, true, 'india_post_import'),
  ('413608', 'Maharashtra', true, true, 'india_post_import'),
  ('413623', 'Maharashtra', true, true, 'india_post_import'),
  ('413624', 'Maharashtra', true, true, 'india_post_import'),
  ('413701', 'Maharashtra', true, true, 'india_post_import'),
  ('413702', 'Maharashtra', true, true, 'india_post_import'),
  ('413703', 'Maharashtra', true, true, 'india_post_import'),
  ('413704', 'Maharashtra', true, true, 'india_post_import'),
  ('413705', 'Maharashtra', true, true, 'india_post_import'),
  ('413706', 'Maharashtra', true, true, 'india_post_import'),
  ('413707', 'Maharashtra', true, true, 'india_post_import'),
  ('413708', 'Maharashtra', true, true, 'india_post_import'),
  ('413709', 'Maharashtra', true, true, 'india_post_import'),
  ('413710', 'Maharashtra', true, true, 'india_post_import'),
  ('413711', 'Maharashtra', true, true, 'india_post_import'),
  ('413712', 'Maharashtra', true, true, 'india_post_import'),
  ('413713', 'Maharashtra', true, true, 'india_post_import'),
  ('413714', 'Maharashtra', true, true, 'india_post_import'),
  ('413715', 'Maharashtra', true, true, 'india_post_import'),
  ('413716', 'Maharashtra', true, true, 'india_post_import'),
  ('413717', 'Maharashtra', true, true, 'india_post_import'),
  ('413718', 'Maharashtra', true, true, 'india_post_import'),
  ('413719', 'Maharashtra', true, true, 'india_post_import'),
  ('413720', 'Maharashtra', true, true, 'india_post_import'),
  ('413721', 'Maharashtra', true, true, 'india_post_import'),
  ('413722', 'Maharashtra', true, true, 'india_post_import'),
  ('413723', 'Maharashtra', true, true, 'india_post_import'),
  ('413725', 'Maharashtra', true, true, 'india_post_import'),
  ('413726', 'Maharashtra', true, true, 'india_post_import'),
  ('413728', 'Maharashtra', true, true, 'india_post_import'),
  ('413736', 'Maharashtra', true, true, 'india_post_import'),
  ('413737', 'Maharashtra', true, true, 'india_post_import'),
  ('413738', 'Maharashtra', true, true, 'india_post_import'),
  ('413739', 'Maharashtra', true, true, 'india_post_import'),
  ('413801', 'Maharashtra', true, true, 'india_post_import'),
  ('413802', 'Maharashtra', true, true, 'india_post_import'),
  ('414001', 'Maharashtra', true, true, 'india_post_import'),
  ('414002', 'Maharashtra', true, true, 'india_post_import'),
  ('414003', 'Maharashtra', true, true, 'india_post_import'),
  ('414005', 'Maharashtra', true, true, 'india_post_import'),
  ('414006', 'Maharashtra', true, true, 'india_post_import'),
  ('414101', 'Maharashtra', true, true, 'india_post_import'),
  ('414102', 'Maharashtra', true, true, 'india_post_import'),
  ('414103', 'Maharashtra', true, true, 'india_post_import'),
  ('414105', 'Maharashtra', true, true, 'india_post_import'),
  ('414106', 'Maharashtra', true, true, 'india_post_import'),
  ('414110', 'Maharashtra', true, true, 'india_post_import'),
  ('414111', 'Maharashtra', true, true, 'india_post_import'),
  ('414113', 'Maharashtra', true, true, 'india_post_import'),
  ('414201', 'Maharashtra', true, true, 'india_post_import'),
  ('414202', 'Maharashtra', true, true, 'india_post_import'),
  ('414203', 'Maharashtra', true, true, 'india_post_import'),
  ('414204', 'Maharashtra', true, true, 'india_post_import'),
  ('414205', 'Maharashtra', true, true, 'india_post_import'),
  ('414208', 'Maharashtra', true, true, 'india_post_import'),
  ('414301', 'Maharashtra', true, true, 'india_post_import'),
  ('414302', 'Maharashtra', true, true, 'india_post_import'),
  ('414303', 'Maharashtra', true, true, 'india_post_import'),
  ('414304', 'Maharashtra', true, true, 'india_post_import'),
  ('414305', 'Maharashtra', true, true, 'india_post_import'),
  ('414306', 'Maharashtra', true, true, 'india_post_import'),
  ('414401', 'Maharashtra', true, true, 'india_post_import'),
  ('414402', 'Maharashtra', true, true, 'india_post_import'),
  ('414403', 'Maharashtra', true, true, 'india_post_import'),
  ('414501', 'Maharashtra', true, true, 'india_post_import'),
  ('414502', 'Maharashtra', true, true, 'india_post_import'),
  ('414503', 'Maharashtra', true, true, 'india_post_import'),
  ('414504', 'Maharashtra', true, true, 'india_post_import'),
  ('414505', 'Maharashtra', true, true, 'india_post_import'),
  ('414601', 'Maharashtra', true, true, 'india_post_import'),
  ('414602', 'Maharashtra', true, true, 'india_post_import'),
  ('414603', 'Maharashtra', true, true, 'india_post_import'),
  ('414604', 'Maharashtra', true, true, 'india_post_import'),
  ('414605', 'Maharashtra', true, true, 'india_post_import'),
  ('414606', 'Maharashtra', true, true, 'india_post_import'),
  ('414607', 'Maharashtra', true, true, 'india_post_import'),
  ('414609', 'Maharashtra', true, true, 'india_post_import'),
  ('414701', 'Maharashtra', true, true, 'india_post_import'),
  ('415001', 'Maharashtra', true, true, 'india_post_import'),
  ('415002', 'Maharashtra', true, true, 'india_post_import'),
  ('415003', 'Maharashtra', true, true, 'india_post_import'),
  ('415004', 'Maharashtra', true, true, 'india_post_import'),
  ('415010', 'Maharashtra', true, true, 'india_post_import'),
  ('415011', 'Maharashtra', true, true, 'india_post_import'),
  ('415012', 'Maharashtra', true, true, 'india_post_import'),
  ('415013', 'Maharashtra', true, true, 'india_post_import'),
  ('415014', 'Maharashtra', true, true, 'india_post_import'),
  ('415015', 'Maharashtra', true, true, 'india_post_import'),
  ('415019', 'Maharashtra', true, true, 'india_post_import'),
  ('415020', 'Maharashtra', true, true, 'india_post_import'),
  ('415021', 'Maharashtra', true, true, 'india_post_import'),
  ('415022', 'Maharashtra', true, true, 'india_post_import'),
  ('415023', 'Maharashtra', true, true, 'india_post_import'),
  ('415101', 'Maharashtra', true, true, 'india_post_import'),
  ('415102', 'Maharashtra', true, true, 'india_post_import'),
  ('415103', 'Maharashtra', true, true, 'india_post_import'),
  ('415104', 'Maharashtra', true, true, 'india_post_import'),
  ('415105', 'Maharashtra', true, true, 'india_post_import'),
  ('415106', 'Maharashtra', true, true, 'india_post_import'),
  ('415107', 'Maharashtra', true, true, 'india_post_import'),
  ('415108', 'Maharashtra', true, true, 'india_post_import'),
  ('415109', 'Maharashtra', true, true, 'india_post_import'),
  ('415110', 'Maharashtra', true, true, 'india_post_import'),
  ('415111', 'Maharashtra', true, true, 'india_post_import'),
  ('415112', 'Maharashtra', true, true, 'india_post_import'),
  ('415114', 'Maharashtra', true, true, 'india_post_import'),
  ('415115', 'Maharashtra', true, true, 'india_post_import'),
  ('415116', 'Maharashtra', true, true, 'india_post_import'),
  ('415122', 'Maharashtra', true, true, 'india_post_import'),
  ('415124', 'Maharashtra', true, true, 'india_post_import'),
  ('415202', 'Maharashtra', true, true, 'india_post_import'),
  ('415203', 'Maharashtra', true, true, 'india_post_import'),
  ('415205', 'Maharashtra', true, true, 'india_post_import'),
  ('415206', 'Maharashtra', true, true, 'india_post_import'),
  ('415207', 'Maharashtra', true, true, 'india_post_import'),
  ('415208', 'Maharashtra', true, true, 'india_post_import'),
  ('415209', 'Maharashtra', true, true, 'india_post_import'),
  ('415211', 'Maharashtra', true, true, 'india_post_import'),
  ('415212', 'Maharashtra', true, true, 'india_post_import'),
  ('415213', 'Maharashtra', true, true, 'india_post_import'),
  ('415214', 'Maharashtra', true, true, 'india_post_import'),
  ('415301', 'Maharashtra', true, true, 'india_post_import'),
  ('415302', 'Maharashtra', true, true, 'india_post_import'),
  ('415303', 'Maharashtra', true, true, 'india_post_import'),
  ('415304', 'Maharashtra', true, true, 'india_post_import'),
  ('415305', 'Maharashtra', true, true, 'india_post_import'),
  ('415306', 'Maharashtra', true, true, 'india_post_import')
on conflict (pincode) do nothing;